"use client";
import {useCallback,useEffect,useState} from "react";
import type {Principal} from "@finai/contracts";
import {Badge,Empty} from "./g8-ui";
import {displayName} from "./display-name";
import {commands,stepLabel,workPath,workState,type ActionItem,type WorkRun} from "./action-model";
import "./action-workbench.css";
import PromotionReadiness from "./promotion-readiness";
import {Value} from "./operator-history";

const label=(s:string)=>s.toLowerCase().replaceAll("_"," ");
const commandLabel=(s:string)=>({complete:"Acknowledge source review",resume:"Resume",pause:"Pause",retry:"Retry processing",cancel:"Cancel process"}[s]??s);
type Queue={items:ActionItem[];truncated:boolean};
export default function ActionWorkbench({token,principal,companyId,onInspect}:{token:string;principal:Principal;companyId:string;onInspect:(id:string)=>void}){
 const contextKey=`g8-actions:${principal.actor_id}:${JSON.stringify(principal.scope)}:${companyId}`;
 const [saved]=useState(()=>{try{return JSON.parse(sessionStorage.getItem(contextKey)??"{}");}catch{return {};}});
 const [selected,setSelected]=useState<string>(typeof saved.selected==="string"?saved.selected:"");
 const [unbound,setUnbound]=useState(saved.unbound===true);const [filter,setFilter]=useState(typeof saved.filter==="string"?saved.filter.slice(0,128):"");
 const [queue,setQueue]=useState<Queue|null>(null);const [run,setRun]=useState<WorkRun|null>(null);
 const [queueError,setQueueError]=useState("");const [error,setError]=useState("");const [revision,setRevision]=useState(0);
 const [busy,setBusy]=useState(false);const [reason,setReason]=useState("");const [notice,setNotice]=useState("");
 const [reviewOpen,setReviewOpen]=useState(saved.reviewOpen===true);const [decision,setDecision]=useState("REJECTED");
 const [pending,setPending]=useState<{command:string;reason:string;idempotency_key:string}|null>(null);
 const active=queue?.items.find(i=>i.workflow_id===selected);
 const api=useCallback(async<T,>(path:string,body?:unknown,signal?:AbortSignal):Promise<T>=>{const response=await fetch(`/api/${path}`,{method:body?"POST":"GET",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},cache:"no-store",signal,...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw Object.assign(Error(typeof data.detail==="string"?data.detail:`Work unavailable (${response.status})`),{status:response.status});return data;},[token]);
 useEffect(()=>{try{sessionStorage.setItem(contextKey,JSON.stringify({version:1,selected,unbound,filter,reviewOpen}));}catch{/* State remains available during this visit. */}},[contextKey,selected,unbound,filter,reviewOpen]);
 useEffect(()=>{const controller=new AbortController();
  const query=new URLSearchParams({include_unbound:String(unbound)});if(companyId)query.set("company_id",companyId);
  void api<Queue>(`workspace/workflows/workbench?${query}`,undefined,controller.signal).then(data=>{if(!controller.signal.aborted){setQueue(data);setQueueError("");}}).catch(e=>{if(!controller.signal.aborted){setQueue(null);setQueueError(String(e));}});
  return()=>controller.abort();
 },[api,companyId,unbound,revision]);
 useEffect(()=>{if(!active||active.family==="unsupported")return;const controller=new AbortController();
  void api<WorkRun>(workPath(active),undefined,controller.signal).then(data=>{if(!controller.signal.aborted){setRun(data);setError("");}}).catch(e=>{if(!controller.signal.aborted){setRun(null);setError(String(e));}});
  return()=>controller.abort();
 },[api,active,revision]);
 const current=active&&run&&(run.operation_id??run.workflow_id)===active.workflow_id?run:null;
 const state=current&&active?workState(active.family,current):"";
 function choose(id:string){setSelected(id);setRun(null);setError("");setReason("");setNotice("");setReviewOpen(false);setPending(null);}
 async function control(command:string){if(!active||!current)return;setBusy(true);setError("");
  const intent=pending??{command,reason:reason.trim(),idempotency_key:crypto.randomUUID()};setPending(intent);
  try{const response=await api<{state:string}>(`${workPath(active)}/${active.family==="ontology"?"resume":"control"}`,active.family==="ontology"?{}:intent);
   setNotice(response.state==="SIGNALLED"?"Request retained and sent. Refresh to confirm the resulting state.":"Command returned. Reading the authoritative state…");
   const latest=await api<WorkRun>(workPath(active));setRun(latest);setPending(null);setReason("");
   setNotice(`Authoritative readback: ${label(workState(active.family,latest))}. Financial approval and external effects remain separate.`);
  }catch(e){const status=(e as {status?:number}).status;if(status&&status>=400&&status<500)setPending(null);setError(`${String(e)}. ${!(status&&status>=400&&status<500)?"Check current state; an uncertain request must be retried with the same identity.":"The server refused this command."}`);}finally{setBusy(false);}
 }
 async function review(){if(!current?.proposal||!active)return;setBusy(true);setError("");try{await api(`ontology/proposals/${current.proposal.proposal.proposal_id}/decision`,{decision,rationale:reason.trim()});setRun(await api<WorkRun>(workPath(active)));setNotice("Independent decision retained and read back from the shared proposal authority.");setReason("");}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function download(id:string,source:boolean,expectedHash?:string,filename?:string){try{const path=source?`workspace/constructions/${id}/source`:`ontology/source-documents/${id}/content`;const response=await fetch(`/api/${path}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw Error("Evidence unavailable for this identity");const blob=await response.blob();const expected=expectedHash??response.headers.get("x-content-sha256");if(expected){const hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",await blob.arrayBuffer())),b=>b.toString(16).padStart(2,"0")).join("");if(hash!==expected)throw Error("Evidence integrity check failed; download withheld");}const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename??(source?"retained-source":"original-evidence");a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(String(e));}}
 const visible=queue?.items.filter(i=>`${i.title} ${i.family}`.toLowerCase().includes(filter.toLowerCase()))??[];
 const available=active&&current?commands(active.family,current,principal.permissions,principal.actor_id):[];
 return <section className="g8-actions" aria-label="Governed workbench"><div className="g8-actions-toolbar"><label>Find work<input maxLength={128} value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Name or process family"/></label>{companyId&&<label className="g8-actions-check"><input type="checkbox" disabled={busy||!!pending} checked={unbound} onChange={e=>{setUnbound(e.target.checked);choose("");}}/>Include work without company binding</label>}<button disabled={busy} onClick={()=>setRevision(r=>r+1)}>Refresh work</button></div>
 <p>Source checks, regulatory monitoring and reviewed business changes share retained requests and receipts. This workbench does not execute external financial postings.</p>
 {queueError&&<p role="alert">{queueError}</p>}{queue?.truncated&&<p>Showing the latest 100 requests in this scope.</p>}
 <div className="g8-actions-body"><nav aria-label="Retained work">{visible.map(item=><button disabled={busy||!!pending} aria-pressed={selected===item.workflow_id} key={item.workflow_id} onClick={()=>choose(item.workflow_id)}><strong>{displayName(item.title)}</strong><span>{item.family==="ontology"?"Business change":item.family==="monitor"?"Regulatory monitoring":"Source processing"}</span><small>{item.company_id?"Explicit company binding":"No canonical company binding"}{item.period?` · ${item.period} · ${item.currency}`:""}</small><small>Requested {new Date(item.created_at).toLocaleString()}</small></button>)}{!visible.length&&<Empty title={queue?"No matching work":"Loading work…"}>{companyId?"Only explicitly company-bound work is included. Other authorized work can be included above.":"Retained requests in your authorized scope appear here."}</Empty>}</nav>
 <div className="g8-action-detail">{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{!active?<Empty title="Select work to investigate">Open its state, evidence, process history and permitted controls.</Empty>:!current?<p role="status">{error?"Current work is unavailable.":active.family==="unsupported"?"This process family has no operator controls yet.":"Reading authoritative process state…"}</p>:<>
 <header><h2>{displayName(active.title)}</h2><Badge tone={state==="FAILED"||state==="UNOBSERVABLE"?"warning":"neutral"}>{label(state)}</Badge><p>{active.company_id?"Company binding retained in the action request.":"This request is authorized for your sign-in scope; it has no canonical company binding."}</p>{current.freshness&&<p>Source freshness: {label(current.freshness)} · {label(current.source_health??"unknown")}</p>}</header>
 <div className="g8-process" aria-label="Recorded process steps">{(current.definition.nodes??[]).map(node=>{const latest=[...current.events].reverse().find(e=>e.node===node.id&&e.state);return <div key={node.id}><strong>{stepLabel(node.id)}</strong><span>{latest?label(latest.state!):node.id==="review"&&state==="WAITING_REVIEW"?"Awaiting independent review":"No completion receipt recorded"}</span><small>{node.depends_on.length?`After ${node.depends_on.map(stepLabel).join(", ")}`:"First step"}</small></div>;})}{active.family==="ontology"&&<><div><strong>Prepared change</strong><span>Frozen proposal retained</span></div><div><strong>Shared proposal</strong><span>{current.proposal?"Proposal receipt available":"Awaiting submission"}</span></div><div><strong>Independent decision</strong><span>{current.proposal?.decision?label(current.proposal.decision):"Awaiting review"}</span></div></>}{active.family==="monitor"&&<><div><strong>Scheduled checks</strong><span>{label(state)}</span></div><div><strong>Source evidence</strong><span>{label(current.source_health??"not checked")}</span></div><div><strong>Next scheduled check</strong><span>{current.runtime?.next_checks?.[0]?new Date(current.runtime.next_checks[0]).toLocaleString():"No observable next check"}</span></div></>}</div>
 <section className="g8-command-panel" aria-label="Permitted actions"><h3>Available actions</h3><p>{active.family==="ontology"?"Resume submits the same frozen proposal for independent review.":active.family==="monitor"?"Pause stops future scheduled checks. A check already running can finish.":"Source review acknowledges the assessment; it does not certify financial values."}</p>{available.length>0&&active.family!=="ontology"&&<label>Reason for action<textarea value={reason} disabled={busy||!!pending} onChange={e=>setReason(e.target.value)} minLength={10} maxLength={2000}/></label>}{pending?<button disabled={busy} onClick={()=>void control(pending!.command)}>Retry retained request</button>:available.map(command=><button key={command} disabled={busy||(active.family!=="ontology"&&reason.trim().length<10)} onClick={()=>void control(command)}>{commandLabel(command)}</button>)}{!available.length&&!pending&&<p>{state==="UNOBSERVABLE"?"Controls are unavailable until authoritative runtime state can be read.":"No process control is available in this state for your identity."}</p>}</section>
 {current.proposal&&<section><h3>Business decision</h3><p>{current.proposal.proposal.rationale}</p><button aria-expanded={reviewOpen} onClick={()=>setReviewOpen(!reviewOpen)}>Inspect proposed change & review</button>{reviewOpen&&<><PromotionReadiness token={token} proposalId={current.proposal.proposal.proposal_id}/><div className="g8-table-scroll"><table><thead><tr><th>Business object</th><th>Change</th><th>Fields affected</th></tr></thead><tbody>{current.proposal.validation.impact.map(change=><tr key={change.resource_id}><td>{displayName(change.name)}</td><td>{label(change.operation)}</td><td>{change.fields_changed.map(stepLabel).join(", ")}{change.semantic_diff?<details><summary>Review exact before and after</summary><table><thead><tr><th>Property</th><th>Before</th><th>Proposed</th></tr></thead><tbody>{change.semantic_diff.changes.map(diff=><tr key={diff.path}><td>{diff.path.split("/").slice(1).map(p=>p.replaceAll("~1","/").replaceAll("~0","~").replaceAll("_"," ")).join(" › ")}</td><td><Value entry={diff.before} onInspect={onInspect}/></td><td><Value entry={diff.after} onInspect={onInspect}/></td></tr>)}</tbody></table></details>:<p>No detailed before/after comparison was retained.</p>}</td></tr>)}</tbody></table></div>{current.proposal.decision?<p>Decision: {label(current.proposal.decision)} · {current.proposal.review_rationale}</p>:principal.permissions.includes("ontology_review")&&current.proposal.submitted_by!==principal.actor_id?<form onSubmit={e=>{e.preventDefault();void review();}}><label>Independent decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="REJECTED">Reject</option><option value="APPROVED" disabled={current.proposal.validation.downstream_impact?.status!=="COMPLETE"}>Approve after checking impact</option></select></label><label>Decision rationale<textarea required minLength={10} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||reason.trim().length<10}>Record independent decision</button></form>:<p>An independent authorized reviewer must decide this proposal.</p>}</>}{current.proposal.decision==="APPROVED"&&current.proposal.proposal.mutations.map(m=><button className="g8-link" key={m.resource_id} onClick={()=>onInspect(m.resource_id)}>{displayName(m.display_name)} · inspect accepted object</button>)}</section>}
 <section><h3>Evidence & results</h3>{current.request?.report?.receipt_ids.map((id,i)=><button key={id} disabled={!principal.permissions.includes("export")} onClick={()=>void download(id,true)}>Download source {i+1}</button>)}{current.events.filter(e=>e.document).map(e=><button key={e.event_id} onClick={()=>void download(e.document!.document_id,false,e.document!.sha256,e.document!.filename)}>Download {e.document!.filename}</button>)}{[...new Set(current.events.map(e=>e.document_id).filter((id):id is string=>!!id))].map((id,i)=><button key={id} onClick={()=>void download(id,false)}>Open original evidence {i+1}</button>)}{current.publications?.map(p=><p key={p.publication_id}>Output set {p.generation+1}: {p.outputs.length} retained results · execution evidence only</p>)}</section>
 <details open><summary>Decision and execution history · {current.events.length} retained events</summary><div className="g8-table-scroll"><table><thead><tr><th>Recorded</th><th>Step / decision</th><th>State</th><th>Reason</th></tr></thead><tbody>{[...current.events].reverse().map(e=><tr key={e.event_id}><td>{new Date(e.created_at).toLocaleString()}</td><td>{stepLabel(e.node??"Process")}</td><td>{label(e.state??(e.command?`${e.command} ${e.event_id.endsWith(":applied")?"applied":"requested"}`:"Recorded"))}</td><td>{e.reason??"—"}</td></tr>)}</tbody></table></div></details><details><summary>Exact execution reference</summary><p>{active.workflow_id}</p><p>{current.definition.version}</p></details>
 </>}</div></div></section>;
}
