"use client";
import {useEffect,useRef,useState} from "react";
import type {CanonicalResource} from "@finai/contracts";
import type {FinanceReportReference} from "./finance-report-reference";
import SavedAnalysisWorkbench from "./saved-analysis-workbench";
import {assertTransformationPreview,type TransformationPreview} from "./transformation-preview";
import {restorationInstant} from "./definition-restoration-time";
import "./builds-workbench.css";
type Pin={resource_id:string;version_id:string};
type BuildRequest={request_id:string;transformation:Pin;valid_at:string;known_at:string};
type Definition={reference:Pin;display_name:string;attributes:Record<string,unknown>;content_hash:string};
type Node={node_id:string;depends_on:string[];input_binding?:{upstream_node_id:string};invocation:{request_id:string;function:Pin;input_result?:{invocation_id:string}}};
type ResourceBudget={max_returned_rows:number;max_derived_evaluations:number;max_published_result_bytes:number};
type WorkUsage={measurement:"POSTGRES_JSONB_TEXT_UTF8_V1";returned_rows:number;derived_evaluations:number;published_result_bytes:number};
type Terminal={node:string;state:string;output?:{invocation_id:string;run_id?:string;receipt_hash:string|null};new_run_required?:boolean;usage?:WorkUsage;cumulative_usage?:WorkUsage;resource_budget?:ResourceBudget};
type PublicationReview={task_id:string;question:string;state:"NOT_REQUESTED"|"PENDING"|"APPROVED"|"REJECTED"|"CANCELLED";outputs:Array<{output_id:string;node_id:string;invocation_id:string;receipt_hash:string;run_id:string}>;decision:null|{task_id:string;state:"APPROVED"|"REJECTED";decision_id:string;actor_id:string;reason:string};run_actor_id:string};
type BindingReview={state:"NOT_REQUESTED"|"PENDING"|"APPROVED"|"REJECTED"|"CANCELLED";binding:Pin&{content_hash:string};source_node_id:string;operation_request_id:string;operation_id:string|null;proposal_id:string|null;input_result:{invocation_id:string;receipt_hash:string;run_id:string}|null;decision:"APPROVED"|"REJECTED"|null;proposal_history_independent:true};
type BuildRun={binding_review?:BindingReview|null;publication_review?:PublicationReview|null;workflow_id:string;current_use_authorized:false;business_effect_authorized:false;request:{compiled_plan:{execution_policy?:{max_concurrent_nodes:number};resource_budget?:ResourceBudget;estimated_work?:{returned_rows:number;derived_evaluations:number};result_bytes_accounting?:string;request:BuildRequest;nodes:Node[];outputs:Array<{output_id:string;node_id:string}>}};definition:{version:string;nodes:Node[]};events:Array<Terminal&{event_id:string;created_at:string;command?:string;reason?:string}>;publications:Array<{publication_id:string;generation:number}>;runtime_status:string;execution?:{state:string;result:Record<string,Terminal>;pause_requested:boolean;cancel_requested:boolean}};
type Control={command:"pause"|"resume"|"cancel";reason:string;idempotency_key:string};
type Props={onInspectAnalysis?:(reference:{resource_id:string;version_id:string;known_at:string})=>void;companyId?:string;onOpenFinance?:(reference:FinanceReportReference)=>void;onProposal?:(id:string)=>void;canReview?:boolean;actorId?:string;initialRequestId?:string;initialTransformation?:Pin;token:string;companyName:string;canControl:boolean;onInspect:(resource:CanonicalResource,knownAt:string)=>void;onTrace:(resource:CanonicalResource,knownAt:string)=>void};
const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
const human=(value:string)=>value.toLowerCase().replaceAll("_"," ");
export default function BuildsWorkbench(props:Props){return <Builds key={`${props.token}:${props.companyId??"workspace"}:${props.initialRequestId??"none"}`} {...props}/>;}
function Builds({onInspectAnalysis,companyId,onOpenFinance,token,companyName,canControl,onInspect,onTrace,onProposal,initialRequestId,initialTransformation,canReview=false,actorId=""}:Props){
 const summaryHeading=useRef<HTMLHeadingElement|null>(null);
 const [preview,setPreview]=useState<TransformationPreview|null>(null);
 const [startAttempted,setStartAttempted]=useState(false);
 const [historyRevision,setHistoryRevision]=useState(0);
 const [catalog,setCatalog]=useState<Definition[]>([]);const [after,setAfter]=useState<string|null>(null);const [next,setNext]=useState<string|null>(null);const [catalogRevision,setCatalogRevision]=useState(0);const [catalogBusy,setCatalogBusy]=useState(true);const [catalogError,setCatalogError]=useState("");
 const [selected,setSelected]=useState("");const [validAt,setValidAt]=useState(()=>new Date().toISOString());const [knownAt,setKnownAt]=useState(()=>new Date().toISOString());const [frozen,setFrozen]=useState<BuildRequest|null>(null);const [runId,setRunId]=useState("");const [run,setRun]=useState<BuildRun|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [reason,setReason]=useState("");const [pendingControl,setPendingControl]=useState<Control|null>(null);const [outputId,setOutputId]=useState("");const active=useRef<AbortController|null>(null);
 useEffect(()=>()=>{active.current?.abort();active.current=null;},[]);
 useEffect(()=>{
  if(!initialRequestId)return;
  const controller=new AbortController();active.current=controller;const timer=setTimeout(()=>controller.abort(),20000);
  async function reopen(){setBusy(true);setRunId(initialRequestId!);setError("");try{
   if(!uuid.test(initialRequestId!))throw new Error("The retained build reference is invalid.");
   const response=await fetch(`/api/ontology/transformations/runs/${initialRequestId}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store",signal:controller.signal});
   if(!response.ok)throw new Error(`Retained build is unavailable (${response.status}).`);
   const data:BuildRun=await response.json();const request=data.request?.compiled_plan?.request;
   if(data.workflow_id!==`transformation:${initialRequestId}`||request?.request_id!==initialRequestId||data.current_use_authorized!==false||data.business_effect_authorized!==false||!Array.isArray(data.events)||initialTransformation&&(request.transformation.resource_id!==initialTransformation.resource_id||request.transformation.version_id!==initialTransformation.version_id))throw new Error("Returned evidence did not match the selected build and transformation.");
   if(active.current===controller&&!controller.signal.aborted)setRun(data);
  }catch(failure){if(active.current===controller)setError(controller.signal.aborted?"Retained build lookup timed out. Reopen the same reference to retry.":failure instanceof Error?failure.message:"Build unavailable");}
  finally{clearTimeout(timer);if(active.current===controller)setBusy(false);}}
  void reopen();return()=>{clearTimeout(timer);controller.abort();if(active.current===controller)active.current=null;};
 },[token,initialRequestId,initialTransformation]);
 useEffect(()=>{if(run&&summaryHeading.current){summaryHeading.current.scrollIntoView({block:"start"});summaryHeading.current.focus({preventScroll:true});}},[run]);
 useEffect(()=>{const controller=new AbortController();let disposed=false;const timer=setTimeout(()=>controller.abort(),20000);async function load(){setCatalogBusy(true);setCatalogError("");try{const response=await fetch(`/api/ontology/transformations${after?`?after_resource_id=${after}`:""}`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal,cache:"no-store"});if(!response.ok)throw new Error("Reviewed builds are unavailable.");const data:{items:Definition[];next_cursor:string|null;purpose:string}=await response.json();if(data.purpose!=="EVIDENCE_ANALYSIS_ONLY"||!Array.isArray(data.items)||after&&data.next_cursor===after)throw new Error("Build catalog could not be verified.");if(!disposed){setCatalog(previous=>Array.from(new Map([...(after?previous:[]),...data.items].map(item=>[item.reference.version_id,item])).values()));setNext(data.next_cursor);}}catch(failure){if(!disposed)setCatalogError(controller.signal.aborted?"Build catalog timed out.":failure instanceof Error?failure.message:"Catalog unavailable");}finally{clearTimeout(timer);if(!disposed)setCatalogBusy(false);}}void load();return()=>{disposed=true;clearTimeout(timer);controller.abort();};},[token,after,catalogRevision]);
 async function api<T,>(path:string,signal:AbortSignal,body?:unknown):Promise<T>{const response=await fetch(`/api/ontology/transformations${path}`,{method:body?"POST":"GET",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},signal,cache:"no-store",...(body?{body:JSON.stringify(body)}:{})});if(!response.ok)throw new Error(`Build request could not be confirmed (${response.status}).`);return response.json();}
 async function read(id:string,signal:AbortSignal){const data=await api<BuildRun>(`/runs/${id}`,signal);if(data.workflow_id!==`transformation:${id}`||data.current_use_authorized!==false||data.business_effect_authorized!==false||!Array.isArray(data.events))throw new Error("Build evidence did not match this run.");return data;}
 async function action(kind:"start"|"read"|"control",request?:BuildRequest,command?:Control,readId?:string){
  if(busy)return;active.current?.abort();const controller=new AbortController();active.current=controller;const timer=setTimeout(()=>controller.abort(),20000);setBusy(true);setError("");setNotice("");const id=readId??request?.request_id??runId;
  if(kind!=="control"){setRun(null);setOutputId("");}
  try{
   if(kind==="start"){if(!request)throw Error("Preview the transformation before starting.");assertTransformationPreview(preview,request);setStartAttempted(true);const response=await api<{request_id:string;workflow_id:string;state:string;business_effect_authorized:false}>("/previewed-runs",controller.signal,{request,expected_plan_hash:preview.plan_hash});if(response.request_id!==id||response.workflow_id!==`transformation:${id}`||response.state!=="START_REQUEST_RECORDED"||response.business_effect_authorized!==false)throw new Error("Start receipt did not match the requested build.");if(active.current===controller&&!controller.signal.aborted)setHistoryRevision(value=>value+1);}
   if(kind==="control")await api(`/runs/${id}/control`,controller.signal,command);
   const data=await read(id,controller.signal);if(active.current===controller&&!controller.signal.aborted){setRun(data);setRunId(id);if(kind==="control"){setPendingControl(null);setReason("");setNotice("Control request sent; the displayed runtime readback reports what is currently observable.");}}
  }catch(failure){if(active.current===controller)setError(`${controller.signal.aborted?"Response timed out.":failure instanceof Error?failure.message:"Build unavailable"} The request may be retained; retry uses the same identity.`);}finally{clearTimeout(timer);if(active.current===controller)setBusy(false);}
 }
 async function start(){
  const definition=catalog.find(item=>item.reference.version_id===selected);if(!definition||busy)return;
  const valid=restorationInstant(validAt),known=restorationInstant(knownAt);
  if(!valid||!known){setError("Both times require an explicit timezone.");return;}
  const request={request_id:crypto.randomUUID(),transformation:definition.reference,valid_at:valid,known_at:known};
  active.current?.abort();const controller=new AbortController();active.current=controller;const timer=setTimeout(()=>controller.abort(),20000);setBusy(true);setError("");setPreview(null);setStartAttempted(false);
  try{const result=await api<unknown>("/preview",controller.signal,request);assertTransformationPreview(result,request);if(active.current===controller&&!controller.signal.aborted){setPreview(result);setFrozen(request);setRunId(request.request_id);setRun(null);setOutputId("");}}
  catch(failure){if(active.current===controller)setError(controller.signal.aborted?"Plan preview timed out. No build was started.":failure instanceof Error?failure.message:"Plan preview unavailable.");}
  finally{clearTimeout(timer);if(active.current===controller)setBusy(false);}
 }
 function control(command:Control["command"]){const intent=pendingControl??{command,reason:reason.trim(),idempotency_key:crypto.randomUUID()};setPendingControl(intent);void action("control",undefined,intent);}
 const observed=run&&run.runtime_status!=="UNOBSERVABLE";const state=observed?(run.execution?.state??run.runtime_status):"UNOBSERVABLE";const controllable=Boolean(canControl&&observed&&run?.runtime_status==="RUNNING"&&run.execution&&!["COMPLETED","FAILED","CANCELLED"].includes(run.execution.state));
 const nodes=run?.request.compiled_plan.nodes??[];
 const refused=run?.events.filter(event=>event.state==="BUDGET_REFUSED")??[];
 const terminal=(node:string)=>run?.execution?.result?.[node]??[...(run?.events??[])].reverse().find(event=>event.node===node&&["COMPLETED","FAILED","BUDGET_REFUSED"].includes(event.state));
 return <section className="builds-workbench" aria-label="Evidence builds"><header><p className="overline">REVIEWED EVIDENCE BUILDS</p><h3>Prepare evidence for analysis</h3><p>Each build uses reviewed source analyses in your authorized scope. Navigation context: {companyName||"none selected"}. Each retained output carries its own source and applicability contract. Open a financial report to inspect its reviewed accounting binding and posting coverage.</p></header>
  <div className="builds-controls"><label>Reviewed build<select disabled={busy||Boolean(frozen)||catalogBusy} value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Choose a reviewed build</option>{catalog.map(item=><option key={item.reference.version_id} value={item.reference.version_id}>{item.display_name}</option>)}</select></label><label>Effective at — timezone required<input disabled={busy||Boolean(frozen)} value={validAt} onChange={event=>setValidAt(event.target.value)}/></label><label>Known at — timezone required<input disabled={busy||Boolean(frozen)} value={knownAt} onChange={event=>setKnownAt(event.target.value)}/></label></div>
  {catalogBusy&&<p role="status">Loading reviewed builds…</p>}{catalogError&&<p role="alert">{catalogError}</p>}{!catalogBusy&&!catalogError&&!catalog.length&&<p>No reviewed builds were returned.</p>}{catalogError&&<button disabled={catalogBusy} onClick={()=>setCatalogRevision(value=>value+1)}>Retry build catalog</button>}{next&&<button disabled={catalogBusy||busy} onClick={()=>setAfter(next)}>Load more reviewed builds</button>}
  <div className="builds-actions">{!frozen?<button disabled={!canControl||busy||!selected||Boolean(pendingControl)} onClick={()=>void start()}>Preview transformation</button>:<><button disabled={busy} onClick={()=>void action("start",frozen)}>{startAttempted?"Retry exact inspected plan":"Start inspected plan"}</button><button disabled={busy||Boolean(pendingControl)} onClick={()=>{setFrozen(null);setRun(null);setOutputId("");}}>Choose another transformation</button></>}</div>
  {frozen&&preview&&<section className="builds-plan-preview" aria-label="Transformation plan preview"><h3>Review the transformation before running</h3><p>{preview.compiled_plan.nodes.length} steps · {preview.compiled_plan.outputs.length} declared outputs. This previews the execution plan; transformed rows are available only after execution.</p><p>Effective {new Date(frozen.valid_at).toLocaleString()} · known {new Date(frozen.known_at).toLocaleString()}</p><div className="builds-table"><table><thead><tr><th>Step</th><th>Required earlier steps</th></tr></thead><tbody>{preview.compiled_plan.nodes.map((node,index)=><tr key={node.node_id}><th>Step {index+1}</th><td>{node.depends_on.length?node.depends_on.map(id=>`Step ${preview.compiled_plan.nodes.findIndex(n=>n.node_id===id)+1}`).join(", "):"None"}</td></tr>)}</tbody></table></div><p>Limits: {preview.compiled_plan.resource_budget.max_returned_rows} returned rows · {preview.compiled_plan.resource_budget.max_derived_evaluations} derived evaluations · {preview.compiled_plan.resource_budget.max_published_result_bytes} output bytes.</p>{preview.compiled_plan.publication_review&&<p>Independent output review: {preview.compiled_plan.publication_review.question}</p>}{Boolean(preview.compiled_plan.binding_review)&&<p>Source binding requires a separate reviewed proposal.</p>}<p>Starting rechecks this exact plan. Changed definitions or inputs require a new preview; this action grants no accounting or external business effect.</p><details><summary>Advanced: exact scope, dependencies and plan</summary><pre>{JSON.stringify(preview,null,2)}</pre></details></section>}
  <BuildHistory token={token} revision={historyRevision} disabled={busy||Boolean(pendingControl)} onOpen={id=>{setFrozen(null);setRunId(id);void action("read",undefined,undefined,id);}}/>
  <details><summary>Reopen a retained build by reference</summary><label>Build request reference<input disabled={busy||Boolean(pendingControl)} value={runId} onChange={event=>{setRunId(event.target.value);setRun(null);setOutputId("");}}/></label><button disabled={busy||!uuid.test(runId)||Boolean(pendingControl)} onClick={()=>{setFrozen(null);void action("read");}}>Reopen build</button></details>
  {busy&&<p role="status">Waiting for build response…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {run&&<><h4 ref={summaryHeading} tabIndex={-1} className="builds-runtime-summary">Runtime: {human(state)}</h4>{!observed&&<p>Live runtime state is unavailable. Retained events and outputs remain historical evidence; this does not mean the build failed.</p>}{run.execution?.pause_requested&&<p>Pause requested; an active bounded node may still finish.</p>}{run.execution?.cancel_requested&&<p>Cancellation requested; confirm the next runtime readback.</p>}<button disabled={busy} onClick={()=>void action("read")}>Refresh build state</button><p>Steps start after their required earlier steps finish. A declared retained input names the result a step must read; consumed input evidence appears in the downstream analysis receipt.</p>
   <BuildExecutionPolicy policy={run.request.compiled_plan.execution_policy}/>
   {refused.length>0&&<section className="builds-budget-refusal" aria-label="Retained work-limit refusal"><h4>Work limit refused</h4><p>A retained step exceeded its reviewed work limit. This refusal remains part of the evidence even when live runtime state is unavailable. It does not establish completion or publication.</p><p>Review the build definition and its limits before starting a new run. Any retained analysis below is diagnostic evidence, not a published build result.</p>{refused.map(event=><div key={event.event_id}><strong>{human(event.node)}</strong>{event.cumulative_usage&&<BudgetTable usage={event.cumulative_usage} budget={event.resource_budget} label="Cumulative use at refusal"/>}</div>)}</section>}
   {run.request.compiled_plan.resource_budget&&<details className="builds-budget"><summary>Reviewed work limits and planned work</summary><BudgetTable budget={run.request.compiled_plan.resource_budget} estimate={run.request.compiled_plan.estimated_work} label="Reviewed build budget"/><p>Result bytes count the UTF-8 PostgreSQL JSONB text representation. This is not source-file size, disk allocation or memory usage.</p><small>Measurement contract: {run.request.compiled_plan.result_bytes_accounting??"Not recorded"}</small></details>}
   <div className="builds-table"><table><thead><tr><th>Step</th><th>Completes after</th><th>Outcome</th></tr></thead><tbody>{nodes.map(node=>{const value=terminal(node.node_id);return <tr key={node.node_id}><th scope="row">{human(node.node_id)}</th><td>{node.depends_on.map(human).join(", ")||"No earlier step"}{node.input_binding&&<div className="builds-input"><strong>Expected retained input</strong><p>{human(node.input_binding.upstream_node_id)}</p>{(()=>{const upstream=terminal(node.input_binding.upstream_node_id);return upstream?.output?.run_id&&upstream.output.invocation_id===node.invocation.input_result?.invocation_id?<button onClick={()=>setOutputId(upstream.output!.invocation_id)}>Inspect upstream result</button>:<p>No matching retained upstream result is visible.</p>;})()}<p>Open this step’s retained analysis to inspect whether it consumed that input.</p>{value?.output?.run_id&&<button onClick={()=>setOutputId(value.output!.invocation_id)}>Inspect downstream analysis</button>}</div>}</td><td>{value?human(value.state):"No terminal evidence"}{value?.new_run_required&&<p>Review the definition before a new run.</p>}{value?.usage&&<details><summary>Recorded step work</summary><BudgetTable usage={value.usage} label="Retained step usage"/></details>}</td></tr>;})}</tbody></table></div>
   <section aria-label="Named build outputs"><h4>Named outputs</h4>{run.request.compiled_plan.outputs.map(output=>{const value=terminal(output.node_id);return <p key={output.output_id}><strong>{human(output.output_id)}</strong> · {value?.output?.run_id?<button onClick={()=>setOutputId(value.output!.invocation_id)}>Open retained analysis</button>:"No retained result available"}</p>;})}<p>{run.publications.length} retained publication manifests. Node results can exist before complete output publication.</p></section>
   {run.binding_review&&<BuildBindingReview task={run.binding_review} runtimeState={state} disabled={busy} onOpen={setOutputId} onProposal={onProposal} onRead={()=>void action("read")}/>}
   {run.publication_review&&<BuildPublicationReview key={`${runId}:${run.publication_review.task_id}`} token={token} requestId={runId} task={run.publication_review} canReview={canReview} actorId={actorId} disabled={busy} onOpen={setOutputId} onRead={()=>void action("read")}/>}
   {canControl&&<section aria-label="Build controls"><label>Reason for control<textarea disabled={busy||Boolean(pendingControl)} minLength={10} maxLength={2000} value={reason} onChange={event=>setReason(event.target.value)}/></label>{pendingControl?<><button disabled={busy||!controllable} onClick={()=>control(pendingControl.command)}>Retry same {pendingControl.command} request</button><button disabled={busy} onClick={()=>{setPendingControl(null);setNotice("Local control retry dismissed. The retained server request and displayed historical readback are unchanged; this does not cancel a server action.");}}>Dismiss local control retry</button></>:<div className="builds-actions">{(["pause","resume","cancel"] as const).map(command=><button key={command} disabled={busy||!controllable||reason.trim().length<10||command==="pause"&&state==="PAUSED"||command==="resume"&&state!=="PAUSED"} onClick={()=>control(command)}>{human(command)} build</button>)}</div>}<p>Controls require observable live runtime state. They apply between bounded node activities.</p></section>}
   <details><summary>Retained execution references</summary><p>Completion dependencies control ordering. Only explicit input bindings declare result consumption; the downstream retained analysis records the exact consumed result.</p>{nodes.map(node=><p key={node.node_id}>Step ID: {node.node_id} · dependencies: {node.depends_on.join(", ")||"none"}{node.input_binding?` · input step: ${node.input_binding.upstream_node_id} · expected invocation: ${node.invocation.input_result?.invocation_id??"not recorded"}`:""}</p>)}{run.request.compiled_plan.outputs.map(output=><p key={output.output_id}>Output ID: {output.output_id} · step: {output.node_id}</p>)}<p>{run.workflow_id}</p><p>{run.definition.version}</p><p>{run.request.compiled_plan.request.valid_at} · {run.request.compiled_plan.request.known_at}</p>{run.events.map(event=><p key={event.event_id}>{new Date(event.created_at).toLocaleString()} · {event.node??event.command??"event"} · {event.state??"recorded"}{event.reason?` · ${event.reason}`:""}</p>)}</details>
  </>}
  {outputId&&<SavedAnalysisWorkbench onInspectAnalysis={onInspectAnalysis} companyId={companyId} onOpenFinance={onOpenFinance} onProposal={onProposal} key={outputId} token={token} companyName={companyName} initialInvocationId={outputId} onInspect={onInspect} onTrace={onTrace}/>}
  <footer>Retained execution preserves the output’s reviewed authority and coverage. It does not grant new current-use authorization or external business effects.</footer>
 </section>;
}

type BuildHistoryCursor={created_at:string;request_id:string};
type BuildHistoryItem={request_id:string;workflow_id:string;created_at:string;display_name:string;transformation:Pin;valid_at:string;known_at:string;completed_steps:number;total_steps:number;failed_steps:number;budget_refused_steps?:number;published_output_sets:number;current_use_authorized:false;business_effect_authorized:false};
function BuildHistory({token,revision,disabled,onOpen}:{token:string;revision:number;disabled:boolean;onOpen:(id:string)=>void}){
 const [open,setOpen]=useState(false);
 return <details className="builds-history" onToggle={event=>setOpen(event.currentTarget.open)}><summary>Retained build history</summary>{open&&<BuildHistoryRecords key={revision} token={token} disabled={disabled} onOpen={onOpen}/>}</details>;
}
function BuildHistoryRecords({token,disabled,onOpen}:{token:string;disabled:boolean;onOpen:(id:string)=>void}){
 const [items,setItems]=useState<BuildHistoryItem[]>([]);const [before,setBefore]=useState<BuildHistoryCursor|null>(null);const [next,setNext]=useState<BuildHistoryCursor|null>(null);const [revision,setRevision]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const cursor=before?JSON.stringify(before):null;
 useEffect(()=>{const controller=new AbortController();let disposed=false;const timer=setTimeout(()=>controller.abort(),20000);
  async function load(){setLoading(true);setError("");try{const params=new URLSearchParams({limit:"20"});if(cursor){const pin:BuildHistoryCursor=JSON.parse(cursor);params.set("before_created_at",pin.created_at);params.set("before_request_id",pin.request_id);}const response=await fetch(`/api/ontology/transformations/runs?${params}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store",signal:controller.signal});if(!response.ok)throw new Error("Retained build history is unavailable in your authorized scope.");const data:{purpose:string;items:BuildHistoryItem[];next_cursor:BuildHistoryCursor|null}=await response.json();
   if(data.purpose!=="HISTORICAL_BUILD_EVIDENCE"||!Array.isArray(data.items)||data.items.length>20||data.items.some(item=>!uuid.test(item.request_id)||item.workflow_id!==`transformation:${item.request_id}`||item.current_use_authorized!==false||item.business_effect_authorized!==false)||data.next_cursor&&(!uuid.test(data.next_cursor.request_id)||!Number.isFinite(Date.parse(data.next_cursor.created_at))||JSON.stringify(data.next_cursor)===cursor))throw new Error("Retained build history did not match its expected scope or page boundary.");
   if(!disposed){setItems(previous=>Array.from(new Map([...(cursor?previous:[]),...data.items].map(item=>[item.request_id,item])).values()));setNext(data.next_cursor);}
  }catch(failure){if(!disposed)setError(controller.signal.aborted?"History lookup timed out. Retry this page.":failure instanceof Error?failure.message:"History unavailable");}finally{clearTimeout(timer);if(!disposed)setLoading(false);}}
  void load();return()=>{disposed=true;clearTimeout(timer);controller.abort();};
 },[token,cursor,revision]);
 return <section aria-label="Retained evidence builds"><p>Counts describe retained step outcomes and publications. Open a build to check its current runtime state.</p>{loading&&<p role="status">Loading retained builds…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!items.length&&<p>No retained builds were found in your authorized scope.</p>}
  {items.map(item=><article key={item.request_id}><div><h4>{item.display_name}</h4><time dateTime={item.created_at}>{new Date(item.created_at).toLocaleString()}</time></div><p>{item.completed_steps} of {item.total_steps} steps have retained completion evidence · {item.failed_steps} failed outcomes{item.budget_refused_steps!==undefined?` · ${item.budget_refused_steps} work-limit refusals`:""} · {item.published_output_sets} published output sets</p><p>Effective {new Date(item.valid_at).toLocaleString()} · known {new Date(item.known_at).toLocaleString()}</p><button disabled={disabled} onClick={()=>onOpen(item.request_id)}>Open retained build</button><details><summary>Exact build reference</summary><p>{item.request_id}</p><p>{item.transformation.resource_id} · {item.transformation.version_id}</p></details></article>)}
  <p>{items.length} retained builds loaded. Historical evidence does not authorize current use or business effects.</p><div className="builds-actions"><button disabled={loading} onClick={()=>{setBefore(null);setRevision(value=>value+1);}}>Refresh build history</button>{error&&<button disabled={loading} onClick={()=>setRevision(value=>value+1)}>Retry history page</button>}{next&&!error&&<button disabled={loading} onClick={()=>setBefore(next)}>Load older builds</button>}</div>
 </section>;
}

function BudgetTable({budget,usage,estimate,label}:{budget?:ResourceBudget;usage?:WorkUsage;estimate?:{returned_rows:number;derived_evaluations:number};label:string}){
 const rows=[{name:"Returned rows",maximum:budget?.max_returned_rows,actual:usage?.returned_rows,planned:estimate?.returned_rows},{name:"Derived evaluations",maximum:budget?.max_derived_evaluations,actual:usage?.derived_evaluations,planned:estimate?.derived_evaluations},{name:"JSON result representation bytes",maximum:budget?.max_published_result_bytes,actual:usage?.published_result_bytes,planned:undefined}];
 return <div className="builds-table"><table aria-label={label}><thead><tr><th>Work measure</th>{budget&&<th>Reviewed limit</th>}{estimate&&<th>Planned</th>}{usage&&<th>Retained actual use</th>}</tr></thead><tbody>{rows.map(row=><tr key={row.name}><th scope="row">{row.name}</th>{budget&&<td>{row.maximum?.toLocaleString()??"Not recorded"}</td>}{estimate&&<td>{row.planned?.toLocaleString()??"Not estimated"}</td>}{usage&&<td>{row.actual?.toLocaleString()??"Not recorded"}</td>}</tr>)}</tbody></table>{usage&&<p>Measurement: PostgreSQL JSONB text encoded as UTF-8 ({usage.measurement}). Counts are retained observations, not live consumption.</p>}</div>;
}


type PublicationDecision={decision_id:string;decision:"APPROVED"|"REJECTED";reason:string};
function BuildPublicationReview({token,requestId,task,canReview,actorId,disabled,onOpen,onRead}:{token:string;requestId:string;task:PublicationReview;canReview:boolean;actorId:string;disabled:boolean;onOpen:(id:string)=>void;onRead:()=>void}){
 const [reason,setReason]=useState("");const [intent,setIntent]=useState<PublicationDecision|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const active=useRef<AbortController|null>(null);
 useEffect(()=>()=>{active.current?.abort();active.current=null;},[]);
 const independent=Boolean(actorId)&&actorId!==task.run_actor_id;
 const eligible=task.state==="PENDING"&&canReview&&independent;
 async function decide(decision:PublicationDecision["decision"]){
  if(busy||disabled||!eligible&&!intent)return;
  const frozen=intent??{decision_id:crypto.randomUUID(),decision,reason:reason.trim()};setIntent(frozen);setBusy(true);setError("");setNotice("");
  active.current?.abort();const controller=new AbortController();active.current=controller;const timer=setTimeout(()=>controller.abort(),20000);
  try{const response=await fetch(`/api/ontology/transformations/runs/${requestId}/publication-review`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(frozen),cache:"no-store",signal:controller.signal});
   if(!response.ok){const data=await response.json();throw new Error(typeof data.detail==="string"?data.detail:`Publication decision could not be confirmed (${response.status}).`);}
   const data:{publication_review:PublicationReview;runtime_notified:boolean}=await response.json();const recorded=data.publication_review?.decision;
   if(data.publication_review?.task_id!==task.task_id||recorded?.task_id!==task.task_id||recorded.decision_id!==frozen.decision_id||recorded.state!==frozen.decision||recorded.actor_id!==actorId||recorded.reason!==frozen.reason)throw new Error("Returned decision did not match the exact review request. Read retained state before retrying.");
   if(active.current===controller&&!controller.signal.aborted){setNotice(data.runtime_notified?"Independent decision retained and runtime notified. Publication remains a separate runtime step.":"Independent decision retained; runtime notification was not confirmed. The retained decision is unchanged.");setIntent(null);onRead();}
  }catch(failure){if(active.current===controller)setError(controller.signal.aborted?"Response timed out. Retry preserves the same decision identity and reason.":failure instanceof Error?failure.message:"Decision unavailable. Retry preserves its identity.");}
  finally{clearTimeout(timer);if(active.current===controller)setBusy(false);}
 }
 return <section className="build-publication-review" aria-label="Independent publication review"><h4>Independent publication review</h4><p>{task.question}</p><p>Retained task state: <strong>{human(task.state)}</strong>. This review concerns publication of the listed evidence outputs, not financial approval.</p>
 {task.outputs.map(output=><p key={output.output_id}><strong>{human(output.output_id)}</strong> · <button disabled={busy||disabled} onClick={()=>onOpen(output.invocation_id)}>Inspect retained output</button></p>)}
 {task.decision&&<div><p>Recorded decision: {human(task.decision.state)} · {task.decision.actor_id}</p><p>{task.decision.reason}</p></div>}
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {eligible&&!intent&&<><label>Review reason<textarea value={reason} minLength={10} maxLength={2000} disabled={busy||disabled} onChange={event=>setReason(event.target.value)}/></label><div className="builds-actions"><button disabled={busy||disabled||reason.trim().length<10} onClick={()=>void decide("APPROVED")}>Approve evidence publication</button><button disabled={busy||disabled||reason.trim().length<10} onClick={()=>void decide("REJECTED")}>Reject evidence publication</button></div></>}
 {intent&&<div className="builds-actions"><button disabled={busy||disabled} onClick={()=>void decide(intent.decision)}>Retry same {human(intent.decision)} decision</button><button disabled={busy||disabled} onClick={onRead}>Read retained review state</button><button disabled={busy||disabled} onClick={()=>{setIntent(null);setNotice("Local retry dismissed. This does not withdraw or alter a retained server decision.");}}>Dismiss local retry</button></div>}
 {task.state==="PENDING"&&!canReview&&<p>This identity does not have publication review permission.</p>}{task.state==="PENDING"&&canReview&&!independent&&<p>An independent reviewer must decide; the build requester cannot review this publication.</p>}
 <details><summary>Exact publication review references</summary><p>Task: {task.task_id} · Requester: {task.run_actor_id}</p>{task.decision&&<p>Decision: {task.decision.decision_id}</p>}{task.outputs.map(output=><p key={output.output_id}>Output: {output.output_id} · step: {output.node_id} · invocation: {output.invocation_id} · receipt: {output.receipt_hash} · result: {output.run_id}</p>)}</details>
 </section>;
}


function BuildBindingReview({task,runtimeState,disabled,onOpen,onProposal,onRead}:{task:BindingReview;runtimeState:string;disabled:boolean;onOpen:(id:string)=>void;onProposal?:Props["onProposal"];onRead:()=>void}) {
 const valid=["NOT_REQUESTED","PENDING","APPROVED","REJECTED","CANCELLED"].includes(task.state)&&
  task.proposal_history_independent===true&&uuid.test(task.binding?.resource_id??"")&&uuid.test(task.binding?.version_id??"")&&
  /^[a-f0-9]{64}$/.test(task.binding?.content_hash??"")&&uuid.test(task.operation_request_id)&&typeof task.source_node_id==="string"&&
  (task.operation_id===null||/^opa_[a-f0-9]{64}$/.test(task.operation_id))&&(task.proposal_id===null||uuid.test(task.proposal_id))&&
  (task.decision===null||["APPROVED","REJECTED"].includes(task.decision))&&
  (task.input_result===null||uuid.test(task.input_result?.invocation_id??"")&&/^[a-f0-9]{64}$/.test(task.input_result?.receipt_hash??"")&&/^fcr_[a-f0-9]{64}$/.test(task.input_result?.run_id??""));
 if(!valid)return <section aria-label="Binding review unavailable"><h4>Review mapped change</h4><p role="alert">The retained binding-review reference is incomplete or unsupported. Refresh the build before opening a result or proposal.</p><button disabled={disabled} onClick={onRead}>Refresh build</button></section>;
 const cancelled=task.state==="CANCELLED"||runtimeState==="CANCELLED";
 const explanation={NOT_REQUESTED:"No binding proposal has been requested in the retained build evidence yet.",PENDING:"A mapped change is awaiting the existing independent proposal review. Output publication waits for that decision.",APPROVED:"The shared proposal is approved. Refresh the build to read whether orchestration has continued; this decision alone does not establish build completion.",REJECTED:"The shared proposal was rejected. The build cannot continue its publication through this review gate.",CANCELLED:"The orchestration was cancelled at this stage."}[task.state];
 return <section className="builds-binding-review" aria-label="Build mapped-change review">
  <h4>Review mapped change</h4><p><strong>{human(task.state)}</strong> · Source step: {human(task.source_node_id)}</p>
  <p>{explanation}</p>
  {runtimeState==="UNOBSERVABLE"&&<p>Live build state is unavailable. The review evidence below does not imply that the worker is running.</p>}
  {cancelled&&<p>Cancellation stops orchestration. An already prepared canonical proposal and its independent review remain retained; cancelling the build does not withdraw or reverse that proposal.</p>}
  {task.decision&&<p>Retained shared proposal decision: {human(task.decision)}.</p>}
  <div className="builds-actions">
   {task.input_result?<button disabled={disabled} onClick={()=>onOpen(task.input_result!.invocation_id)}>Inspect retained source analysis</button>:<p>No retained source analysis reference is available at this stage.</p>}
   {task.proposal_id&&(onProposal?<button disabled={disabled} onClick={()=>onProposal(task.proposal_id!)}>Open binding review</button>:<p>Shared proposal review is unavailable in this view.</p>)}
   <button disabled={disabled} onClick={onRead}>Refresh build after review</button>
  </div>
  <p>This gate reviews a canonical mapped change. It does not certify financial statements or grant ERP posting authority.</p>
  <details><summary>Exact binding and review references</summary><dl>
   <dt>Reviewed binding / version</dt><dd>{task.binding.resource_id} / {task.binding.version_id}</dd><dt>Binding hash</dt><dd>{task.binding.content_hash}</dd>
   <dt>Source step</dt><dd>{task.source_node_id}</dd><dt>Operation request</dt><dd>{task.operation_request_id}</dd>
   <dt>Retained operation</dt><dd>{task.operation_id??"Not requested"}</dd><dt>Canonical proposal</dt><dd>{task.proposal_id??"Not available"}</dd>
   {task.input_result&&<><dt>Source invocation</dt><dd>{task.input_result.invocation_id}</dd><dt>Receipt hash</dt><dd>{task.input_result.receipt_hash}</dd><dt>Retained result</dt><dd>{task.input_result.run_id}</dd></>}
  </dl></details>
 </section>;
}


function BuildExecutionPolicy({policy}:{policy?:{max_concurrent_nodes:number}}) {
 const maximum=policy?.max_concurrent_nodes;
 if(policy!==undefined&&(typeof maximum!=="number"||!Number.isInteger(maximum)||maximum<1||maximum>4))return <p role="alert">The reviewed execution policy is unavailable or unsupported. No concurrency claim is shown; retained step outcomes remain below.</p>;
 return <details className="builds-execution-policy"><summary>{policy?`Reviewed execution limit: ${maximum} ready ${maximum===1?"step":"steps"} at once`:"Sequential execution: one ready step at a time"}</summary>
  <p>{policy?"The reviewed limit allows eligible steps to run in bounded batches.":"This retained definition has no explicit concurrency policy and uses sequential execution."} A step becomes eligible only after its required earlier steps complete. Steps that do not depend on each other may share a batch within the limit.</p>
  <p>All launched steps settle before another batch starts. A failed or cancelled batch prevents further batches and output publication; retained results may still be available for inspection.</p>
  <p>This setting does not prove that steps ran simultaneously. The step outcomes below report retained execution evidence. It is not a tenant-wide capacity or memory limit.</p>
 </details>;
}
