"use client";
import {useEffect,useRef,useState} from "react";
import type {CanonicalResource} from "@finai/contracts";
import SavedAnalysisWorkbench from "./saved-analysis-workbench";
import "./builds-workbench.css";
type Pin={resource_id:string;version_id:string};
type BuildRequest={request_id:string;transformation:Pin;valid_at:string;known_at:string};
type Definition={reference:Pin;display_name:string;attributes:Record<string,unknown>;content_hash:string};
type Node={node_id:string;depends_on:string[];invocation:{request_id:string;function:Pin}};
type ResourceBudget={max_returned_rows:number;max_derived_evaluations:number;max_published_result_bytes:number};
type WorkUsage={measurement:"POSTGRES_JSONB_TEXT_UTF8_V1";returned_rows:number;derived_evaluations:number;published_result_bytes:number};
type Terminal={node:string;state:string;output?:{invocation_id:string;run_id?:string;receipt_hash:string|null};new_run_required?:boolean;usage?:WorkUsage;cumulative_usage?:WorkUsage;resource_budget?:ResourceBudget};
type BuildRun={workflow_id:string;current_use_authorized:false;business_effect_authorized:false;request:{compiled_plan:{resource_budget?:ResourceBudget;estimated_work?:{returned_rows:number;derived_evaluations:number};result_bytes_accounting?:string;request:BuildRequest;nodes:Node[];outputs:Array<{output_id:string;node_id:string}>}};definition:{version:string;nodes:Node[]};events:Array<Terminal&{event_id:string;created_at:string;command?:string;reason?:string}>;publications:Array<{publication_id:string;generation:number}>;runtime_status:string;execution?:{state:string;result:Record<string,Terminal>;pause_requested:boolean;cancel_requested:boolean}};
type Control={command:"pause"|"resume"|"cancel";reason:string;idempotency_key:string};
type Props={token:string;companyName:string;canControl:boolean;onInspect:(resource:CanonicalResource,knownAt:string)=>void;onTrace:(resource:CanonicalResource,knownAt:string)=>void};
const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
const human=(value:string)=>value.toLowerCase().replaceAll("_"," ");
export default function BuildsWorkbench(props:Props){return <Builds key={props.token} {...props}/>;}
function Builds({token,companyName,canControl,onInspect,onTrace}:Props){
 const summaryHeading=useRef<HTMLHeadingElement|null>(null);
 const [historyRevision,setHistoryRevision]=useState(0);
 const [catalog,setCatalog]=useState<Definition[]>([]);const [after,setAfter]=useState<string|null>(null);const [next,setNext]=useState<string|null>(null);const [catalogRevision,setCatalogRevision]=useState(0);const [catalogBusy,setCatalogBusy]=useState(true);const [catalogError,setCatalogError]=useState("");
 const [selected,setSelected]=useState("");const [validAt,setValidAt]=useState(()=>new Date().toISOString());const [knownAt,setKnownAt]=useState(()=>new Date().toISOString());const [frozen,setFrozen]=useState<BuildRequest|null>(null);const [runId,setRunId]=useState("");const [run,setRun]=useState<BuildRun|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [reason,setReason]=useState("");const [pendingControl,setPendingControl]=useState<Control|null>(null);const [outputId,setOutputId]=useState("");const active=useRef<AbortController|null>(null);
 useEffect(()=>()=>{active.current?.abort();active.current=null;},[]);
 useEffect(()=>{if(run&&summaryHeading.current){summaryHeading.current.scrollIntoView({block:"start"});summaryHeading.current.focus({preventScroll:true});}},[run]);
 useEffect(()=>{const controller=new AbortController();let disposed=false;const timer=setTimeout(()=>controller.abort(),20000);async function load(){setCatalogBusy(true);setCatalogError("");try{const response=await fetch(`/api/ontology/transformations${after?`?after_resource_id=${after}`:""}`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal,cache:"no-store"});if(!response.ok)throw new Error("Reviewed builds are unavailable.");const data:{items:Definition[];next_cursor:string|null;purpose:string}=await response.json();if(data.purpose!=="EVIDENCE_ANALYSIS_ONLY"||!Array.isArray(data.items)||after&&data.next_cursor===after)throw new Error("Build catalog could not be verified.");if(!disposed){setCatalog(previous=>Array.from(new Map([...(after?previous:[]),...data.items].map(item=>[item.reference.version_id,item])).values()));setNext(data.next_cursor);}}catch(failure){if(!disposed)setCatalogError(controller.signal.aborted?"Build catalog timed out.":failure instanceof Error?failure.message:"Catalog unavailable");}finally{clearTimeout(timer);if(!disposed)setCatalogBusy(false);}}void load();return()=>{disposed=true;clearTimeout(timer);controller.abort();};},[token,after,catalogRevision]);
 async function api<T,>(path:string,signal:AbortSignal,body?:unknown):Promise<T>{const response=await fetch(`/api/ontology/transformations${path}`,{method:body?"POST":"GET",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},signal,cache:"no-store",...(body?{body:JSON.stringify(body)}:{})});if(!response.ok)throw new Error(`Build request could not be confirmed (${response.status}).`);return response.json();}
 async function read(id:string,signal:AbortSignal){const data=await api<BuildRun>(`/runs/${id}`,signal);if(data.workflow_id!==`transformation:${id}`||data.current_use_authorized!==false||data.business_effect_authorized!==false||!Array.isArray(data.events))throw new Error("Build evidence did not match this run.");return data;}
 async function action(kind:"start"|"read"|"control",request?:BuildRequest,command?:Control,readId?:string){
  if(busy)return;active.current?.abort();const controller=new AbortController();active.current=controller;const timer=setTimeout(()=>controller.abort(),20000);setBusy(true);setError("");setNotice("");const id=readId??request?.request_id??runId;
  if(kind!=="control"){setRun(null);setOutputId("");}
  try{
   if(kind==="start"){const response=await api<{request_id:string;workflow_id:string;state:string;business_effect_authorized:false}>("/runs",controller.signal,request);if(response.request_id!==id||response.workflow_id!==`transformation:${id}`||response.state!=="START_REQUEST_RECORDED"||response.business_effect_authorized!==false)throw new Error("Start receipt did not match the requested build.");if(active.current===controller&&!controller.signal.aborted)setHistoryRevision(value=>value+1);}
   if(kind==="control")await api(`/runs/${id}/control`,controller.signal,command);
   const data=await read(id,controller.signal);if(active.current===controller&&!controller.signal.aborted){setRun(data);setRunId(id);if(kind==="control"){setPendingControl(null);setReason("");setNotice("Control request sent; the displayed runtime readback reports what is currently observable.");}}
  }catch(failure){if(active.current===controller)setError(`${controller.signal.aborted?"Response timed out.":failure instanceof Error?failure.message:"Build unavailable"} The request may be retained; retry uses the same identity.`);}finally{clearTimeout(timer);if(active.current===controller)setBusy(false);}
 }
 function start(){const definition=catalog.find(item=>item.reference.version_id===selected);if(!definition)return;const aware=(value:string)=>/(Z|[+-]\d{2}:\d{2})$/i.test(value)&&Number.isFinite(Date.parse(value));if(!aware(validAt)||!aware(knownAt)){setError("Both times require an explicit timezone.");return;}const request={request_id:crypto.randomUUID(),transformation:definition.reference,valid_at:new Date(validAt).toISOString(),known_at:new Date(knownAt).toISOString()};setFrozen(request);setRunId(request.request_id);void action("start",request);}
 function control(command:Control["command"]){const intent=pendingControl??{command,reason:reason.trim(),idempotency_key:crypto.randomUUID()};setPendingControl(intent);void action("control",undefined,intent);}
 const observed=run&&run.runtime_status!=="UNOBSERVABLE";const state=observed?(run.execution?.state??run.runtime_status):"UNOBSERVABLE";const controllable=Boolean(canControl&&observed&&run?.runtime_status==="RUNNING"&&run.execution&&!["COMPLETED","FAILED","CANCELLED"].includes(run.execution.state));
 const nodes=run?.request.compiled_plan.nodes??[];
 const refused=run?.events.filter(event=>event.state==="BUDGET_REFUSED")??[];
 const terminal=(node:string)=>run?.execution?.result?.[node]??[...(run?.events??[])].reverse().find(event=>event.node===node&&["COMPLETED","FAILED","BUDGET_REFUSED"].includes(event.state));
 return <section className="builds-workbench" aria-label="Evidence builds"><header><p className="overline">REVIEWED EVIDENCE BUILDS</p><h3>Prepare evidence for analysis</h3><p>Each build uses reviewed source analyses in your authorized scope. Company navigation context ({companyName||"none selected"}) does not bind these outputs to company finances.</p></header>
  <div className="builds-controls"><label>Reviewed build<select disabled={busy||Boolean(frozen)||catalogBusy} value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Choose a reviewed build</option>{catalog.map(item=><option key={item.reference.version_id} value={item.reference.version_id}>{item.display_name}</option>)}</select></label><label>Effective at — timezone required<input disabled={busy||Boolean(frozen)} value={validAt} onChange={event=>setValidAt(event.target.value)}/></label><label>Known at — timezone required<input disabled={busy||Boolean(frozen)} value={knownAt} onChange={event=>setKnownAt(event.target.value)}/></label></div>
  {catalogBusy&&<p role="status">Loading reviewed builds…</p>}{catalogError&&<p role="alert">{catalogError}</p>}{!catalogBusy&&!catalogError&&!catalog.length&&<p>No reviewed builds were returned.</p>}{catalogError&&<button disabled={catalogBusy} onClick={()=>setCatalogRevision(value=>value+1)}>Retry build catalog</button>}{next&&<button disabled={catalogBusy||busy} onClick={()=>setAfter(next)}>Load more reviewed builds</button>}
  <div className="builds-actions">{!frozen?<button disabled={!canControl||busy||!selected||Boolean(pendingControl)} onClick={start}>Start evidence build</button>:<><button disabled={busy} onClick={()=>void action("start",frozen)}>Retry exact start request</button><button disabled={busy||Boolean(pendingControl)} onClick={()=>{setFrozen(null);setRun(null);setOutputId("");}}>Start a new build</button></>}</div>
  <BuildHistory token={token} revision={historyRevision} disabled={busy||Boolean(pendingControl)} onOpen={id=>{setFrozen(null);setRunId(id);void action("read",undefined,undefined,id);}}/>
  <details><summary>Reopen a retained build by reference</summary><label>Build request reference<input disabled={busy||Boolean(pendingControl)} value={runId} onChange={event=>{setRunId(event.target.value);setRun(null);setOutputId("");}}/></label><button disabled={busy||!uuid.test(runId)||Boolean(pendingControl)} onClick={()=>{setFrozen(null);void action("read");}}>Reopen build</button></details>
  {busy&&<p role="status">Waiting for build response…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {run&&<><h4 ref={summaryHeading} tabIndex={-1} className="builds-runtime-summary">Runtime: {human(state)}</h4>{!observed&&<p>Live runtime state is unavailable. Retained events and outputs remain historical evidence; this does not mean the build failed.</p>}{run.execution?.pause_requested&&<p>Pause requested; an active bounded node may still finish.</p>}{run.execution?.cancel_requested&&<p>Cancellation requested; confirm the next runtime readback.</p>}<button disabled={busy} onClick={()=>void action("read")}>Refresh build state</button><p>Steps start after their required earlier steps finish.</p>
   {refused.length>0&&<section className="builds-budget-refusal" aria-label="Retained work-limit refusal"><h4>Work limit refused</h4><p>A retained step exceeded its reviewed work limit. This refusal remains part of the evidence even when live runtime state is unavailable. It does not establish completion or publication.</p><p>Review the build definition and its limits before starting a new run. Any retained analysis below is diagnostic evidence, not a published build result.</p>{refused.map(event=><div key={event.event_id}><strong>{human(event.node)}</strong>{event.cumulative_usage&&<BudgetTable usage={event.cumulative_usage} budget={event.resource_budget} label="Cumulative use at refusal"/>}</div>)}</section>}
   {run.request.compiled_plan.resource_budget&&<details className="builds-budget"><summary>Reviewed work limits and planned work</summary><BudgetTable budget={run.request.compiled_plan.resource_budget} estimate={run.request.compiled_plan.estimated_work} label="Reviewed build budget"/><p>Result bytes count the UTF-8 PostgreSQL JSONB text representation. This is not source-file size, disk allocation or memory usage.</p><small>Measurement contract: {run.request.compiled_plan.result_bytes_accounting??"Not recorded"}</small></details>}
   <div className="builds-table"><table><thead><tr><th>Step</th><th>Completes after</th><th>Outcome</th></tr></thead><tbody>{nodes.map(node=>{const value=terminal(node.node_id);return <tr key={node.node_id}><th scope="row">{human(node.node_id)}</th><td>{node.depends_on.map(human).join(", ")||"No earlier step"}</td><td>{value?human(value.state):"No terminal evidence"}{value?.new_run_required&&<p>Review the definition before a new run.</p>}{value?.usage&&<details><summary>Recorded step work</summary><BudgetTable usage={value.usage} label="Retained step usage"/></details>}</td></tr>;})}</tbody></table></div>
   <section aria-label="Named build outputs"><h4>Named outputs</h4>{run.request.compiled_plan.outputs.map(output=>{const value=terminal(output.node_id);return <p key={output.output_id}><strong>{human(output.output_id)}</strong> · {value?.output?.run_id?<button onClick={()=>setOutputId(value.output!.invocation_id)}>Open retained analysis</button>:"No retained result available"}</p>;})}<p>{run.publications.length} retained publication manifests. Node results can exist before complete output publication.</p></section>
   {canControl&&<section aria-label="Build controls"><label>Reason for control<textarea disabled={busy||Boolean(pendingControl)} minLength={10} maxLength={2000} value={reason} onChange={event=>setReason(event.target.value)}/></label>{pendingControl?<><button disabled={busy||!controllable} onClick={()=>control(pendingControl.command)}>Retry same {pendingControl.command} request</button><button disabled={busy} onClick={()=>{setPendingControl(null);setNotice("Local control retry dismissed. The retained server request and displayed historical readback are unchanged; this does not cancel a server action.");}}>Dismiss local control retry</button></>:<div className="builds-actions">{(["pause","resume","cancel"] as const).map(command=><button key={command} disabled={busy||!controllable||reason.trim().length<10||command==="pause"&&state==="PAUSED"||command==="resume"&&state!=="PAUSED"} onClick={()=>control(command)}>{human(command)} build</button>)}</div>}<p>Controls require observable live runtime state. They apply between bounded node activities.</p></section>}
   <details><summary>Retained execution references</summary><p>Dependencies are completion barriers; no transfer of data between nodes is inferred.</p>{nodes.map(node=><p key={node.node_id}>Step ID: {node.node_id} · dependencies: {node.depends_on.join(", ")||"none"}</p>)}{run.request.compiled_plan.outputs.map(output=><p key={output.output_id}>Output ID: {output.output_id} · step: {output.node_id}</p>)}<p>{run.workflow_id}</p><p>{run.definition.version}</p><p>{run.request.compiled_plan.request.valid_at} · {run.request.compiled_plan.request.known_at}</p>{run.events.map(event=><p key={event.event_id}>{new Date(event.created_at).toLocaleString()} · {event.node??event.command??"event"} · {event.state??"recorded"}{event.reason?` · ${event.reason}`:""}</p>)}</details>
  </>}
  {outputId&&<SavedAnalysisWorkbench key={outputId} token={token} companyName={companyName} initialInvocationId={outputId} onInspect={onInspect} onTrace={onTrace}/>}
  <footer>Evidence build only. Retained execution does not grant financial authority, current-use authorization or external business effects.</footer>
 </section>;
}

type BuildHistoryCursor={created_at:string;request_id:string};
type BuildHistoryItem={request_id:string;workflow_id:string;created_at:string;display_name:string;transformation:Pin;valid_at:string;known_at:string;completed_steps:number;total_steps:number;failed_steps:number;budget_refused_steps?:number;published_output_sets:number;current_use_authorized:false;business_effect_authorized:false};
function BuildHistory({token,revision,disabled,onOpen}:{token:string;revision:number;disabled:boolean;onOpen:(id:string)=>void}){
 const [open,setOpen]=useState(false);
 return <details className="builds-history" onToggle={event=>setOpen(event.currentTarget.open)}><summary>Retained build history</summary>{open&&<BuildHistoryRecords key={revision} token={token} disabled={disabled} onOpen={onOpen}/>}</details>;
}
function BuildHistoryRecords({token,disabled,onOpen}:{token:string;disabled:boolean;onOpen:(id:string)=>void}){
 const [items,setItems]=useState<BuildHistoryItem[]>([]);const [before,setBefore]=useState<BuildHistoryCursor|null>(null);const [next,setNext]=useState<BuildHistoryCursor|null>(null);const [revision,setRevision]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const cursor=before?JSON.stringify(before):null;
 useEffect(()=>{const controller=new AbortController();let disposed=false;const timer=setTimeout(()=>controller.abort(),20000);
  async function load(){setLoading(true);setError("");try{const params=new URLSearchParams({limit:"20"});if(cursor){const pin:BuildHistoryCursor=JSON.parse(cursor);params.set("before_created_at",pin.created_at);params.set("before_request_id",pin.request_id);}const response=await fetch(`/api/ontology/transformations/runs?${params}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store",signal:controller.signal});if(!response.ok)throw new Error("Retained build history is unavailable in your authorized scope.");const data:{purpose:string;items:BuildHistoryItem[];next_cursor:BuildHistoryCursor|null}=await response.json();
   if(data.purpose!=="HISTORICAL_BUILD_EVIDENCE"||!Array.isArray(data.items)||data.items.length>20||data.items.some(item=>!uuid.test(item.request_id)||item.workflow_id!==`transformation:${item.request_id}`||item.current_use_authorized!==false||item.business_effect_authorized!==false)||data.next_cursor&&(!uuid.test(data.next_cursor.request_id)||!Number.isFinite(Date.parse(data.next_cursor.created_at))||JSON.stringify(data.next_cursor)===cursor))throw new Error("Retained build history did not match its expected scope or page boundary.");
   if(!disposed){setItems(previous=>Array.from(new Map([...(cursor?previous:[]),...data.items].map(item=>[item.request_id,item])).values()));setNext(data.next_cursor);}
  }catch(failure){if(!disposed)setError(controller.signal.aborted?"History lookup timed out. Retry this page.":failure instanceof Error?failure.message:"History unavailable");}finally{clearTimeout(timer);if(!disposed)setLoading(false);}}
  void load();return()=>{disposed=true;clearTimeout(timer);controller.abort();};
 },[token,cursor,revision]);
 return <section aria-label="Retained evidence builds"><p>Counts describe retained step outcomes and publications. Open a build to check its current runtime state.</p>{loading&&<p role="status">Loading retained builds…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!error&&!items.length&&<p>No retained builds were found in your authorized scope.</p>}
  {items.map(item=><article key={item.request_id}><div><h4>{item.display_name}</h4><time dateTime={item.created_at}>{new Date(item.created_at).toLocaleString()}</time></div><p>{item.completed_steps} of {item.total_steps} steps have retained completion evidence · {item.failed_steps} failed outcomes{item.budget_refused_steps!==undefined?` · ${item.budget_refused_steps} work-limit refusals`:""} · {item.published_output_sets} published output sets</p><p>Effective {new Date(item.valid_at).toLocaleString()} · known {new Date(item.known_at).toLocaleString()}</p><button disabled={disabled} onClick={()=>onOpen(item.request_id)}>Open retained build</button><details><summary>Exact build reference</summary><p>{item.request_id}</p><p>{item.transformation.resource_id} · {item.transformation.version_id}</p></details></article>)}
  <p>{items.length} retained builds loaded. Historical evidence does not authorize current use or business effects.</p><div className="builds-actions"><button disabled={loading} onClick={()=>{setBefore(null);setRevision(value=>value+1);}}>Refresh build history</button>{error&&<button disabled={loading} onClick={()=>setRevision(value=>value+1)}>Retry history page</button>}{next&&!error&&<button disabled={loading} onClick={()=>setBefore(next)}>Load older builds</button>}</div>
 </section>;
}

function BudgetTable({budget,usage,estimate,label}:{budget?:ResourceBudget;usage?:WorkUsage;estimate?:{returned_rows:number;derived_evaluations:number};label:string}){
 const rows=[{name:"Returned rows",maximum:budget?.max_returned_rows,actual:usage?.returned_rows,planned:estimate?.returned_rows},{name:"Derived evaluations",maximum:budget?.max_derived_evaluations,actual:usage?.derived_evaluations,planned:estimate?.derived_evaluations},{name:"JSON result representation bytes",maximum:budget?.max_published_result_bytes,actual:usage?.published_result_bytes,planned:undefined}];
 return <div className="builds-table"><table aria-label={label}><thead><tr><th>Work measure</th>{budget&&<th>Reviewed limit</th>}{estimate&&<th>Planned</th>}{usage&&<th>Retained actual use</th>}</tr></thead><tbody>{rows.map(row=><tr key={row.name}><th scope="row">{row.name}</th>{budget&&<td>{row.maximum?.toLocaleString()??"Not recorded"}</td>}{estimate&&<td>{row.planned?.toLocaleString()??"Not estimated"}</td>}{usage&&<td>{row.actual?.toLocaleString()??"Not recorded"}</td>}</tr>)}</tbody></table>{usage&&<p>Measurement: PostgreSQL JSONB text encoded as UTF-8 ({usage.measurement}). Counts are retained observations, not live consumption.</p>}</div>;
}
