import type {CanonicalResource,CompanyConditionWorkItem} from "@finai/contracts";
import type {CompanyConditionDescriptorV2} from "../../../packages/contracts/src/company-condition";
import {restorationInstant} from "./definition-restoration-time";

export type OperatingSnapshot={companyId:string;validAt:string;knownAt:string};
const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
const hash=/^[a-f0-9]{64}$/;
const resource=(value:CanonicalResource)=>Boolean(value&&uuid.test(value.resource_id)&&uuid.test(value.version_id)&&hash.test(value.content_hash)&&typeof value.display_name==="string"&&typeof value.object_type==="string"&&value.authority_state==="APPROVED"&&value.evidence_class!=="REFERENCE_TEMPLATE");
export function operatingResourceKey(value:CanonicalResource):string{return `${value.resource_id}:${value.version_id}`;}
const priority={PENDING_REVIEW:0,PREPARED:1,REJECTED:2,PUBLISHED:3};
export function rankCompanyWork(items:CompanyConditionWorkItem[],filter:"ALL"|CompanyConditionWorkItem["state"]="ALL",query=""):CompanyConditionWorkItem[]{
 const search=query.trim().toLocaleLowerCase();
 return items.filter(item=>(filter==="ALL"||item.state===filter)&&(!search||`${item.title} ${item.reason}`.toLocaleLowerCase().includes(search))).sort((a,b)=>priority[a.state]-priority[b.state]||Date.parse(b.created_at)-Date.parse(a.created_at)||(a.workflow_id<b.workflow_id?-1:a.workflow_id>b.workflow_id?1:0));
}
/** Verify response scope and retained references before rendering company work. */
export function assertCompanyCondition(value:CompanyConditionDescriptorV2,expected:OperatingSnapshot):void {
 if(!value||value.contract!=="g8-company-condition/2"||!resource(value.company)||value.company.resource_id!==expected.companyId||value.company.object_type!=="LegalEntity"||value.current_use_authorized!==false||value.business_effect_authorized!==false||value.connection_depth!==2||!restorationInstant(expected.validAt)||!restorationInstant(expected.knownAt)||restorationInstant(value.valid_at)!==restorationInstant(expected.validAt)||restorationInstant(value.known_at)!==restorationInstant(expected.knownAt))throw Error("Operating context did not match this company and exact snapshot.");
 if(!Array.isArray(value.connections)||value.connections.length>5000||value.connections.some(item=>![item.record,item.relation,item.source,item.target].every(resource)||item.record.object_type!=="Relationship"||item.relation.object_type!=="LinkType"||item.record.attributes?.source_id!==item.source.resource_id||item.record.attributes?.target_id!==item.target.resource_id||item.record.attributes?.relation_id!==item.relation.resource_id))throw Error("Company connections lack verified retained references.");
 const root=operatingResourceKey(value.company),same=(a:CanonicalResource,b:CanonicalResource)=>operatingResourceKey(a)===operatingResourceKey(b)&&a.content_hash===b.content_hash;
 const units=value.connections.filter(item=>same(item.source,value.company)&&["BusinessUnit","LicensedOperator","ServiceCompany"].includes(item.target.object_type)).map(item=>item.target);
 if(value.connections.some(item=>!(operatingResourceKey(item.source)===root&&same(item.source,value.company))&&!units.some(unit=>same(item.source,unit))))throw Error("Company connections exceed the selected company's bounded scope.");
 const targets=new Map(value.connections.map(item=>[operatingResourceKey(item.target),item.target.content_hash]));
 if(!Array.isArray(value.resource_groups)||value.resource_groups.length>5000||!["AVAILABLE","UNAVAILABLE"].includes(value.resource_groups_state)||value.resource_groups_state==="AVAILABLE"&&value.resource_groups_reason!==null||value.resource_groups_state==="UNAVAILABLE"&&(typeof value.resource_groups_reason!=="string"||!value.resource_groups_reason.trim())||new Set(value.resource_groups.map(group=>group.key)).size!==value.resource_groups.length)throw Error("Company resource groups are unavailable or have duplicate identities.");
 for(const group of value.resource_groups){
  if(!group||!resource(group.definition)||group.key!==group.definition.resource_id||typeof group.label!=="string"||!group.label.trim()||!["AVAILABLE","EMPTY","UNAVAILABLE"].includes(group.state)||group.count_basis!=="EXPLICIT_CONNECTED_RESOURCE_SNAPSHOT"||typeof group.reason!=="string"||!group.reason.trim()||restorationInstant(group.valid_at)!==restorationInstant(expected.validAt)||restorationInstant(group.known_at)!==restorationInstant(expected.knownAt))throw Error("Resource group definition or snapshot could not be verified.");
  // Producer allows up to 100 implementations, each with an implementation/schema pin, plus self.
  if(!Array.isArray(group.definition_pins)||group.definition_pins.length>201||!group.definition_pins.some(pin=>pin&&pin.resource_id===group.definition.resource_id&&pin.version_id===group.definition.version_id&&pin.content_hash===group.definition.content_hash)||group.definition_pins.some(pin=>!pin||!uuid.test(pin.resource_id)||!uuid.test(pin.version_id)||!hash.test(pin.content_hash))||new Set(group.definition_pins.map(pin=>pin.resource_id)).size!==group.definition_pins.length)throw Error("Resource group definition pins are invalid.");
  if(!Array.isArray(group.resources)||group.resources.length>5000||group.resources.some(item=>!resource(item)||targets.get(operatingResourceKey(item))!==item.content_hash)||new Set(group.resources.map(operatingResourceKey)).size!==group.resources.length)throw Error("Resource group members lack exact company connections.");
  if(group.state==="UNAVAILABLE"?group.count!==null||group.completeness!=="UNAVAILABLE"||group.resources.length!==0:group.completeness!=="COMPLETE_WITHIN_CONNECTION_SNAPSHOT"||!Number.isInteger(group.count)||group.count!==group.resources.length||(group.state==="EMPTY")!==(group.resources.length===0))throw Error("Resource group count does not match its bounded completeness state.");
 }
 if(!Array.isArray(value.licence_evidence)||value.licence_evidence.some(item=>!resource(item.binding)||item.binding.object_type!=="LicenceNoticeBinding"||item.binding.attributes?.company_id!==expected.companyId||item.notice!==null&&(!resource(item.notice)||item.binding.attributes?.notice_id!==item.notice.resource_id)||item.licence!==null&&(!resource(item.licence)||item.binding.attributes?.licence_id!==item.licence.resource_id)))throw Error("Licence evidence lacks exact retained references.");
 const work=value.work;
 if(!work||!["AVAILABLE","UNAVAILABLE"].includes(work.state)||work.state==="AVAILABLE"&&work.reason!==null||work.state==="UNAVAILABLE"&&(typeof work.reason!=="string"||!work.reason.trim()||work.items?.length!==0)||work.authority!=="CURRENT_RETAINED_WORK"||!restorationInstant(work.observed_at)||work.limit!==25||typeof work.truncated!=="boolean"||!Array.isArray(work.items)||work.items.length>work.limit||work.items.some(item=>item.company_id!==expected.companyId||item.basis!=="EXPLICIT_INVOCATION"||typeof item.workflow_id!=="string"||!item.workflow_id||item.workflow_id.length>250||item.proposal_id!==null&&!uuid.test(item.proposal_id)||!["PREPARED","PENDING_REVIEW","PUBLISHED","REJECTED"].includes(item.state)||typeof item.title!=="string"||typeof item.reason!=="string"||!restorationInstant(item.created_at))||new Set(work.items.map(item=>item.workflow_id)).size!==work.items.length)throw Error("Company work did not preserve explicit company scope and current observation time.");
 if(!Array.isArray(value.unavailable)||value.unavailable.some(item=>!["financial_performance","live_operations","findings","investigations","regulatory_compliance"].includes(item.key)||typeof item.label!=="string"||typeof item.reason!=="string"))throw Error("Company capability availability could not be verified.");
}
