"use client";
import {companyWorkflowReference,journalReviewReference,type CompanyWorkflowReference,type JournalReviewReference} from "./journal-review-handoff";
import {useEffect,useState} from "react";
import type {CanonicalResource,CompanyConditionWorkItem} from "@finai/contracts";
import type {CompanyConditionDescriptorV2} from "../../../packages/contracts/src/company-condition";
import {assertCompanyCondition,operatingResourceKey,rankCompanyWork} from "./company-operating-state";
import {parseOperatingView,operatingViewPage,operatingViewSelection,matchesOperatingGroup,type OperatingView} from "./company-operating-view";
import {partitionCompanyWork} from "./company-work-attention";
import {displayName} from "./display-name";
import CompanyRegulation from "./company-regulation";
import CompanyJournalAnalysisEntry from "./company-journal-analysis-entry";
import CompanyJournalReviewWork from "./company-journal-review-work";
import "./company-operating-workspace.css";

type ResourceAction=(resource:CanonicalResource,knownAt:string)=>void;
export type CompanyOperatingProps={token:string;viewStateKey?:string;companyId:string;snapshot:{validAt:string;knownAt:string};compact?:boolean;onInspect:ResourceAction;onTrace?:ResourceAction;onHistory?:ResourceAction;onProposal?:(id:string)=>void;onJournalReview?:(reference:JournalReviewReference)=>void;onCompanyWorkflow?:(reference:CompanyWorkflowReference)=>void;onWorkflow?:(id:string)=>void};
const human=(value:string)=>value.replace(/([a-z])([A-Z])/g,"$1 $2").replaceAll("_"," ").toLowerCase();
const stamp=(value:string)=>new Date(value).toLocaleString();

export default function CompanyOperatingWorkspace(props:CompanyOperatingProps){return <OperatingWorkspace key={`${props.token}:${props.companyId}:${props.snapshot.validAt}:${props.snapshot.knownAt}`} {...props}/>;}
function OperatingWorkspace({token,viewStateKey,companyId,snapshot,compact=false,onInspect,onTrace,onHistory,onProposal,onJournalReview,onCompanyWorkflow,onWorkflow}:CompanyOperatingProps){
 const {validAt,knownAt}=snapshot;
 const storageKey=!compact&&viewStateKey?`${viewStateKey}:operating-v1:${companyId}`:null;
 const [restored]=useState(()=>{if(!storageKey)return null;try{return parseOperatingView(sessionStorage.getItem(storageKey)??"",{companyId,validAt,knownAt});}catch{return null;}});
 const [result,setResult]=useState<CompanyConditionDescriptorV2|null>(null),[error,setError]=useState("");const [revision,setRevision]=useState(0);const [settledRevision,setSettledRevision]=useState<number|null>(null);
 const [openedWorkflow,setOpenedWorkflow]=useState("");
 const [workFilter,setWorkFilter]=useState<"ALL"|CompanyConditionWorkItem["state"]>(restored?.workFilter??"ALL"),[workSearch,setWorkSearch]=useState(restored?.workSearch??"");
 const [group,setGroup]=useState<OperatingView["group"]>(restored?.group??null),[search,setSearch]=useState(restored?.search??"");
 const [groupUnavailable,setGroupUnavailable]=useState(restored?.groupUnavailable??false);
 const [page,setPage]=useState(restored?.page??0),[workPage,setWorkPage]=useState(restored?.workPage??0),[licencePage,setLicencePage]=useState(restored?.licencePage??0),[selected,setSelected]=useState(restored?.selected?`${restored.selected.resourceId}:${restored.selected.versionId}:${restored.selected.contentHash}`:"");
 useEffect(()=>{const controller=new AbortController();let disposed=false;const timer=setTimeout(()=>controller.abort(),25000);
  const params=new URLSearchParams({company_id:companyId,valid_at:validAt,known_at:knownAt,contract_version:"2"});
  void fetch(`/api/ontology/company-condition?${params}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store",signal:controller.signal}).then(async response=>{
   const data=await response.json();if(!response.ok)throw Error(typeof data.detail==="string"?data.detail:"Company operating context is unavailable.");
   assertCompanyCondition(data,{companyId,validAt,knownAt});if(!disposed){setResult(data);setError("");setSettledRevision(revision);}
  }).catch(failure=>{if(!disposed){setSettledRevision(revision);setError(controller.signal.aborted?"Company operating context timed out. Retry this snapshot.":failure instanceof Error?failure.message:"Company operating context is unavailable.");}}).finally(()=>clearTimeout(timer));
  return()=>{disposed=true;clearTimeout(timer);controller.abort();};
 },[token,companyId,validAt,knownAt,revision]);
 useEffect(()=>{const refresh=(event:Event)=>{const value=(event as CustomEvent).detail;if(value?.companyId===companyId&&value.validAt===validAt&&value.knownAt===knownAt)setRevision(current=>current+1);};window.addEventListener("g8:refresh-journal-review-origin",refresh);return()=>window.removeEventListener("g8:refresh-journal-review-origin",refresh);},[companyId,validAt,knownAt]);
 useEffect(()=>{if(settledRevision===revision)window.dispatchEvent(new CustomEvent("g8:journal-review-origin-settled",{detail:{companyId,validAt,knownAt}}));},[settledRevision,revision,companyId,validAt,knownAt]);
 const pageSize=compact?5:10,query=search.trim().toLocaleLowerCase();
 const activeGroup=result?.resource_groups.find(item=>matchesOperatingGroup(group,item))??null;
 const resources=activeGroup?.resources.filter(item=>`${item.display_name} ${item.object_type}`.toLocaleLowerCase().includes(query))??[];
 const orderedWork=rankCompanyWork(result?.work.items??[],workFilter,workSearch),workGroups=partitionCompanyWork(orderedWork),primaryWork=compact?workGroups.attention:orderedWork;
 const resourcePage=operatingViewPage(page,resources.length,pageSize),currentWorkPage=operatingViewPage(workPage,primaryWork.length,pageSize),currentLicencePage=operatingViewPage(licencePage,result?.licence_evidence.length??0,pageSize);
 const [resourceId,versionId,contentHash]=selected.split(":");
 const selectedResource=result?operatingViewSelection(selected?{resourceId,versionId,contentHash}:null,activeGroup?.resources??[],result.connections):null;
 useEffect(()=>{if(!storageKey||!result)return;const safe=parseOperatingView(JSON.stringify({version:2,companyId,validAt,knownAt,group,groupUnavailable,search,workSearch,workFilter,page:activeGroup?resourcePage:page,workPage:currentWorkPage,licencePage:currentLicencePage,selected:selectedResource?{resourceId:selectedResource.resource_id,versionId:selectedResource.version_id,contentHash:selectedResource.content_hash}:selected?{resourceId,versionId,contentHash}:null}),{companyId,validAt,knownAt});if(safe)try{sessionStorage.setItem(storageKey,JSON.stringify(safe));}catch{/* Optional view preferences never block company work. */}},[storageKey,result,companyId,validAt,knownAt,group,search,workSearch,workFilter,page,resourcePage,currentWorkPage,currentLicencePage,selectedResource,activeGroup,groupUnavailable,selected,resourceId,versionId,contentHash]);
 function retry(){setResult(null);setError("");setRevision(value=>value+1);}
 function inspect(resource:CanonicalResource){if(activeGroup?.resources.some(item=>operatingResourceKey(item)===operatingResourceKey(resource)))setSelected(`${operatingResourceKey(resource)}:${resource.content_hash}`);onInspect(resource,knownAt);}
 function actions(resource:CanonicalResource){return <span className="company-operating-row-actions"><button onClick={()=>inspect(resource)}>Inspect</button>{onTrace&&<button onClick={()=>onTrace(resource,knownAt)}>Trace</button>}{onHistory&&<button onClick={()=>onHistory(resource,knownAt)}>History</button>}</span>;}
 if(error&&!result)return <section className="company-operating-error" role="alert"><h3>Company operating context unavailable</h3><p>{error}</p><button onClick={retry}>Retry exact snapshot</button></section>;
 if(!result)return <p className="company-operating-loading" role="status">Resolving linked company resources, retained work and regulatory evidence…</p>;
 const work=primaryWork.slice(currentWorkPage*pageSize,(currentWorkPage+1)*pageSize);
 const verifiedResult=result;
 function workTable(rows:CompanyConditionWorkItem[]){return <div className="company-operating-table"><table><thead><tr><th>Company work</th><th>Retained state</th><th>Why it matters</th><th>Open</th></tr></thead><tbody>{rows.map(item=><tr key={item.workflow_id}><th scope="row">{displayName(item.title)}<small>Created {stamp(item.created_at)}</small></th><td><span className="company-operating-status" data-state={item.state}>{human(item.state)}</span></td><td>{item.reason}</td><td><span className="company-operating-row-actions">{item.state!=="PREPARED"&&item.proposal_id&&onProposal&&!onCompanyWorkflow&&<button onClick={()=>onProposal(item.proposal_id!)}>Open review</button>}{(onCompanyWorkflow||onWorkflow)&&<button data-company-workflow={item.workflow_id} onClick={()=>{try{if(onCompanyWorkflow)onCompanyWorkflow(companyWorkflowReference(verifiedResult.company,validAt,knownAt,verifiedResult.work.observed_at,item));else onWorkflow?.(item.workflow_id);setOpenedWorkflow(item.workflow_id);}catch(failure){setError(failure instanceof Error?failure.message:"The exact company workflow reference is unavailable.");}}}>Open workflow</button>}{!onCompanyWorkflow&&!onWorkflow&&!(item.state!=="PREPARED"&&item.proposal_id&&onProposal)&&<span>Navigation unavailable</span>}</span></td></tr>)}</tbody></table></div>;}
 const selectedConnections=result.connections.filter(item=>[item.source,item.target].some(node=>`${operatingResourceKey(node)}:${node.content_hash}`===selected));
 return <section className={`company-operating-workspace${compact?" company-operating-compact":""}`} aria-label="Company operating workbench">
  <header><div><p className="overline">COMPANY WORK & OPERATING CONTEXT</p><h2>{compact?"Needs attention":"Decisions, obligations & connected resources"}</h2></div><button onClick={retry}>Refresh retained context</button></header>
  {selected&&!selectedResource&&<p className="company-operating-limitation" role="status">The saved resource selection is unavailable in this exact company group and snapshot. <button onClick={()=>setSelected("")}>Clear unavailable selection</button></p>}
  {!compact&&<CompanyJournalAnalysisEntry token={token} companyId={companyId} value={result.journal_reviews} pending={settledRevision!==revision||Boolean(error)}/>}
  <CompanyJournalReviewWork companyId={companyId} value={result.journal_reviews} compact={compact} onProposal={onProposal} pending={settledRevision!==revision} error={error} onReview={onJournalReview?item=>onJournalReview(journalReviewReference(result.company,validAt,knownAt,item)):undefined}/>

  <section data-company-work-queue tabIndex={-1} className="company-operating-work" aria-label="Current company work">{(settledRevision!==revision||error)&&<p role="status" className="company-operating-limitation">{error?"Current company work could not be refreshed. Earlier review decisions and controls are withheld.":"Refreshing current company work. Earlier review controls are withheld."}</p>}<div hidden={settledRevision!==revision||Boolean(error)} inert={settledRevision!==revision||Boolean(error)}><header><h3>{compact?"Other company work awaiting action":"Work requiring review and recent outcomes"}</h3><span>Observed {stamp(result.work.observed_at)}</span></header><p className="company-operating-note">Current retained work explicitly linked to this company. This queue is separate from the historical company snapshot.</p>
   <div className="company-operating-signals">{result.unavailable.filter(item=>item.key==="findings"||item.key==="investigations").map(item=><p key={item.key}><strong>{item.label} unavailable.</strong> {item.reason}</p>)}</div>
   {openedWorkflow&&!(compact?orderedWork:work).some(item=>item.workflow_id===openedWorkflow)&&<p role="status">The previously opened workflow is not visible in this returned page. Filters and queue position are retained. <button onClick={()=>{setWorkFilter("ALL");setWorkSearch("");setWorkPage(0);}}>Show all returned work</button></p>}
   {result.work.state==="AVAILABLE"&&<div className="company-operating-toolbar"><label>Priority within returned queue<select value={workFilter} onChange={event=>{setWorkFilter(event.target.value as "ALL"|CompanyConditionWorkItem["state"]);setWorkPage(0);}}><option value="ALL">All returned work</option>{(["PENDING_REVIEW","PREPARED","REJECTED","PUBLISHED"] as const).map(state=><option key={state} value={state}>{human(state)}</option>)}</select></label><label>Find work<input maxLength={200} value={workSearch} onChange={event=>{setWorkSearch(event.target.value.slice(0,200));setWorkPage(0);}} placeholder="Title or reason"/></label><span className="company-operating-note">Review priority; no financial materiality ranking</span></div>}
   {result.work.state==="UNAVAILABLE"?<p className="company-operating-limitation" role="status"><strong>Current company work is unavailable.</strong> {result.work.reason} Resource and licence context remain available below.</p>:work.length?workTable(work):<p className="company-operating-empty">{compact?(workFilter!=="ALL"||workSearch.trim()?"No prepared or awaiting-review work matches these filters in the returned collection.":"No prepared or awaiting-review work was returned. This does not establish that the company has no outstanding obligations."):result.work.items.length?"No returned work matches these filters.":"No explicitly linked retained work was returned. This does not establish that the company has no outstanding obligations."}</p>}
   {primaryWork.length>pageSize&&<div className="company-operating-pager"><button disabled={currentWorkPage===0} onClick={()=>setWorkPage(currentWorkPage-1)}>Previous work</button><span>{currentWorkPage*pageSize+1}–{Math.min((currentWorkPage+1)*pageSize,primaryWork.length)} of {primaryWork.length} matching returned</span><button disabled={(currentWorkPage+1)*pageSize>=primaryWork.length} onClick={()=>setWorkPage(currentWorkPage+1)}>Next work</button></div>}{!compact&&result.work.truncated&&<p className="company-operating-limitation">The server returned a bounded queue of {result.work.limit} items. Other company work may exist.</p>}
   {compact&&result.work.state==="AVAILABLE"&&<details data-company-work-outcomes className="company-work-outcomes"><summary>Recent company outcomes <span>{workGroups.outcomes.length} matching returned</span></summary><p className="company-operating-note">Published and rejected work is retained outcome history. It does not establish current financial, operating or licence authority.</p>{workGroups.outcomes.length?workTable(workGroups.outcomes):<p className="company-operating-empty">No published or rejected work matches this returned collection and its filters.</p>}</details>}
  </div>{compact&&result.work.truncated&&<p className="company-operating-limitation">The returned company work queue is bounded to {result.work.limit} items. Other work may exist; refreshing does not establish a complete queue.</p>}</section>
  {compact&&<CompanyJournalAnalysisEntry token={token} companyId={companyId} value={result.journal_reviews} pending={settledRevision!==revision||Boolean(error)}/>}
  <details className="company-operating-resource-depth" open={!compact}><summary hidden={!compact}>Connected resources & licence evidence</summary><section className="company-operating-inventory" aria-label="Connected company resources"><div className="company-operating-toolbar"><div className="company-operating-groups" aria-label="Resource group">{result.resource_groups.map(item=><button key={item.key} aria-pressed={activeGroup?.key===item.key} onClick={()=>{setGroup({key:item.key,versionId:item.definition.version_id,contentHash:item.definition.content_hash,definitionPins:item.definition_pins});setGroupUnavailable(false);setPage(0);setSelected("");}}>{item.label}<span>{item.count===null?"Unavailable":`${item.count} connected`}</span></button>)}</div><label>Find linked resource<input maxLength={200} value={search} onChange={event=>{setSearch(event.target.value.slice(0,200));setPage(0);}} placeholder="Name or type"/></label></div><p className="company-operating-note">{activeGroup?.reason} Groups may overlap; counts must not be added. Explicit company connections are bounded to {result.connection_depth} steps; presence does not establish ownership, balances or live operating condition.</p>
   {(groupUnavailable||group&&!activeGroup)&&<p role="status" className="company-operating-limitation">The saved group has no matching canonical definition at this snapshot. Choose a returned group explicitly; no replacement has been selected.</p>}
   {result.resource_groups_state==="UNAVAILABLE"&&<p role="status" className="company-operating-limitation">{result.resource_groups_reason}</p>}
   {activeGroup&&<p className="company-operating-note">{activeGroup.completeness==="UNAVAILABLE"?"Group membership unavailable":`${activeGroup.count} members · complete within this connection snapshot only`} · Effective {stamp(activeGroup.valid_at)} · known {stamp(activeGroup.known_at)}</p>}
   {activeGroup&&<details><summary>Advanced · exact group definition & snapshot</summary><p>Effective {stamp(activeGroup.valid_at)} · known {stamp(activeGroup.known_at)}. {activeGroup.completeness==="UNAVAILABLE"?"Membership unavailable":"Complete only within the returned connection snapshot"}.</p>{actions(activeGroup.definition)}<pre>{JSON.stringify({key:activeGroup.key,definition:activeGroup.definition,definition_pins:activeGroup.definition_pins,count_basis:activeGroup.count_basis,completeness:activeGroup.completeness},null,2)}</pre></details>}
   {resources.length?<div className="company-operating-table"><table><thead><tr><th>Business resource</th><th>Recorded kind</th><th>Context & evidence</th></tr></thead><tbody>{resources.slice(resourcePage*pageSize,(resourcePage+1)*pageSize).map(resource=><tr key={operatingResourceKey(resource)} aria-selected={selected===`${operatingResourceKey(resource)}:${resource.content_hash}`}><th scope="row"><button className="company-operating-name" onClick={()=>inspect(resource)}>{displayName(resource.display_name)}</button></th><td>{human(resource.object_type)}</td><td>{actions(resource)}</td></tr>)}</tbody></table></div>:<p className="company-operating-empty">{!activeGroup?"Choose an available canonical group to review its members.":activeGroup.state==="UNAVAILABLE"?"Membership is unavailable; this is not an empty group.":query?"No returned resources match this search.":"No resources in this group were returned through accepted company connections."}</p>}
   {resources.length>pageSize&&<div className="company-operating-pager"><button disabled={resourcePage===0} onClick={()=>setPage(resourcePage-1)}>Previous resources</button><span>{resourcePage*pageSize+1}–{Math.min((resourcePage+1)*pageSize,resources.length)} of {resources.length} returned</span><button disabled={(resourcePage+1)*pageSize>=resources.length} onClick={()=>setPage(resourcePage+1)}>Next resources</button></div>}
   {selectedResource&&<div className="company-operating-connections"><h4>Retained connection evidence · {displayName(selectedResource.display_name)}</h4>{selectedConnections.slice(0,20).map(item=><div key={operatingResourceKey(item.record)}><span>{displayName(item.source.display_name)} <strong>{human(item.relation.display_name)}</strong> {displayName(item.target.display_name)}</span>{actions(item.record)}</div>)}{selectedConnections.length>20&&<p className="company-operating-note">Showing 20 of {selectedConnections.length} returned connections. Inspect the exact resource in Trace to explore more.</p>}</div>}
  </section>
  <section className="company-operating-licences" aria-label="Company licence evidence"><header><h3>Regulatory & licence evidence</h3><span>Retained evidence · compliance not established</span></header>{result.licence_evidence.length?<div className="company-operating-table"><table><thead><tr><th>Licence / retained notice</th><th>Evidence linkage</th><th>Inspect</th></tr></thead><tbody>{result.licence_evidence.slice(currentLicencePage*pageSize,(currentLicencePage+1)*pageSize).map(item=><tr key={operatingResourceKey(item.binding)}><th scope="row">{displayName(item.licence?.display_name??item.binding.display_name)}<small>{item.notice?displayName(item.notice.display_name):"Retained notice dependency unavailable"}</small></th><td><span className="company-operating-reference">Reviewed evidence binding</span><small>Current licence validity and compliance require separate authority.</small></td><td>{actions(item.binding)}{item.notice&&<button onClick={()=>inspect(item.notice!)}>Open notice</button>}{item.licence&&<button onClick={()=>inspect(item.licence!)}>Open licence</button>}</td></tr>)}</tbody></table></div>:<p className="company-operating-empty">No licence evidence bindings were returned for this company snapshot. This does not determine whether a licence is required.</p>}{result.licence_evidence.length>pageSize&&<div className="company-operating-pager"><button disabled={currentLicencePage===0} onClick={()=>setLicencePage(currentLicencePage-1)}>Previous licences</button><span>{currentLicencePage*pageSize+1}–{Math.min((currentLicencePage+1)*pageSize,result.licence_evidence.length)} of {result.licence_evidence.length}</span><button disabled={(currentLicencePage+1)*pageSize>=result.licence_evidence.length} onClick={()=>setLicencePage(currentLicencePage+1)}>Next licences</button></div>}</section>
  <CompanyRegulation token={token} company={result.company} validAt={validAt} knownAt={knownAt} onInspect={onInspect} onTrace={onTrace}/>
  </details><footer><span>Company resources effective {stamp(result.valid_at)} · known {stamp(result.known_at)}</span><details><summary>Unavailable capabilities & authority</summary>{result.unavailable.map(item=><p key={item.key}><strong>{item.label}.</strong> {item.reason}</p>)}<p>This view grants no new current-use permission or business action.</p></details></footer>
 </section>;
}
