"use client";
import {useEffect,useState} from "react";
import type {CanonicalResource,CompanyConditionDescriptor,CompanyConditionWorkItem} from "@finai/contracts";
import {assertCompanyCondition,operatingResourceKey,rankCompanyWork} from "./company-operating-state";
import {displayName} from "./display-name";
import "./company-operating-workspace.css";

type ResourceAction=(resource:CanonicalResource,knownAt:string)=>void;
export type CompanyOperatingProps={token:string;companyId:string;snapshot:{validAt:string;knownAt:string};compact?:boolean;onInspect:ResourceAction;onTrace?:ResourceAction;onHistory?:ResourceAction;onProposal?:(id:string)=>void;onWorkflow?:(id:string)=>void};
const human=(value:string)=>value.replace(/([a-z])([A-Z])/g,"$1 $2").replaceAll("_"," ").toLowerCase();
const stamp=(value:string)=>new Date(value).toLocaleString();
const inventoryGroups=[{key:"assets",label:"Assets & facilities"},{key:"products",label:"Products"},{key:"parties",label:"Business parties"},{key:"contracts",label:"Contracts"}] as const;

export default function CompanyOperatingWorkspace(props:CompanyOperatingProps){return <OperatingWorkspace key={`${props.token}:${props.companyId}:${props.snapshot.validAt}:${props.snapshot.knownAt}`} {...props}/>;}
function OperatingWorkspace({token,companyId,snapshot,compact=false,onInspect,onTrace,onHistory,onProposal,onWorkflow}:CompanyOperatingProps){
 const [result,setResult]=useState<CompanyConditionDescriptor|null>(null),[error,setError]=useState("");const [revision,setRevision]=useState(0);
 const [workFilter,setWorkFilter]=useState<"ALL"|CompanyConditionWorkItem["state"]>("ALL"),[workSearch,setWorkSearch]=useState("");
 const [group,setGroup]=useState<"assets"|"products"|"parties"|"contracts">("assets"),[search,setSearch]=useState("");
 const [page,setPage]=useState(0),[workPage,setWorkPage]=useState(0),[licencePage,setLicencePage]=useState(0),[selected,setSelected]=useState("");
 const {validAt,knownAt}=snapshot;
 useEffect(()=>{const controller=new AbortController();let disposed=false;const timer=setTimeout(()=>controller.abort(),25000);
  const params=new URLSearchParams({company_id:companyId,valid_at:validAt,known_at:knownAt});
  void fetch(`/api/ontology/company-condition?${params}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store",signal:controller.signal}).then(async response=>{
   const data=await response.json();if(!response.ok)throw Error(typeof data.detail==="string"?data.detail:"Company operating context is unavailable.");
   assertCompanyCondition(data,{companyId,validAt,knownAt});if(!disposed){setResult(data);setError("");}
  }).catch(failure=>{if(!disposed){setResult(null);setError(controller.signal.aborted?"Company operating context timed out. Retry this snapshot.":failure instanceof Error?failure.message:"Company operating context is unavailable.");}}).finally(()=>clearTimeout(timer));
  return()=>{disposed=true;clearTimeout(timer);controller.abort();};
 },[token,companyId,validAt,knownAt,revision]);
 function retry(){setResult(null);setError("");setRevision(value=>value+1);}
 function inspect(resource:CanonicalResource){setSelected(operatingResourceKey(resource));onInspect(resource,knownAt);}
 function actions(resource:CanonicalResource){return <span className="company-operating-row-actions"><button onClick={()=>onInspect(resource,knownAt)}>Inspect</button>{onTrace&&<button onClick={()=>onTrace(resource,knownAt)}>Trace</button>}{onHistory&&<button onClick={()=>onHistory(resource,knownAt)}>History</button>}</span>;}
 if(error)return <section className="company-operating-error" role="alert"><h3>Company operating context unavailable</h3><p>{error}</p><button onClick={retry}>Retry exact snapshot</button></section>;
 if(!result)return <p className="company-operating-loading" role="status">Resolving linked company resources, retained work and regulatory evidence…</p>;
 const pageSize=compact?5:10,query=search.trim().toLocaleLowerCase();
 const resources=result[group].resources.filter(item=>`${item.display_name} ${item.object_type}`.toLocaleLowerCase().includes(query));
 const orderedWork=rankCompanyWork(result.work.items,workFilter,workSearch);
 const work=orderedWork.slice(workPage*pageSize,(workPage+1)*pageSize);
 const selectedResource=result[group].resources.find(item=>operatingResourceKey(item)===selected);
 const selectedConnections=result.connections.filter(item=>[item.source,item.target].some(node=>operatingResourceKey(node)===selected));
 return <section className={`company-operating-workspace${compact?" company-operating-compact":""}`} aria-label="Company operating workbench">
  <header><div><p className="overline">COMPANY WORK & OPERATING CONTEXT</p><h2>Decisions, obligations & connected resources</h2></div><button onClick={retry}>Refresh retained context</button></header>
  <section className="company-operating-work" aria-label="Current company work"><header><h3>Work requiring review and recent outcomes</h3><span>Observed {stamp(result.work.observed_at)}</span></header><p className="company-operating-note">Current retained work explicitly linked to this company. This queue is separate from the historical company snapshot.</p>
   <div className="company-operating-signals">{result.unavailable.filter(item=>item.key==="findings"||item.key==="investigations").map(item=><p key={item.key}><strong>{item.label} unavailable.</strong> {item.reason}</p>)}</div>
   {result.work.state==="AVAILABLE"&&<div className="company-operating-toolbar"><label>Priority within returned queue<select value={workFilter} onChange={event=>{setWorkFilter(event.target.value as "ALL"|CompanyConditionWorkItem["state"]);setWorkPage(0);}}><option value="ALL">All returned work</option>{(["PENDING_REVIEW","PREPARED","REJECTED","PUBLISHED"] as const).map(state=><option key={state} value={state}>{human(state)}</option>)}</select></label><label>Find work<input value={workSearch} onChange={event=>{setWorkSearch(event.target.value);setWorkPage(0);}} placeholder="Title or reason"/></label><span className="company-operating-note">Review priority; no financial materiality ranking</span></div>}
   {result.work.state==="UNAVAILABLE"?<p className="company-operating-limitation" role="status"><strong>Current company work is unavailable.</strong> {result.work.reason} Resource and licence context remain available below.</p>:work.length?<div className="company-operating-table"><table><thead><tr><th>Company work</th><th>Retained state</th><th>Why it matters</th><th>Open</th></tr></thead><tbody>{work.map(item=><tr key={item.workflow_id}><th scope="row">{displayName(item.title)}<small>Created {stamp(item.created_at)}</small></th><td><span className="company-operating-status" data-state={item.state}>{human(item.state)}</span></td><td>{item.reason}</td><td><span className="company-operating-row-actions">{item.state!=="PREPARED"&&item.proposal_id&&onProposal&&<button onClick={()=>onProposal(item.proposal_id!)}>Open review</button>}{onWorkflow&&<button onClick={()=>onWorkflow(item.workflow_id)}>Open workflow</button>}{!onWorkflow&&!(item.state!=="PREPARED"&&item.proposal_id&&onProposal)&&<span>Navigation unavailable</span>}</span></td></tr>)}</tbody></table></div>:<p className="company-operating-empty">{result.work.items.length?"No returned work matches these filters.":"No explicitly linked retained work was returned. This does not establish that the company has no outstanding obligations."}</p>}
   {orderedWork.length>pageSize&&<div className="company-operating-pager"><button disabled={workPage===0} onClick={()=>setWorkPage(value=>value-1)}>Previous work</button><span>{workPage*pageSize+1}–{Math.min((workPage+1)*pageSize,orderedWork.length)} of {orderedWork.length} matching returned</span><button disabled={(workPage+1)*pageSize>=orderedWork.length} onClick={()=>setWorkPage(value=>value+1)}>Next work</button></div>}{result.work.truncated&&<p className="company-operating-limitation">The server returned a bounded queue of {result.work.limit} items. Other company work may exist.</p>}
  </section>
  <details className="company-operating-resource-depth" open={!compact}><summary hidden={!compact}>Connected resources & licence evidence</summary><section className="company-operating-inventory" aria-label="Connected company resources"><div className="company-operating-toolbar"><div className="company-operating-groups" aria-label="Resource group">{inventoryGroups.map(item=><button key={item.key} aria-pressed={group===item.key} onClick={()=>{setGroup(item.key);setPage(0);setSelected("");}}>{item.label}<span>{result[item.key].resources.length}</span></button>)}</div><label>Find linked resource<input value={search} onChange={event=>{setSearch(event.target.value);setPage(0);}} placeholder="Name or type"/></label></div><p className="company-operating-note">{result[group].reason} Explicit company connections are bounded to {result.connection_depth} steps; presence does not establish ownership, balances or live operating condition.</p>
   {resources.length?<div className="company-operating-table"><table><thead><tr><th>Business resource</th><th>Recorded kind</th><th>Context & evidence</th></tr></thead><tbody>{resources.slice(page*pageSize,(page+1)*pageSize).map(resource=><tr key={operatingResourceKey(resource)} aria-selected={selected===operatingResourceKey(resource)}><th scope="row"><button className="company-operating-name" onClick={()=>inspect(resource)}>{displayName(resource.display_name)}</button></th><td>{human(resource.object_type)}</td><td>{actions(resource)}</td></tr>)}</tbody></table></div>:<p className="company-operating-empty">{query?"No returned resources match this search.":"No resources in this group were returned through accepted company connections."}</p>}
   {resources.length>pageSize&&<div className="company-operating-pager"><button disabled={page===0} onClick={()=>setPage(value=>value-1)}>Previous resources</button><span>{page*pageSize+1}–{Math.min((page+1)*pageSize,resources.length)} of {resources.length} returned</span><button disabled={(page+1)*pageSize>=resources.length} onClick={()=>setPage(value=>value+1)}>Next resources</button></div>}
   {selectedResource&&<div className="company-operating-connections"><h4>Retained connection evidence · {displayName(selectedResource.display_name)}</h4>{selectedConnections.slice(0,20).map(item=><div key={operatingResourceKey(item.record)}><span>{displayName(item.source.display_name)} <strong>{human(item.relation.display_name)}</strong> {displayName(item.target.display_name)}</span>{actions(item.record)}</div>)}{selectedConnections.length>20&&<p className="company-operating-note">Showing 20 of {selectedConnections.length} returned connections. Inspect the exact resource in Trace to explore more.</p>}</div>}
  </section>
  <section className="company-operating-licences" aria-label="Company licence evidence"><header><h3>Regulatory & licence evidence</h3><span>Retained evidence · compliance not established</span></header>{result.licence_evidence.length?<div className="company-operating-table"><table><thead><tr><th>Licence / retained notice</th><th>Evidence linkage</th><th>Inspect</th></tr></thead><tbody>{result.licence_evidence.slice(licencePage*pageSize,(licencePage+1)*pageSize).map(item=><tr key={operatingResourceKey(item.binding)}><th scope="row">{displayName(item.licence?.display_name??item.binding.display_name)}<small>{item.notice?displayName(item.notice.display_name):"Retained notice dependency unavailable"}</small></th><td><span className="company-operating-reference">Reviewed evidence binding</span><small>Current licence validity and compliance require separate authority.</small></td><td>{actions(item.binding)}{item.notice&&<button onClick={()=>inspect(item.notice!)}>Open notice</button>}{item.licence&&<button onClick={()=>inspect(item.licence!)}>Open licence</button>}</td></tr>)}</tbody></table></div>:<p className="company-operating-empty">No licence evidence bindings were returned for this company snapshot. This does not determine whether a licence is required.</p>}{result.licence_evidence.length>pageSize&&<div className="company-operating-pager"><button disabled={licencePage===0} onClick={()=>setLicencePage(value=>value-1)}>Previous licences</button><span>{licencePage*pageSize+1}–{Math.min((licencePage+1)*pageSize,result.licence_evidence.length)} of {result.licence_evidence.length}</span><button disabled={(licencePage+1)*pageSize>=result.licence_evidence.length} onClick={()=>setLicencePage(value=>value+1)}>Next licences</button></div>}</section>
  </details><footer><span>Company resources effective {stamp(result.valid_at)} · known {stamp(result.known_at)}</span><details><summary>Unavailable capabilities & authority</summary>{result.unavailable.map(item=><p key={item.key}><strong>{item.label}.</strong> {item.reason}</p>)}<p>This view grants no new current-use permission or business action.</p></details></footer>
 </section>;
}
