"use client";
import {useState,type FormEvent} from "react";
import {Buildings,ArrowRight} from "@phosphor-icons/react";
import type {Principal,ResourceProposalDetail} from "@finai/contracts";
import {Badge} from "./g8-ui";

export default function CompanySetup({token,principal,onSubmitted}: {token:string;principal:Principal;onSubmitted:(proposal:ResourceProposalDetail)=>void}) {
  const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const [saved,setSaved]=useState<ResourceProposalDetail|null>(null);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");
    const values=new FormData(event.currentTarget);const name=String(values.get("name")).trim();const code=String(values.get("code")).trim();
    const attributes:Record<string,string>={};for(const key of ["jurisdiction","registration_code"]){const value=String(values.get(key)??"").trim();if(value)attributes[key]=value;}
    try{const response=await fetch("/api/ontology/proposals",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({proposal_id:crypto.randomUUID(),title:`Register company: ${name}`.slice(0,200),rationale:String(values.get("rationale")),access_entity:principal.scope.legal_entity_id,mutations:[{resource_id:crypto.randomUUID(),object_type:"LegalEntity",identity_key:code,display_name:name,attributes,valid_from:new Date().toISOString(),evidence_class:"USER_ASSERTED"}]})});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==="string"?data.detail:"The company proposal could not be validated.");setSaved(data);setOpen(false);onSubmitted(data);}catch(error){setError(error instanceof Error?error.message:"Company setup unavailable");}finally{setBusy(false);}}
  return <section className="company-setup"><div className="company-setup-intro"><Buildings size={30}/><div><h2>Establish your company context</h2><p>Register a legal entity once. Accepted company identity can then be reused across data, accounts and business workspaces.</p></div>{principal.permissions.includes("ontology_propose") && principal.permissions.includes("ontology_read")&&<button onClick={()=>setOpen(!open)}>{open?"Cancel":"Propose company"}<ArrowRight size={16}/></button>}</div>{saved&&<p className="success-banner" role="status">{saved.proposal.title} is awaiting independent review. It is not an accepted company yet.</p>}{!principal.permissions.includes("ontology_propose")&&<p className="g8-inline-error">A company steward must submit the company identity. Your current identity does not have proposal permission.</p>}{open&&<form onSubmit={submit} className="company-setup-form"><label>Legal company name<input name="name" required maxLength={200} placeholder="Name as registered"/></label><label>Company code<input name="code" required maxLength={128} placeholder="Your organization's unique company code"/><small>Use the shared identifier consistently; do not create a second identity for an existing company.</small></label><label>Jurisdiction<input name="jurisdiction" maxLength={128} placeholder="Country or jurisdiction"/></label><label>Registration number<input name="registration_code" maxLength={128} placeholder="Preserved exactly as supplied"/></label><label className="company-rationale">Reason and source reference<textarea name="rationale" required minLength={10} maxLength={2000} placeholder="Explain the identity and the records supporting it."/></label><div className="company-form-footer"><Badge>User supplied · review required</Badge><button disabled={busy}>{busy?"Validating…":"Submit for independent review"}</button></div>{error&&<p role="alert" className="g8-inline-error">{error}</p>}</form>}</section>;
}
