"use client";
import {useState,type ReactNode} from "react";
import {ArrowRight,ChartLineUp,Graph,Database} from "@phosphor-icons/react";
import type {CanonicalResource} from "@finai/contracts";
import {Badge,Panel} from "./g8-ui";
import {readable} from "./g8-model";
const statements={"P&L":["Revenue","Gross Profit","EBITDA","Net Profit"],"Balance Sheet":["Total Assets","Total Liabilities","Equity","Cash"],"Cash Flow":["Operating","Investing","Financing","Net Movement"],"Key Ratios":["Gross Margin","EBITDA Margin","Current Ratio","Net Debt / EBITDA"]};
export default function ExecutiveOverview({company,period,currency,resources,resourcesAvailable,onData,onCompanies,onOntology,operationalPanel}:{company:string;period:string;currency:string;resources:CanonicalResource[];resourcesAvailable:boolean;onData:()=>void;onCompanies:()=>void;onOntology:()=>void;operationalPanel?:ReactNode}) {
 const [statement,setStatement]=useState<keyof typeof statements>("P&L");const [layer,setLayer]=useState("networks");
 const types=layer==="networks"?["OperationalNetwork","GasDistributionSystem","PipelineSegment"]:["Facility","Location","AssetPortfolio"];
 const objects=resources.filter(item=>types.includes(item.object_type));
 return <div className="g8-executive-overview"><Panel title="Key financials" className="g8-financial-panel" aside={<div className="g8-finance-tabs" aria-label="Financial statement">{Object.keys(statements).map(name=><button key={name} aria-pressed={statement===name} onClick={()=>setStatement(name as keyof typeof statements)}>{name}</button>)}</div>}><div className="g8-finance-context"><button className="quiet" onClick={onCompanies}>{company}<ArrowRight size={12}/></button><span>{period} · {currency}</span></div><div className="g8-financial-metrics">{statements[statement].map(name=><div key={name}><span>{name}</span><strong aria-label={`${name}: unavailable`}>—</strong><small>Not established</small></div>)}</div><div className="g8-financial-chart-state"><ChartLineUp size={32}/><h3>No accepted {statement} is available</h3><p>Financial statements are not connected for this company and period. Review available source evidence to see what has been received.</p><button className="g8-link" onClick={onData}>Inspect available financial evidence<ArrowRight size={14}/></button></div><div className="g8-panel-foot"><span>Financial values and comparative trends are unavailable.</span><Badge>Not certified</Badge></div></Panel>{operationalPanel ?? <Panel title="Network & operations" className="g8-operations-panel" aside={<label><span className="sr-only">Operational resource view</span><select aria-label="Operational resource view" value={layer} onChange={e=>setLayer(e.target.value)}><option value="networks">Networks</option><option value="facilities">Facilities & locations</option></select></label>}><div className="g8-operations-canvas">{objects.length?<div className="g8-operational-resources">{objects.slice(0,6).map(item=><button key={item.resource_id} onClick={onOntology}><Graph size={20}/><span>{item.display_name}<small>{readable(item.object_type)} · {readable(item.authority_state)}</small></span><ArrowRight size={13}/></button>)}</div>:<div className="g8-operation-empty"><Graph size={34}/><h3>{!resourcesAvailable?"Operational resources unavailable":`No accepted ${layer==="networks"?"network":"facility or location"} resources in this context`}</h3><p>Map layers and operating signals appear when governed assets, locations and observations are connected.</p><button className="g8-link" onClick={onOntology}>Explore company connections<ArrowRight size={14}/></button></div>}</div><div className="g8-operations-facts"><div><strong>{resourcesAvailable?objects.length:"—"}</strong><small>Resources in this view</small></div><div><strong>—</strong><small>Live telemetry</small></div><div><strong>—</strong><small>Geographic coverage</small></div></div><div className="g8-panel-foot"><span><Database size={12}/> Accepted resources only</span><button className="g8-link" onClick={onData}>Source evidence<ArrowRight size={13}/></button></div></Panel>}</div>;
}
