"use client";

import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import dynamic from "next/dynamic";
import Image from "next/image";
import { House, Buildings, Database, Graph as GraphIcon, GearSix, MagnifyingGlass, ArrowRight, ArrowClockwise, SignOut, ShieldCheck, ChartLineUp, GlobeHemisphereWest, Tray, UploadSimple, List, X, CaretRight } from "@phosphor-icons/react";
import type { CanonicalDetail, CanonicalResource, Principal, ReceiptDetail, ResourceProposalDetail } from "@finai/contracts";
import type { EngineeringView } from "./operator-workspace";
import { Badge, Brand, Empty, Panel, Signal } from "./g8-ui";
import { acceptedCompanies, belongsToCompany, emptySnapshot, readable, workItems, type Loadable, type Snapshot, type WorkItem } from "./g8-model";
import ProposalImpact from "./proposal-impact";

const Engineering = dynamic(() => import("./operator-workspace"), {loading:() => <p role="status">Opening engineering tools…</p>});
type View = "home" | "companies" | "data" | "ontology" | "system";
const areas = [{id:"home",label:"Home",hint:"My work",icon:House},{id:"companies",label:"Companies",hint:undefined,icon:Buildings},{id:"data",label:"Data",hint:undefined,icon:Database},{id:"ontology",label:"Ontology",hint:undefined,icon:GraphIcon}] as const;
const tone = (state: string) => state === "APPROVED" || state === "ready" ? "good" : state === "REJECTED" || state === "REVOKED" ? "bad" : state === "PENDING" ? "warning" : "neutral";
const date = (value: string) => new Date(value).toLocaleDateString(undefined,{month:"short",day:"numeric"});
async function get<T>(path: string, token: string, signal?: AbortSignal): Promise<T> {
  const response = await fetch(`/api/${path}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store",signal});
  const data = await response.json();
  // A readiness response is an observed degraded state, not a failed data request.
  if (!response.ok && !(path === "readiness" && data.evidence_store)) throw new Error(typeof data.detail === "string" ? data.detail : `Request unavailable (${response.status})`);
  return data as T;
}

export default function G8Workspace() {
  const [session,setSession] = useState<{token:string;principal:Principal} | null>(null);
  const [error,setError] = useState(""); const [busy,setBusy] = useState(false);
  async function signIn(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError("");
    const token = String(new FormData(event.currentTarget).get("token") ?? "").trim();
    try {const principal = await get<Principal>("workspace/session",token); setSession({token,principal});}
    catch (failure) {setError(failure instanceof Error ? failure.message : "Sign-in unavailable");}
    finally {setBusy(false);}
  }
  if (session) return <SignedIn key={session.principal.actor_id} {...session} onSignOut={() => setSession(null)} />;
  return <main className="g8-login"><section className="g8-login-story"><Brand /><div><p className="overline">ENTERPRISE INTELLIGENCE</p><h1>Understand the evidence.<br />See the context.<br />Act with confidence.</h1><p>One workspace for your companies, retained sources and governed decisions.</p><div className="g8-principles"><span>Exact context<small>Company and version stay bound.</small></span><span>Visible evidence<small>Trace every accepted change.</small></span><span>Controlled action<small>Independent review is preserved.</small></span></div></div><Image className="g8-brand-banner" src="/brand/nyx-core-banner.jpg" alt="NYX Core cognition systems — G8" width={750} height={250} /></section><section className="g8-login-form"><form onSubmit={signIn}><ShieldCheck size={30} /><p className="overline">G8 WORKSPACE ACCESS</p><h2>Sign in to your workspace</h2><p>Your identity determines the company access, evidence and actions available to you.</p><label>Workspace access key<input name="token" type="password" required autoComplete="off" autoFocus /></label><button disabled={busy}>{busy ? "Connecting…" : "Continue securely"}<ArrowRight size={18} /></button>{error && <p role="alert" className="error-banner">{error}</p>}<small>Use your organization-issued access key. It stays in memory for this session.</small></form></section></main>;
}

function SignedIn({token,principal,onSignOut}: {token:string;principal:Principal;onSignOut:()=>void}) {
  const [view,setView] = useState<View>("home"); const [snapshot,setSnapshot] = useState<Snapshot>(emptySnapshot);
  const [loading,setLoading] = useState(true); const [revision,setRevision] = useState(0); const [updated,setUpdated] = useState("");
  const [companyId,setCompanyId] = useState(""); const [search,setSearch] = useState(""); const [workFilter,setWorkFilter] = useState("pending");
  const [selected,setSelected] = useState<CanonicalDetail | null>(null); const [work,setWork] = useState<WorkItem | null>(null);
  const [receipt,setReceipt] = useState<ReceiptDetail | null>(null); const [proposal,setProposal] = useState<ResourceProposalDetail | null>(null);
  const [detailError,setDetailError] = useState(""); const [detailBusy,setDetailBusy] = useState(false);
  const [engineering,setEngineering] = useState<{view:EngineeringView;receiptId?:string}>({view:"intake"});
  const [menu,setMenu] = useState(false); const [rail,setRail] = useState(false);
  const detailRequest = useRef(0); const searchRef = useRef<HTMLInputElement>(null); const workRef = useRef<HTMLDivElement>(null);
  const canOntology = principal.permissions.includes("ontology_read");
  const refresh = useCallback(() => setRevision(value => value+1),[]);
  useEffect(() => {
    const controller = new AbortController(); let cancelled = false;
    async function load() {
      setLoading(true);
      async function read<T>(path:string): Promise<Loadable<T>> {try {return {data:await get<T>(path,token,controller.signal),error:null};} catch(error) {return {data:null,error:error instanceof Error ? error.message : "Unavailable"};}}
      const noAccess = Promise.resolve({data:null,error:"Your identity does not include ontology access."});
      const [summary,evidence,graph,proposals,context,readiness] = await Promise.all([
        read<NonNullable<Snapshot["summary"]["data"]>>("workspace/summary"),read<NonNullable<Snapshot["evidence"]["data"]>>("workspace/intake"),
        canOntology ? read<NonNullable<Snapshot["graph"]["data"]>>("ontology/graph") : noAccess,
        canOntology ? read<NonNullable<Snapshot["proposals"]["data"]>>("ontology/proposals") : noAccess,
        canOntology ? read<NonNullable<Snapshot["context"]["data"]>>("ontology/context") : noAccess,
        read<NonNullable<Snapshot["readiness"]["data"]>>("readiness")]);
      if (!cancelled) {setSnapshot({summary,evidence,graph,proposals,context,readiness});setUpdated(new Date().toLocaleTimeString(undefined,{hour:"2-digit",minute:"2-digit"}));setLoading(false);}
    }
    void load(); return () => {cancelled=true;controller.abort();};
  },[token,canOntology,revision]);
  useEffect(() => {
    function shortcut(event:KeyboardEvent) {if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") {event.preventDefault();searchRef.current?.focus();} if(event.key === "Escape") {setSearch("");setMenu(false);setRail(false);}}
    document.addEventListener("keydown",shortcut); return () => document.removeEventListener("keydown",shortcut);
  },[]);
  const resources = snapshot.graph.data?.resources ?? [];
  const companies = acceptedCompanies(resources);
  // A company choice is an explorer selection. The server-issued evidence scope never changes with it.
  const company = companies.find(item => item.resource_id === companyId);
  const contextCompanyId = snapshot.context.data?.canonical_references.legal_entity_id?.resource_id;
  const boundCompany = companies.find(item => item.resource_id === contextCompanyId);
  const currentCompany = company ?? boundCompany;
  const companyMismatch = !!currentCompany && currentCompany.resource_id !== contextCompanyId;
  const scopedEvidence = companyMismatch ? [] : snapshot.evidence.data ?? [];
  const scopedProposals = (snapshot.proposals.data ?? []).filter(item => !currentCompany || item.access_entity === currentCompany.access_entity || item.access_entity === "__PLATFORM__");
  const items = workItems(scopedEvidence,scopedProposals);
  const pending = items.filter(item => item.state === "PENDING");
  const shown = items.filter(item => workFilter === "all" || item.state === "PENDING");
  const query = search.trim().toLocaleLowerCase();
  const visibleResources = resources.filter(item => !["SchemaDefinition","SemanticContract","LinkType"].includes(item.object_type))
    .filter(item => !currentCompany || belongsToCompany(item,currentCompany.resource_id));
  const results = query ? [...resources.filter(item => item.display_name.toLocaleLowerCase().includes(query)).map(item => ({id:item.resource_id,title:item.display_name,kind:readable(item.object_type),resource:item,work:null})),...items.filter(item => item.title.toLocaleLowerCase().includes(query)).map(item => ({id:item.id,title:item.title,kind:readable(item.kind),resource:null,work:item}))].slice(0,12) : [];
  const ready = snapshot.readiness.data;
  const openEngineering = (next:EngineeringView,receiptId?:string) => {setEngineering({view:next,receiptId});setView("system");setMenu(false);};
  const navigate = (next:View) => {setView(next);setMenu(false);setSearch("");if(next === "home" || next === "data") refresh();};
  const clearSelection = () => {detailRequest.current++;setSelected(null);setWork(null);setReceipt(null);setProposal(null);setDetailError("");setDetailBusy(false);};
  async function inspect(resource:CanonicalResource) {
    const request = ++detailRequest.current;setWork(null);setReceipt(null);setProposal(null);setSelected(null);setDetailError("");setDetailBusy(true);setRail(true);setSearch("");
    try {const value=await get<CanonicalDetail>(`ontology/resources/${resource.resource_id}`,token);if(request===detailRequest.current)setSelected(value);}
    catch(error){if(request===detailRequest.current)setDetailError(error instanceof Error ? error.message : "Could not inspect resource");}
    finally {if(request===detailRequest.current)setDetailBusy(false);}
  }
  async function inspectWork(item:WorkItem) {
    const request=++detailRequest.current;setWork(item);setSelected(null);setReceipt(null);setProposal(null);setDetailError("");setDetailBusy(true);setRail(true);setSearch("");
    try {if(item.kind === "evidence") {const value=await get<ReceiptDetail>(`workspace/constructions/${item.id}`,token);if(request===detailRequest.current)setReceipt(value);}else {const value=await get<ResourceProposalDetail>(`ontology/proposals/${item.id}`,token);if(request===detailRequest.current)setProposal(value);}}
    catch(error){if(request===detailRequest.current)setDetailError(error instanceof Error ? error.message : "Could not inspect work");}
    finally {if(request===detailRequest.current)setDetailBusy(false);}
  }
  const workTable = <><div className="g8-tabs" aria-label="Work filter">{["pending","all"].map(value => <button key={value} aria-pressed={workFilter===value} onClick={()=>setWorkFilter(value)}>{value === "pending" ? "Needs attention" : "All changes"}</button>)}<span>{companyMismatch ? "No evidence scope for this company" : "Current access scope"}</span></div>{snapshot.evidence.error && <p className="g8-inline-error" role="status">Evidence queue unavailable: {snapshot.evidence.error}</p>}{snapshot.proposals.error && <p className="g8-inline-error" role="status">Change queue unavailable: {snapshot.proposals.error}</p>}{shown.length ? <div className="g8-table-scroll"><table><thead><tr><th>Work item</th><th>Type</th><th>State</th><th>Received</th></tr></thead><tbody>{shown.slice(0,30).map(item=><tr key={`${item.kind}:${item.id}`}><td><button className="g8-link" onClick={()=>void inspectWork(item)}>{item.title}</button></td><td>{item.kind === "evidence" ? "Source review" : "Change review"}</td><td><Badge tone={tone(item.state)}>{readable(item.state)}</Badge></td><td>{date(item.date)}</td></tr>)}</tbody></table></div> : <Empty title={loading ? "Loading your work…" : "No review items in this view"}>{loading ? "Checking the current access scope." : "Available queues have no matching items. Source and company access remain explicit."}</Empty>}<div className="g8-panel-foot">Latest 50 source receipts and available change proposals. <button className="g8-link" onClick={()=>openEngineering("history")}>Browse history<ArrowRight size={13}/></button></div></>;
  return <div className={`g8-app ${menu ? "menu-open" : ""} ${rail ? "rail-open" : ""}`}><a className="g8-skip" href="#g8-main">Skip to workspace</a>
    <aside className="g8-sidebar"><Brand /><p className="g8-tagline">Enterprise Intelligence</p><nav aria-label="Business navigation">{areas.map(({id,label,hint,icon:Icon})=><button aria-current={view===id ? "page" : undefined} className={view===id ? "active" : ""} onClick={()=>navigate(id)} key={id}><Icon size={21} weight="regular"/><span>{label}{hint && <small>{hint}</small>}</span></button>)}</nav><div className="g8-nav-bottom"><button className={`g8-system ${view === "system" ? "active" : ""}`} onClick={()=>navigate("system")}><GearSix size={21}/><span>System<small>Engineering access</small></span><CaretRight size={13}/></button><div className="g8-platform"><ShieldCheck size={20}/><span>G8 Platform<small>{loading ? "Checking services…" : ready?.status === "ready" ? "Services ready" : "Readiness unavailable"}</small></span></div></div></aside>
    <header className="g8-topbar"><button className="g8-icon mobile-menu" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}><List size={21}/></button><div className="g8-search"><MagnifyingGlass size={19}/><input ref={searchRef} aria-label="Search workspace" placeholder="Search companies, data and work…" value={search} onChange={event=>setSearch(event.target.value)}/><kbd>Ctrl K</kbd>{query && <div className="g8-search-results" role="region" aria-label="Search results"><small>Search within loaded, authorized resources</small>{results.map(result=><button key={result.id} onClick={()=>result.resource ? void inspect(result.resource) : result.work && void inspectWork(result.work)}><span>{result.title}<small>{result.kind}</small></span><ArrowRight size={15}/></button>)}{!results.length && <p>No matching resources in the current snapshot.</p>}</div>}</div><div className="g8-top-context"><Buildings size={17}/><label><span className="sr-only">Company context</span><select value={currentCompany?.resource_id ?? ""} onChange={event=>{setCompanyId(event.target.value);clearSelection();}}><option value="">{boundCompany ? "Bound company" : "Accessible companies"}</option>{companies.map(item=><option value={item.resource_id} key={item.resource_id}>{item.display_name}</option>)}</select></label></div><button className="g8-icon" aria-label="Refresh workspace" onClick={refresh} disabled={loading}><ArrowClockwise size={19}/></button><div className="g8-user"><span>{principal.display_name.split(" ").map(part=>part[0]).slice(0,2).join("")}</span><div>{principal.display_name}<small>Governed workspace</small></div></div><button className="g8-icon" aria-label="Sign out" onClick={onSignOut}><SignOut size={19}/></button><button className="g8-icon mobile-analyst" aria-label="Open NYX context" onClick={()=>setRail(!rail)}><Image src="/brand/nyx-core.jpg" alt="" width={25} height={25}/></button></header>
    <main id="g8-main" className="g8-main"><div className="g8-breadcrumb">Workspace< CaretRight size={12}/>{view === "system" ? "System / Engineering" : areas.find(area=>area.id===view)?.label}<span>{loading ? "Refreshing…" : `Updated ${updated}`}</span></div>
    {view === "system" ? <><div className="g8-page-heading"><div><p className="overline">ADVANCED INTERNAL ACCESS</p><h1>System / Engineering</h1><p>Evidence intake, construction, registry and governed review tools.</p></div><Badge>Advanced</Badge></div><Engineering key={`${engineering.view}:${engineering.receiptId ?? ""}`} token={token} principal={principal} initialView={engineering.view} receiptId={engineering.receiptId}/></> : <>
      <div className="g8-page-heading"><div><p className="overline">{view === "home" ? `YOUR WORKSPACE · ${principal.display_name}` : "ENTERPRISE WORKSPACE"}</p><h1>{view === "home" ? currentCompany?.display_name ?? "Your enterprise workspace" : view === "companies" ? "Companies" : view === "data" ? "Data & evidence" : "Ontology"}</h1><p>{view === "home" ? "Financial reality. Operational context. Evidence-led decisions." : view === "companies" ? "Shared company identities. One connected business context." : view === "data" ? "Retained sources, review state and traceable versions." : "Explore the business resources behind your workspace."}</p></div><Badge tone={currentCompany ? tone(currentCompany.authority_state) : "neutral"}>{currentCompany ? readable(currentCompany.evidence_class) : "Company not selected"}</Badge></div>
      {snapshot.graph.data?.bounded && <p className="g8-inline-error">Showing up to 1,000 authorized resources. This is a bounded view.</p>}
      {companyMismatch && <p className="g8-inline-error">Company exploration selected. Evidence remains bound to your sign-in scope; no source data is attributed to this company.</p>}
      {view === "home" && <><div className="g8-actionbar"><button onClick={()=>{setWorkFilter("pending");workRef.current?.scrollIntoView({behavior:"smooth"});}}><Tray size={23}/><span>Review items<small>{loading ? "Checking…" : `${pending.length} in loaded queues`}</small></span></button><button onClick={()=>navigate("data")}><Database size={23}/><span>Explore data<small>Sources & versions</small></span></button>{principal.permissions.includes("ingest") && <button onClick={()=>openEngineering("intake")}><UploadSimple size={23}/><span>New data source<small>Retain source evidence</small></span></button>}<button onClick={()=>navigate("ontology")}><GraphIcon size={23}/><span>Explore connections<small>Company & evidence context</small></span></button></div>
      <div className="g8-canvas"><Panel title="Financial evidence" aside={<Badge>Not certified</Badge>}><div className="g8-panel-intro"><ChartLineUp size={27}/><div><h3>Start with what the evidence establishes</h3><p>Inspect retained sources and their review state. Financial statements and performance measures are not yet available.</p></div></div><div className="g8-fact-list"><div><span>Accepted constructions</span><strong>{companyMismatch ? "—" : snapshot.summary.data?.approved_count ?? "—"}</strong></div><div><span>Current source versions</span><strong>{companyMismatch ? "—" : snapshot.summary.data?.active_versions.length ?? "—"}</strong></div><div><span>Financial reporting authority</span><Badge>Unavailable</Badge></div></div>{snapshot.summary.error && <p className="g8-inline-error">{snapshot.summary.error}</p>}<button className="g8-panel-action" onClick={()=>navigate("data")}>Inspect retained sources<ArrowRight size={16}/></button></Panel>
      <Panel title="Operations & source health" aside={<Badge tone={ready?.status === "ready" ? "good" : "warning"}>{ready?.status === "ready" ? "Services ready" : "Not confirmed"}</Badge>}><div className="g8-panel-intro"><GlobeHemisphereWest size={27}/><div><h3>Operational telemetry is not connected</h3><p>Live network, facility and loss measurements require governed operational sources.</p></div></div><Signal title="Evidence storage" detail={ready ? readable(ready.evidence_store) : snapshot.readiness.error ?? "Checking readiness…"} tone={ready?.evidence_store === "ready" ? "good" : "warning"}/><Signal title="Workspace services" detail={ready ? `Database: ${readable(ready.database)} · Schema: ${readable(ready.schema)}` : "Current service state is not confirmed"} tone={ready?.status === "ready" ? "good" : "warning"}/><button className="g8-panel-action" onClick={refresh}>Check current readiness<ArrowClockwise size={16}/></button></Panel>
      <div ref={workRef}><Panel title="My work" aside={<Badge>{loading ? "Checking" : `${pending.length} loaded`}</Badge>}>{workTable}</Panel></div><Panel title="Recent findings" aside={<span className="g8-subtle">Source & review signals</span>}>{items.filter(item=>item.state === "PENDING" || item.severity===0).slice(0,5).map(item=><Signal key={`${item.kind}:${item.id}`} title={item.title} detail={item.reason} tone={item.severity===0 ? "bad" : "warning"} onClick={()=>void inspectWork(item)}/>)}{!pending.length && <Empty title={loading ? "Checking current signals…" : "No actionable findings in loaded queues"}>Findings appear when source validation or governed review provides evidence for them.</Empty>}<Signal title="Financial and operational analysis" detail="No certified financial or live operational conclusions are available yet."/></Panel></div></>}
      {view === "companies" && <Panel title="Company directory" aside={<Badge>{companies.length} available</Badge>}>{snapshot.graph.error ? <Empty title="Company directory unavailable">{snapshot.graph.error}</Empty> : !companies.length ? <Empty title={loading ? "Loading companies…" : "No accepted company identities"}>Company resources must be accepted before business context can be established. A data steward can manage proposals under System / Engineering.</Empty> : <div className="g8-company-list">{companies.map(item=><article key={item.resource_id}><Buildings size={28}/><div><h3>{item.display_name}</h3><p>{readable(item.object_type)} · {readable(item.evidence_class)}</p><Badge tone={tone(item.authority_state)}>{readable(item.authority_state)}</Badge></div><button className="g8-link" onClick={()=>{setCompanyId(item.resource_id);clearSelection();navigate("home");}}>Open workspace<ArrowRight size={16}/></button><button className="g8-icon" aria-label={`Inspect ${item.display_name}`} onClick={()=>void inspect(item)}><GraphIcon size={19}/></button></article>)}</div>}</Panel>}
      {view === "data" && <><div className="g8-actionbar"><button onClick={()=>openEngineering("intake")}><UploadSimple size={22}/><span>Evidence intake<small>Advanced retention & review</small></span></button><button onClick={()=>openEngineering("history")}><Tray size={22}/><span>Version history<small>Retrieve retained evidence</small></span></button></div><Panel title="Retained source versions" aside={<Badge tone={ready?.evidence_store === "ready" ? "good" : "warning"}>Storage {ready?.evidence_store ?? "unknown"}</Badge>}>{snapshot.evidence.error ? <Empty title="Evidence is unavailable">{snapshot.evidence.error}</Empty> : !scopedEvidence.length ? <Empty title={loading ? "Loading sources…" : "No retained sources in this view"}>Bring in a source through evidence intake. Retained data and review decisions will appear here.</Empty> : <div className="g8-table-scroll"><table><thead><tr><th>Source</th><th>Classification</th><th>Version state</th><th>Quality</th><th>Received</th></tr></thead><tbody>{scopedEvidence.map(item=><tr key={item.receipt_id}><td><button className="g8-link" onClick={()=>void inspectWork(items.find(work=>work.id===item.receipt_id)!)}>{item.filename}</button></td><td>{readable(item.source_class)}</td><td><Badge tone={tone(item.review_state)}>{item.review_state}</Badge><small className="g8-block">{item.is_current ? "Current version" : "Retained version"}</small></td><td>{item.reject_count ? `${item.reject_count} rejected rows` : readable(item.reconciliation_status)}</td><td>{date(item.ingested_at)}</td></tr>)}</tbody></table></div>}<div className="g8-panel-foot">Latest 50 receipts · Scope: {boundCompany?.display_name ?? "Sign-in scope"} · {principal.scope.period} · {principal.scope.currency}</div></Panel></>}
      {view === "ontology" && <Panel title="Business resources" aside={<Badge>{visibleResources.length} in view</Badge>}>{snapshot.graph.error ? <Empty title="Ontology unavailable">{snapshot.graph.error}</Empty> : !visibleResources.length ? <Empty title={loading ? "Loading business resources…" : "No accepted resources in this context"}>Accepted companies, accounts, relationships and other business resources will appear here with their authority and evidence.</Empty> : <div className="g8-table-scroll"><table><thead><tr><th>Resource</th><th>Type</th><th>Authority</th><th>Evidence</th><th>Effective</th></tr></thead><tbody>{visibleResources.map(item=><tr key={item.resource_id}><td><button className="g8-link" onClick={()=>void inspect(item)}>{item.display_name}</button></td><td>{readable(item.object_type)}</td><td><Badge tone={tone(item.authority_state)}>{item.authority_state}</Badge></td><td>{readable(item.evidence_class)}</td><td>{date(item.valid_from)}</td></tr>)}</tbody></table></div>}<div className="g8-panel-foot">Accepted business context · current effective versions<button className="g8-link" onClick={()=>openEngineering("ontology")}>Open governance tools<ArrowRight size={13}/></button></div></Panel>}
      <footer className="g8-footer"><span><ShieldCheck size={13}/> Governed evidence · explicit authority</span><span>{snapshot.context.data?.binding ? "Company binding available" : "No confirmed company binding"}</span></footer></>}
    </main>
    <aside className="g8-analyst" aria-label="NYX analyst context"><header><Image src="/brand/nyx-core.jpg" alt="NYX Core" width={52} height={52}/><div><h2>NYX</h2><small>Context & evidence</small></div><button className="g8-icon" aria-label="Close NYX context" onClick={()=>setRail(false)}><X size={17}/></button></header><div className="g8-analyst-body"><Badge>Guided context · analyst runtime unavailable</Badge><p className="g8-analyst-intro">Your enterprise context, with the evidence always in reach.</p><div className="g8-context-note"><small>WORKING CONTEXT</small><strong>{currentCompany?.display_name ?? "No company selected"}</strong><span>{currentCompany ? readable(currentCompany.evidence_class) : "Select an accepted company to explore its resources."}</span></div>{detailBusy && <p role="status">Loading evidence and impact…</p>}{detailError && <p className="g8-inline-error" role="alert">{detailError}</p>}
      {selected && <div className="g8-inspector"><p className="overline">RESOURCE CONTEXT</p><h3>{selected.resource.display_name}</h3><Badge tone={tone(selected.resource.authority_state)}>{selected.resource.authority_state}</Badge><p>{readable(selected.resource.object_type)} · {readable(selected.resource.evidence_class)}</p><dl><dt>Effective from</dt><dd>{date(selected.resource.valid_from)}</dd><dt>Retained versions</dt><dd>{selected.versions.length}</dd><dt>Visible dependents</dt><dd>{selected.dependents.length}</dd></dl>{selected.dependents.slice(0,8).map(item=><button className="g8-panel-action" key={item.resource_id} onClick={()=>void inspect({...selected.resource,resource_id:item.resource_id})}>{item.display_name}<ArrowRight size={13}/></button>)}<details><summary>Identity & version</summary><small>{selected.resource.resource_id}<br/>{selected.resource.version_id}</small></details><button className="g8-link" onClick={clearSelection}>Clear selection</button></div>}
      {work && <div className="g8-inspector"><p className="overline">WHY THIS NEEDS ATTENTION</p><h3>{work.title}</h3><Badge tone={tone(work.state)}>{work.state}</Badge><p>{work.reason}</p>{receipt && <><h3>Review eligibility</h3>{receipt.approval_blockers.length ? receipt.approval_blockers.map(reason=><p className="g8-inline-error" key={reason}>{reason}</p>) : <p>No approval blockers reported. Independent review remains required.</p>}<h3>Proposed object impact</h3><dl>{Object.entries(receipt.impact).map(([key,value])=><div key={key}><dt>{readable(key)}</dt><dd>{value}</dd></div>)}</dl><button className="g8-panel-action" onClick={()=>openEngineering("history",work.id)}>Open evidence & review<ArrowRight size={15}/></button></>}{proposal && <><ProposalImpact validation={proposal.validation}/><button className="g8-panel-action" onClick={()=>openEngineering("ontology")}>Open governed change review<ArrowRight size={15}/></button></>}<button className="g8-link" onClick={clearSelection}>Clear selection</button></div>}
      {!work && !selected && !detailBusy && <><h3>What needs attention?</h3><p className="g8-subtle">Open a work item to see its reason, source evidence and available review path.</p><button className="g8-panel-action" onClick={()=>{navigate("home");setWorkFilter("pending");}}>Review current work<ArrowRight size={15}/></button><button className="g8-panel-action" onClick={()=>navigate("data")}>Trace source evidence<ArrowRight size={15}/></button><button className="g8-panel-action" onClick={()=>navigate("companies")}>Explore companies<ArrowRight size={15}/></button></>}
      </div><footer><ShieldCheck size={17}/><p>Only governed context is shown here. Natural-language analysis is not connected.</p></footer></aside>
  </div>;
}
