"use client";
import {useEffect,useRef,useState} from "react";
import type {AnalysisPin,InvestigationResolutionOperation,InvestigationResolutionRequest,RetainedSourceException,SourceExceptionRequest} from "@finai/contracts";
import {metricRecord} from "./metric-observation-state";
import {assertMatchedException,assertOpenResource,assertResolutionException,assertResolutionOperation,laterJournalSnapshot,matchedExceptionRequest,openInvestigation,resolutionRequest,type OpenInvestigation} from "./investigation-resolution-state";
import PromotionReadiness from "./promotion-readiness";
import "./investigation-resolution-review.css";
type Props={token:string;companyId:string;operation:unknown;onInspectReference?:(pin:AnalysisPin,knownAt:string)=>void};
const errorText=(value:unknown)=>value instanceof Error?value.message:"Exact investigation evidence is unavailable.";
export default function InvestigationResolutionReview(props:Props){const operation=metricRecord(props.operation);return <ResolutionReview key={`${props.token}:${props.companyId}:${String(operation.operation_id)}:${String(operation.state)}`} {...props}/>;}
function ResolutionReview({token,companyId,operation,onInspectReference}:Props){
 const [context,setContext]=useState<OpenInvestigation|null>(null),[matched,setMatched]=useState<RetainedSourceException|null>(null),[snapshot,setSnapshot]=useState(""),[observationRequest,setObservationRequest]=useState<SourceExceptionRequest|null>(null),[snapshotRequest,setSnapshotRequest]=useState<string|null>(null);
 const [rationale,setRationale]=useState(""),[frozen,setFrozen]=useState<InvestigationResolutionRequest|null>(null),[result,setResult]=useState<InvestigationResolutionOperation|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[review,setReview]=useState(false);
 const pending=useRef<AbortController|null>(null);
 useEffect(()=>()=>{pending.current?.abort();pending.current=null;},[]);
 async function request(path:string,signal:AbortSignal,body?:unknown,post=false){const response=await fetch(`/api/ontology/${path}`,{method:body||post?"POST":"GET",headers:{Authorization:`Bearer ${token}`,...(body?{"Content-Type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{}),cache:"no-store",signal});if(!response.ok)throw Error(response.status===409?"The exact heads or evidence were refused. No resolution is established; refresh the investigation before continuing.":response.status===403?"You do not have permission for this investigation action.":"The retained investigation request could not be completed. Retry its unchanged inputs.");return response.json();}
 async function work(action:(signal:AbortSignal)=>Promise<void>){if(pending.current)return;const controller=new AbortController();pending.current=controller;const timer=setTimeout(()=>controller.abort(),25000);setBusy(true);setError("");try{await action(controller.signal);}catch(failure){if(pending.current===controller)setError(controller.signal.aborted?"The request timed out. Retry without changing the pinned inputs.":errorText(failure));}finally{clearTimeout(timer);if(pending.current===controller){pending.current=null;setBusy(false);}}}
 function load(){void work(async signal=>{setContext(null);setMatched(null);setResult(null);const op=metricRecord(operation),d=metricRecord(op.definition);if(typeof d.exception_run_id!=="string")throw Error("The original retained exception reference is unavailable.");const old=await request(`source-exceptions/${encodeURIComponent(d.exception_run_id)}`,signal);assertResolutionException(old,companyId,d.exception_run_id);
  let loaded:OpenInvestigation;
  if(d.operation==="RESOLVE"){loaded={finding:d.prior_finding as AnalysisPin,investigation:d.prior_investigation as AnalysisPin,exception:old,operationId:String(op.operation_id)};const newer=await request(`source-exceptions/${encodeURIComponent(String(d.matched_exception_run_id))}`,signal);assertMatchedException(newer,loaded,{company_id:companyId,invocation_id:old.source.invocation_id,journal_snapshot_at:newer.journal_observed_at,expected_reconciliation_receipt_hash:newer.reconciliation?.receipt_hash,coordinate:old.source.coordinate});assertResolutionOperation(operation,loaded,newer,{operationId:String(op.operation_id)});if(!signal.aborted){setContext(loaded);setMatched(newer);setResult(operation);}return;}
  loaded=openInvestigation(operation,old,companyId);const values=await Promise.all((["finding","investigation"] as const).map(kind=>request(`operator/resources/${loaded[kind].resource_id}?version_id=${loaded[kind].version_id}`,signal)));assertOpenResource(values[0],loaded.finding,"Finding",loaded);assertOpenResource(values[1],loaded.investigation,"Investigation",loaded);if(!signal.aborted)setContext(loaded);
 });}
 function match(){if(!context)return;void work(async signal=>{setMatched(null);setResult(null);const at=snapshotRequest??laterJournalSnapshot(snapshot,context.exception);setSnapshotRequest(at);let input=observationRequest;
  if(!input){const query=new URLSearchParams({company_id:companyId,snapshot_at:at});const value=await request(`company-journals/reconciliation/source/${context.exception.source.invocation_id}?${query}`,signal);input=matchedExceptionRequest(value,context,at);setObservationRequest(input);}
  const value=await request("source-exceptions",signal,input);assertMatchedException(value,context,input);if(!signal.aborted)setMatched(value);
 });}
 function propose(){if(!context||!matched)return;void work(async signal=>{const input=frozen??resolutionRequest(crypto.randomUUID(),context,matched,rationale);setFrozen(input);setResult(null);const value=await request("operations/investigation-resolutions",signal,input);assertResolutionOperation(value,context,matched,{request:input});if(!signal.aborted)setResult(value);});}
 function refresh(resume=false){if(!context||!matched||!result)return;const id=result.operation_id;void work(async signal=>{const value=await request(`operations/${id}${resume?"/resume":""}`,signal,undefined,resume);assertResolutionOperation(value,context,matched,{operationId:id});if(!signal.aborted)setResult(value);});}
 const resolution=metricRecord(metricRecord(operation).definition).operation==="RESOLVE";
 return <details className="investigation-resolution"><summary>{resolution?"Resolution evidence and exact publication":"Review a possible resolution"}</summary><p>A later matching journal is evidence for a reviewed proposal. It does not automatically close the finding or change accounting.</p><button disabled={busy||Boolean(frozen)} onClick={load}>Read exact investigation evidence</button>{busy&&<p role="status">Reading pinned investigation evidence…</p>}{error&&<p role="alert">{error}</p>}
  {context&&<><div className="resolution-evidence"><section><h4>Original unmatched observation</h4><p>{context.exception.source.sheet} · row {context.exception.source.row} · {context.exception.source.coordinate}</p><p>Journal snapshot {context.exception.journal_observed_at}</p>{onInspectReference&&<button onClick={()=>onInspectReference(context.exception.source.evidence,context.exception.source_known_at)}>Inspect original source evidence</button>}</section>{matched&&<section><h4>Later matched observation</h4><p>One accepted journal is retained for the same source cell.</p><p>Journal snapshot {matched.journal_observed_at}</p><p>Resolution requires independent review and exact publication.</p>{onInspectReference&&<button onClick={()=>onInspectReference(matched.source.evidence,matched.source_known_at)}>Inspect matched source evidence</button>}</section>}</div>
  {!resolution&&<><label>Later journal snapshot, with time zone<input value={snapshot} disabled={busy||Boolean(snapshotRequest)} onChange={e=>setSnapshot(e.target.value)} placeholder="YYYY-MM-DDTHH:mm:ss+04:00"/></label><div className="resolution-actions"><button disabled={busy||Boolean(frozen)} onClick={match}>{snapshotRequest?"Retry exact evidence read":"Check and retain matched evidence"}</button>{snapshotRequest&&!frozen&&<button disabled={busy} onClick={()=>{setSnapshotRequest(null);setObservationRequest(null);setMatched(null);setResult(null);}}>Choose another snapshot</button>}</div>{matched&&<><label>Reason for resolution<textarea rows={3} value={rationale} disabled={busy||Boolean(frozen)} maxLength={2000} onChange={e=>setRationale(e.target.value)}/></label><button disabled={busy||!frozen&&rationale.trim().length<10} onClick={propose}>{frozen?"Retry exact resolution proposal":"Propose reviewed resolution"}</button></>}</>}
  {result&&<section><h4>{result.state==="PUBLISHED"?"Resolved pair publication confirmed":result.state==="PUBLICATION_UNAVAILABLE"?"Resolved publication unavailable":result.state==="REJECTED"?"Resolution proposal rejected":"Resolution proposed; investigation remains open"}</h4><p>Retained proposal rationale: {result.frozen_rationale}</p><div className="resolution-actions">{result.proposal&&<button onClick={()=>setReview(v=>!v)}>{review?"Collapse review":"Open independent review"}</button>}<button disabled={busy} onClick={()=>refresh()}>Read review and publication state</button>{result.state==="PREPARED"&&<button disabled={busy} onClick={()=>refresh(true)}>Resume proposal submission</button>}</div>{review&&result.proposal&&<PromotionReadiness key={result.prepared_proposal_id} token={token} proposalId={result.prepared_proposal_id} onDecision={()=>refresh()}/>}</section>}
  <details><summary>Advanced · original and matched evidence, exact heads and resolution</summary><pre>{JSON.stringify({finding:context.finding,investigation:context.investigation,original:context.exception,matched,observationRequest,request:frozen,result},null,2)}</pre></details></>}
 </details>;
}
