import type {AnalysisPin,InvestigationResolutionOperation,InvestigationResolutionRequest,RetainedSourceException,SourceExceptionRequest} from "@finai/contracts";
import {metricCanonical,metricPin,metricRecord,sameMetricPin,referenceOnly} from "./metric-observation-state";
import {assertInvestigation} from "./source-exception-state";
import {restorationInstant} from "./definition-restoration-time";
const hash=/^[a-f0-9]{64}$/,runId=/^fcr_[a-f0-9]{64}$/,uuid=/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i;
function refuse():never{throw Error("Resolution evidence does not match the exact published investigation, company and source snapshot.");}
export const exceptionEvidence=(value:RetainedSourceException)=>Object.fromEntries(Object.entries(value).filter(([key])=>!["run_id","scope","calculation_runtime","read_permissions"].includes(key)));
const sameTime=(a:unknown,b:unknown)=>Boolean(restorationInstant(a)&&restorationInstant(a)===restorationInstant(b));
export type OpenInvestigation={finding:AnalysisPin;investigation:AnalysisPin;exception:RetainedSourceException;operationId:string};
export function assertResolutionException(value:unknown,companyId:string,expectedId:string):asserts value is RetainedSourceException {
 const v=value as RetainedSourceException;
 if(!v||v.contract!=="source-reconciliation-exception/1"||v.detector!=="source-reconciliation-exceptions/1"||v.calculation_runtime!==v.detector||v.run_id!==expectedId||!runId.test(v.run_id)||!hash.test(v.receipt_hash)||!metricPin(v.company)||v.company.resource_id!==companyId||metricRecord(v.scope).legal_entity_id!==companyId||!metricPin(v.binding)||!metricPin(v.source_function)||!restorationInstant(v.source_valid_at)||!restorationInstant(v.source_known_at)||!restorationInstant(v.journal_observed_at)||!hash.test(v.reconciliation?.receipt_hash)||!["UNAVAILABLE","PARTIAL","RECONCILED"].includes(v.reconciliation.status)||!v.source||!uuid.test(v.source.invocation_id)||!hash.test(v.source.invocation_receipt_hash)||!hash.test(v.source.source_receipt_hash)||!hash.test(v.source.sha256)||!metricPin(v.source.evidence)||typeof v.source.coordinate!=="string"||typeof v.source.sheet!=="string"||v.source.coordinate.slice(0,v.source.coordinate.lastIndexOf("!"))!==v.source.sheet||!Number.isSafeInteger(v.source.row)||v.source.row<1||String(v.source.row)!==/[0-9]+$/.exec(v.source.coordinate)?.[0]||!/^(doc|ir)_[a-f0-9]{64}$/.test(v.source.document_id)||!Array.isArray(v.context_versions)||v.context_versions.length!==7||!v.context_versions.every(metricPin)||new Set(v.context_versions.map(p=>p.resource_id)).size!==7||!v.selection||Object.keys(v.selection).length!==7||Object.values(v.selection).some(p=>!v.context_versions.some(c=>c.resource_id===p.resource_id&&c.version_id===p.version_id))||v.financial_impact!==null||v.materiality!=="UNASSESSED"||v.automatic_resolution!==false||v.current_use_authorized!==false||v.business_effect_authorized!==false||v.exclusion_reason!==null||!Array.isArray(v.matched_journals))refuse();
 if(v.state==="UNMATCHED_AT_SNAPSHOT"?(v.finding_eligible!==true||v.matched_journals.length!==0):v.state!=="MATCHED_AT_SNAPSHOT"||v.finding_eligible!==false||v.matched_journals.length!==1||v.matched_journals.some(p=>!uuid.test(p.resource_id)||!uuid.test(p.version_id)))refuse();
}
export function openInvestigation(operation:unknown,exception:unknown,companyId:string):OpenInvestigation {
 const o=metricRecord(operation),definition=metricRecord(o.definition);if(definition.operation!==undefined&&definition.operation!=="CREATE"||typeof definition.exception_run_id!=="string")refuse();
 assertResolutionException(exception,companyId,definition.exception_run_id);if(exception.state!=="UNMATCHED_AT_SNAPSHOT")refuse();assertInvestigation(operation,exception,{operationId:String(o.operation_id)});
 if(operation.state!=="PUBLISHED"||!operation.publication)refuse();return {finding:referenceOnly(operation.publication.finding),investigation:referenceOnly(operation.publication.investigation),exception,operationId:operation.operation_id};
}
export function assertOpenResource(value:unknown,pin:AnalysisPin,kind:"Finding"|"Investigation",context:OpenInvestigation):void {
 const envelope=metricRecord(value),resource=metricRecord(envelope.resource),d=metricRecord(metricRecord(resource.attributes).definition);
 if(envelope.selection_mode!=="EXACT_VERSION"||envelope.current_use_authorized!==false||!sameMetricPin(resource,pin)||resource.object_type!==kind||resource.authority_state!=="APPROVED"||d.contract!==(kind==="Finding"?"source-finding/1":"source-investigation/1")||d.state!=="OPEN"||d.exception_run_id!==context.exception.run_id||d.exception_receipt_hash!==context.exception.receipt_hash||d.automatic_resolution!==false)refuse();
 if(kind==="Finding"&&(d.financial_impact!==null||d.materiality!=="UNASSESSED"||metricCanonical(d.evidence)!==metricCanonical(exceptionEvidence(context.exception))))refuse();
}
export function laterJournalSnapshot(value:string,old:RetainedSourceException):string {const at=restorationInstant(value),before=restorationInstant(old.journal_observed_at);if(!at||!before||at<=before)throw Error("Choose an explicit journal snapshot later than the unmatched observation, including its time zone.");return at;}
export function matchedExceptionRequest(value:unknown,context:OpenInvestigation,snapshot:string):SourceExceptionRequest {
 const envelope=metricRecord(value),r=metricRecord(envelope.reconciliation),old=context.exception,accepted=Array.isArray(r.accepted)?r.accepted.map(metricRecord):[];
 if(r.contract!=="source-journal-movement-reconciliation/1"||r.basis!=="EXACT_SOURCE_MATCHED_CANONICAL_JOURNALS"||!hash.test(String(r.receipt_hash))||!sameTime(r.snapshot_at,snapshot)||metricCanonical(r.selection)!==metricCanonical(old.selection)||!sameMetricPin(r.binding,old.binding)||r.source_receipt_hash!==old.source.source_receipt_hash||r.source_sha256!==old.source.sha256||r.current_use_authorized!==false||r.business_effect_authorized!==false||accepted.filter(row=>row.source_coordinate===old.source.coordinate).length!==1||!Array.isArray(r.missing_coordinates)||r.missing_coordinates.includes(old.source.coordinate)||!Array.isArray(r.excluded_rows)||r.excluded_rows.some(row=>metricRecord(row).coordinate===old.source.coordinate))throw Error("The server has not established a compatible accepted journal for this source cell at the selected snapshot.");
 return {company_id:old.company.resource_id,invocation_id:old.source.invocation_id,journal_snapshot_at:snapshot,expected_reconciliation_receipt_hash:String(r.receipt_hash),coordinate:old.source.coordinate};
}
export function assertMatchedException(value:unknown,context:OpenInvestigation,request:SourceExceptionRequest):asserts value is RetainedSourceException {
 const v=metricRecord(value);assertResolutionException(value,context.exception.company.resource_id,String(v.run_id));const old=context.exception;
 if(value.state!=="MATCHED_AT_SNAPSHOT"||value.run_id===old.run_id||!sameTime(value.journal_observed_at,request.journal_snapshot_at)||value.reconciliation.receipt_hash!==request.expected_reconciliation_receipt_hash)refuse();laterJournalSnapshot(value.journal_observed_at,old);
 for(const key of ["scope","company","selection","context_versions","binding","source_function","source"] as const){const a=key==="context_versions"?[...value[key]].sort((x,y)=>x.resource_id.localeCompare(y.resource_id)):value[key],b=key==="context_versions"?[...old[key]].sort((x,y)=>x.resource_id.localeCompare(y.resource_id)):old[key];if(metricCanonical(a)!==metricCanonical(b))refuse();}
 if(!sameTime(value.source_valid_at,old.source_valid_at)||!sameTime(value.source_known_at,old.source_known_at))refuse();
}
export function resolutionRequest(id:string,context:OpenInvestigation,matched:RetainedSourceException,rationale:string):InvestigationResolutionRequest {
 if(!uuid.test(id)||matched.state!=="MATCHED_AT_SNAPSHOT"||rationale.trim().length<10||rationale.trim().length>2000)throw Error("Retain compatible matched evidence and explain the resolution for independent review.");return {request_id:id,finding:referenceOnly(context.finding),investigation:referenceOnly(context.investigation),matched_exception_run_id:matched.run_id,rationale:rationale.trim()};
}
export function assertResolutionOperation(value:unknown,context:OpenInvestigation,matched:RetainedSourceException,expected:{request?:InvestigationResolutionRequest;operationId?:string}):asserts value is InvestigationResolutionOperation {
 const v=value as InvestigationResolutionOperation,d=metricRecord(v?.definition),p=metricRecord(metricRecord(v?.proposal).proposal);
 if(!v||!/^opa_[a-f0-9]{64}$/.test(v.operation_id)||expected.operationId&&v.operation_id!==expected.operationId||d.version!=="ontology-action/1"||d.kind!=="SOURCE_EXCEPTION_INVESTIGATION"||d.operation!=="RESOLVE"||d.company_id!==context.exception.company.resource_id||d.exception_run_id!==context.exception.run_id||d.matched_exception_run_id!==matched.run_id||!sameMetricPin(d.prior_finding,context.finding)||!sameMetricPin(d.prior_investigation,context.investigation)||v.finding_id!==context.finding.resource_id||v.investigation_id!==context.investigation.resource_id||v.current_use_authorized!==false||v.business_effect_authorized!==false||!["PREPARED","PENDING_REVIEW","REJECTED","PUBLISHED","PUBLICATION_UNAVAILABLE"].includes(v.state)||!uuid.test(v.prepared_proposal_id))refuse();
 if(expected.request&&metricCanonical(v.intent_request)!==metricCanonical(expected.request))refuse();
 if(v.state!=="PREPARED"&&!v.proposal)refuse();
 if(v.proposal){if(p.proposal_id!==v.prepared_proposal_id||p.rationale!==v.frozen_rationale||!Array.isArray(p.mutations)||p.mutations.length!==2)refuse();for(const kind of ["Finding","Investigation"]){const rows=p.mutations.map(metricRecord).filter(m=>m.object_type===kind),prior=kind==="Finding"?context.finding:context.investigation;if(rows.length!==1)refuse();const m=rows[0],definition=metricRecord(metricRecord(m.attributes).definition),proof=metricRecord(definition.resolution);if(m.resource_id!==prior.resource_id||m.expected_version_id!==prior.version_id||definition.contract!==(kind==="Finding"?"source-finding/2":"source-investigation/2")||definition.exception_run_id!==context.exception.run_id||definition.exception_receipt_hash!==context.exception.receipt_hash||definition.state!=="RESOLVED"||definition.automatic_resolution!==false||!sameMetricPin(proof.prior_finding,context.finding)||!sameMetricPin(proof.prior_investigation,context.investigation)||proof.unmatched_exception_run_id!==context.exception.run_id||proof.matched_exception_run_id!==matched.run_id||metricCanonical(proof.unmatched_evidence)!==metricCanonical(exceptionEvidence(context.exception))||metricCanonical(proof.matched_evidence)!==metricCanonical(exceptionEvidence(matched)))refuse();if(kind==="Finding"&&(metricCanonical(definition.evidence)!==metricCanonical(exceptionEvidence(context.exception))||definition.financial_impact!==null||definition.materiality!=="UNASSESSED"))refuse();}}
 if(v.state==="PUBLISHED"){if(metricRecord(v.proposal).decision!=="APPROVED"||!v.publication)refuse();for(const kind of ["finding","investigation"] as const){const pin=v.publication[kind];if(!metricPin(pin)||pin.resource_id!==context[kind].resource_id||pin.version_id===context[kind].version_id)refuse();}}else if(v.publication!==null)refuse();
}
