"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import type {AnalysisPin,AnalysisProjection,FinancialMetricResult,MetricCatalogItem,MetricObservation,MetricObservationRequest} from "@finai/contracts";
import {acceptedMetricFunctionRequest,assertAcceptedMetricFunction,assertMetricCatalog,assertMetricCompany,assertMetricObservation,completedMetricSource,financialFunctionMatches,metricObservationRequest,parseSavedMetricObservation,savedMetricObservation,savedFinancialMeasurementSource,parseFinancialMeasurementSource,type SavedFinancialMeasurementSource,type AcceptedMetricFunctionRequest,type FinancialFunctionChoice,type MetricSource,type SavedMetricObservation} from "./metric-observation-state";
import "./metric-observation-review.css";

type Props={token:string;companyId:string;invocation:unknown;onInspect?:(pin:AnalysisPin,knownAt:string)=>void;onSource?:()=>void;onSaved?:()=>void};
const stamp=(value:string)=>new Date(value).toLocaleString();
const message=(error:unknown)=>error instanceof Error?error.message:"The measurement is unavailable.";
async function responseBody(response:Response){if(!response.ok)throw Error(response.status===403?"You do not have access to this measurement.":response.status===409?"The definition or source revision was refused. The previous result is withheld.":"The measurement request could not be completed. Retry the exact request.");return response.json();}

export default function MetricObservationReview(props:Props){
 const source=useMemo(()=>{try{const result=completedMetricSource(props.invocation);assertMetricCompany(result,props.companyId);return result;}catch{return null;}},[props.invocation,props.companyId]);
 if(!source)return <p className="metric-observation-note">Measurement retention requires a completed shared Function for the selected company with exact source provenance.</p>;
 return <ObservationReview key={`${props.token}:${props.companyId}:${source.invocationId}:${source.receiptHash}`} {...props} source={source}/>;
}
function ObservationReview({token,companyId,source,onInspect,onSource,onSaved}:Props&{source:MetricSource}){
 const [items,setItems]=useState<MetricCatalogItem[]>([]),[after,setAfter]=useState<string|null>(null),[next,setNext]=useState<string|null>(null),[catalogBusy,setCatalogBusy]=useState(true),[catalogError,setCatalogError]=useState(""),[catalogRetry,setCatalogRetry]=useState(0),[selected,setSelected]=useState("");
 const [frozen,setFrozen]=useState<{request:MetricObservationRequest;item:MetricCatalogItem}|null>(null),[observation,setObservation]=useState<MetricObservation|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [storageKey,setStorageKey]=useState(""),[saved,setSaved]=useState<SavedMetricObservation|null>(null),[saveError,setSaveError]=useState("");
 const pending=useRef<AbortController|null>(null);
 useEffect(()=>()=>{pending.current?.abort();pending.current=null;},[]);
 useEffect(()=>{let disposed=false;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);
  async function load(){setCatalogBusy(true);setCatalogError("");try{const params=new URLSearchParams({function_resource_id:source.function.resource_id,function_version_id:source.function.version_id,function_content_hash:source.function.content_hash});if(after)params.set("after_resource_id",after);
   const value=await responseBody(await fetch(`/api/ontology/metrics?${params}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store",signal:controller.signal}));assertMetricCatalog(value,source,companyId,after);
   if(!disposed){setItems(previous=>after?[...previous.filter(p=>!value.items.some(i=>i.metric.resource_id===p.metric.resource_id)),...value.items]:value.items);setNext(value.next_cursor);}
  }catch(failure){if(!disposed)setCatalogError(controller.signal.aborted?"Measurement discovery timed out. Retry this page.":message(failure));}finally{clearTimeout(timer);if(!disposed)setCatalogBusy(false);}}
  void load();return()=>{disposed=true;controller.abort();clearTimeout(timer);};
 },[token,companyId,source,after,catalogRetry]);
 useEffect(()=>{let disposed=false;void crypto.subtle.digest("SHA-256",new TextEncoder().encode(token)).then(bytes=>{if(disposed)return;const identity=Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join(""),key=`g8:metric-observation:1:${identity}:${companyId}:${source.invocationId}:${source.receiptHash}`;setStorageKey(key);try{const raw=localStorage.getItem(key);if(raw){const value=parseSavedMetricObservation(raw,source,companyId);setSaved(value);if(!value)setSaveError("The saved measurement reference does not match this source.");}}catch{setSaveError("Measurement reference storage is unavailable.");}}).catch(()=>{if(!disposed)setSaveError("Measurement reference storage is unavailable.");});return()=>{disposed=true;};},[token,companyId,source]);
 const choice=items.find(item=>`${item.metric.resource_id}:${item.metric.version_id}:${item.metric.content_hash}`===selected);
 async function retain(){if(busy)return;const target=frozen??(choice?{request:metricObservationRequest(choice,source),item:choice}:null);if(!target)return;setFrozen(target);await readObservation(target.request,target.item);}
 async function readObservation(request:MetricObservationRequest,expected:MetricCatalogItem|SavedMetricObservation){
  if(pending.current)return;const controller=new AbortController();pending.current=controller;const timer=setTimeout(()=>controller.abort(),25000);setBusy(true);setObservation(null);setError("");setNotice("");
  try{const historical="runId" in expected;const response=await fetch(historical?`/api/ontology/metrics/observations/${expected.runId}`:"/api/ontology/metrics/observations",{method:historical?"GET":"POST",headers:{Authorization:`Bearer ${token}`,...(!historical?{"Content-Type":"application/json"}:{})},...(!historical?{body:JSON.stringify(request)}:{}),cache:"no-store",signal:controller.signal});const value=await responseBody(response);assertMetricObservation(value,source,request,companyId,expected);if(pending.current!==controller)return;setObservation(value);setNotice(historical?"Exact historical measurement reopened.":"Measurement retained from the completed Function result.");
  }catch(failure){if(pending.current===controller)setError(controller.signal.aborted?"The request timed out. Retry without changing its pinned inputs.":message(failure));}finally{clearTimeout(timer);if(pending.current===controller){pending.current=null;setBusy(false);}}
 }
 function save(){if(!observation||!storageKey)return;const request=frozen&&observation.metric.resource_id===frozen.request.metric.resource_id?frozen.request:saved?.request;if(!request)return;try{const reference=savedMetricObservation(observation,request);localStorage.setItem(storageKey,JSON.stringify(reference));setSaved(reference);onSaved?.();setSaveError("");setNotice("Historical reference saved on this device. Values were not copied.");}catch{setSaveError("The historical reference could not be saved.");}}
 return <section className="metric-observation-review" aria-label="Retained measurements" aria-busy={busy}>
  <header><h4>Retained measurements</h4><span>Evidence only</span></header>
  <p className="metric-observation-note">Choose an approved measurement for this completed analysis. Retention records the server result and its exact evidence.</p>
  <div className="metric-observation-actions"><label>Measurement<select value={selected} disabled={busy||Boolean(frozen)} onChange={e=>{setSelected(e.target.value);setObservation(null);setError("");setNotice("");}}><option value="">Choose a measurement</option>{items.map(item=><option key={item.metric.resource_id} value={`${item.metric.resource_id}:${item.metric.version_id}:${item.metric.content_hash}`}>{item.display_name}</option>)}</select></label>
   <button disabled={busy||!frozen&&!choice} onClick={()=>void retain()}>{frozen?"Retry exact retention":"Retain measurement"}</button>
   {frozen&&<button disabled={busy} onClick={()=>{setFrozen(null);setObservation(null);setError("");setNotice("");}}>Choose another measurement</button>}
   {saved&&<button disabled={busy} onClick={()=>{setFrozen(null);void readObservation(saved.request,saved);}}>Reopen saved measurement</button>}
  </div>
  {catalogBusy&&<p role="status">Loading available measurements…</p>}{catalogError&&<p role="alert">{catalogError} <button onClick={()=>setCatalogRetry(v=>v+1)}>Retry discovery</button></p>}
  {!catalogBusy&&!catalogError&&!items.length&&<p>No approved measurement was returned for this exact analysis revision{next?" on this page":""}.</p>}{next&&<button disabled={catalogBusy||busy} onClick={()=>setAfter(next)}>Load more measurements</button>}
  {selected&&!choice&&!frozen&&<p role="alert">The selected definition is no longer in this collection. Choose explicitly.</p>}
  {busy&&<p role="status">Resolving the exact retained measurement…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{saveError&&<p role="status">{saveError}</p>}
  {observation&&<><dl className="metric-observation-value"><div><dt>{frozen?.item.display_name??"Retained measurement"}</dt><dd>{observation.observation.state==="VALUE"?observation.observation.value:"Unavailable"} <small>{observation.observation.unit.kind==="COUNT"?"objects":"in the defined currency"}</small></dd></div><div><dt>Coverage</dt><dd>{observation.observation.coverage==="COMPLETE"?"Complete selected result":"Partial selected result"}</dd></div></dl>
   <p className="metric-observation-note">Source valid {stamp(observation.observation.valid_at)} · Source known {stamp(observation.observation.known_at)} · Definition observed {stamp(observation.definition_snapshot.known_at)}. Values are not additive across observations.</p>
   <div className="metric-observation-actions"><button disabled={!storageKey} onClick={save}>Save historical reference</button>{onSource&&<button onClick={onSource}>Open source review</button>}</div>
   <details><summary>Source contributors · {observation.observation.contributors.length}</summary>{onInspect?<ol className="metric-observation-contributors">{observation.observation.contributors.map((pin,index)=><li key={pin.resource_id}><button onClick={()=>onInspect(pin,source.knownAt)}>Inspect contributor {index+1}</button></li>)}</ol>:<p>Open the source review to inspect the contributing evidence.</p>}</details>
   <details><summary>Advanced · exact definition, request and retained result</summary><pre>{JSON.stringify({request:frozen?.request??saved?.request,result:observation},null,2)}</pre></details>
  </>}
 </section>;
}

export function AcceptedMovementMetricReview({token,companyId,metrics,projection,onSource}:{token:string;companyId:string;metrics:FinancialMetricResult;projection:AnalysisProjection;onSource:()=>void}){
 return <AcceptedReview key={`${token}:${companyId}:${metrics.invocation_id}:${metrics.result_sha256}:${projection.descriptor_sha256}`} token={token} companyId={companyId} metrics={metrics} projection={projection} onSource={onSource}/>;
}
function AcceptedReview({token,companyId,metrics,projection,onSource}:{token:string;companyId:string;metrics:FinancialMetricResult;projection:AnalysisProjection;onSource:()=>void}){
 const [items,setItems]=useState<FinancialFunctionChoice[]>([]),[after,setAfter]=useState<string|null>(null),[next,setNext]=useState<string|null>(null),[catalogBusy,setCatalogBusy]=useState(true),[catalogError,setCatalogError]=useState(""),[retry,setRetry]=useState(0),[selected,setSelected]=useState("");
 const [frozen,setFrozen]=useState<{request:AcceptedMetricFunctionRequest;fn:AnalysisPin}|null>(null),[invocation,setInvocation]=useState<unknown>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const pending=useRef<AbortController|null>(null),company=projection.descriptor.company;
 const [savedSource,setSavedSource]=useState<SavedFinancialMeasurementSource|null>(null),[storageKey,setStorageKey]=useState(""),[storageError,setStorageError]=useState("");
 useEffect(()=>()=>{pending.current?.abort();pending.current=null;},[]);
 useEffect(()=>{const controller=new AbortController();let disposed=false;const timer=setTimeout(()=>controller.abort(),25000);
  async function load(){setCatalogBusy(true);setCatalogError("");try{const value=await responseBody(await fetch(`/api/ontology/functions${after?`?after_resource_id=${encodeURIComponent(after)}`:""}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store",signal:controller.signal}));if(value.purpose!=="EVIDENCE_ANALYSIS_ONLY"||!Array.isArray(value.items)||value.items.length>50||value.next_cursor!==null&&(typeof value.next_cursor!=="string"||!/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i.test(value.next_cursor)||value.next_cursor===after))throw Error("Approved financial analyses could not be verified.");const matches:FinancialFunctionChoice[]=value.items.filter((item:FinancialFunctionChoice)=>financialFunctionMatches(item,company));if(!disposed){setItems(previous=>after?[...previous.filter(p=>!matches.some(i=>i.reference.resource_id===p.reference.resource_id)),...matches]:matches);setNext(value.next_cursor);}}
   catch(failure){if(!disposed)setCatalogError(controller.signal.aborted?"Approved analysis discovery timed out.":message(failure));}finally{clearTimeout(timer);if(!disposed)setCatalogBusy(false);}}
  void load();return()=>{disposed=true;controller.abort();clearTimeout(timer);};
 },[token,company,after,retry]);
 useEffect(()=>{let disposed=false;void crypto.subtle.digest("SHA-256",new TextEncoder().encode(token)).then(bytes=>{if(disposed)return;const identity=Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join(""),key=`g8:financial-measurement-source:1:${identity}:${companyId}:${metrics.invocation_id}:${metrics.result_sha256}`;setStorageKey(key);try{const raw=localStorage.getItem(key);if(raw){const value=parseFinancialMeasurementSource(raw,metrics,company,projection.descriptor.valid_at,projection.descriptor.known_at);setSavedSource(value);if(!value)setStorageError("The saved analysis reference differs from this financial source.");}}catch{setStorageError("Analysis reference storage is unavailable.");}}).catch(()=>{if(!disposed)setStorageError("Analysis reference storage is unavailable.");});return()=>{disposed=true;};},[token,companyId,metrics,company,projection]);
 function saveSource(){if(!invocation||!frozen||!storageKey)throw Error("The source analysis reference could not be saved.");const reference=savedFinancialMeasurementSource(completedMetricSource(invocation),frozen.request);localStorage.setItem(storageKey,JSON.stringify(reference));setSavedSource(reference);setStorageError("");}
 async function reopen(){if(!savedSource||pending.current)return;const reference=savedSource,controller=new AbortController();pending.current=controller;const timer=setTimeout(()=>controller.abort(),25000);setBusy(true);setError("");setInvocation(null);try{const value=await responseBody(await fetch(`/api/ontology/functions/invocations/${reference.request.request_id}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store",signal:controller.signal}));const source=assertAcceptedMetricFunction(value,reference.request,reference.function);if(source.receiptHash!==reference.receiptHash||source.runId!==reference.runId||source.planHash!==reference.planHash)throw Error("The saved analysis revision changed.");if(pending.current===controller){setFrozen({request:reference.request,fn:reference.function});setInvocation(value);}}catch(failure){if(pending.current===controller)setError(controller.signal.aborted?"Historical analysis read timed out. Retry the saved reference.":message(failure));}finally{clearTimeout(timer);if(pending.current===controller){pending.current=null;setBusy(false);}}}
 const choice=items.find(item=>`${item.reference.resource_id}:${item.reference.version_id}:${item.content_hash}`===selected);
 async function execute(){if(pending.current||!choice&&!frozen)return;let target=frozen;try{if(!target&&choice)target={request:acceptedMetricFunctionRequest(crypto.randomUUID(),choice,metrics,company,projection.descriptor.valid_at,projection.descriptor.known_at),fn:{...choice.reference,content_hash:choice.content_hash}};if(!target)return;setFrozen(target);}catch(failure){setError(message(failure));return;}
  const controller=new AbortController();pending.current=controller;const timer=setTimeout(()=>controller.abort(),25000);setBusy(true);setError("");setInvocation(null);
  try{const value=await responseBody(await fetch("/api/ontology/functions/invocations",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(target.request),cache:"no-store",signal:controller.signal}));assertAcceptedMetricFunction(value,target.request,target.fn);if(pending.current===controller)setInvocation(value);}catch(failure){if(pending.current===controller)setError(controller.signal.aborted?"The analysis timed out. Retry its unchanged request.":message(failure));}finally{clearTimeout(timer);if(pending.current===controller){pending.current=null;setBusy(false);}}
 }
 return <section className="metric-observation-review" aria-label="Measure accepted movements"><header><h4>Measure accepted movements</h4><span>Explicit analysis</span></header><p className="metric-observation-note">Run an approved analysis against this fixed source and journal snapshot, then choose a measurement to retain.</p>
  <div className="metric-observation-actions"><label>Approved analysis<select value={selected} disabled={busy||Boolean(frozen)} onChange={e=>setSelected(e.target.value)}><option value="">Choose an approved analysis</option>{items.map(item=><option key={item.reference.resource_id} value={`${item.reference.resource_id}:${item.reference.version_id}:${item.content_hash}`}>{item.display_name}</option>)}</select></label><button disabled={busy||!choice&&!frozen} onClick={()=>void execute()}>{frozen?"Retry exact analysis":"Run approved analysis"}</button>{frozen&&<button disabled={busy} onClick={()=>{setFrozen(null);setInvocation(null);setError("");}}>Choose another analysis</button>}</div>
  {catalogBusy&&<p role="status">Loading approved analyses…</p>}{catalogError&&<p role="alert">{catalogError} <button onClick={()=>setRetry(v=>v+1)}>Retry discovery</button></p>}{!catalogBusy&&!catalogError&&!items.length&&<p>No approved movement analysis was returned for this exact company revision{next?" on this page":""}.</p>}{next&&<button disabled={catalogBusy||busy} onClick={()=>setAfter(next)}>Load more analyses</button>}{busy&&<p role="status">Executing the pinned shared analysis…</p>}{error&&<p role="alert">{error}</p>}
  {savedSource&&<button disabled={busy} onClick={()=>void reopen()}>Reopen saved analysis for measurements</button>}{storageError&&<p role="status">{storageError}</p>}
  {invocation!==null&&<MetricObservationReview token={token} companyId={companyId} invocation={invocation} onSource={onSource} onSaved={saveSource}/>}
  {frozen&&<details><summary>Advanced · exact financial analysis request</summary><pre>{JSON.stringify(frozen,null,2)}</pre></details>}
 </section>;
}
