import type {AcceptedMovementFunctionInvocation,AnalysisPin,FinancialMetricResult,MetricCatalog,MetricCatalogItem,MetricDefinition,MetricObservation,MetricObservationRequest} from "@finai/contracts";
import {restorationInstant} from "./definition-restoration-time";

const uuid=/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i,hash=/^[a-f0-9]{64}$/,run=/^fcr_[a-f0-9]{64}$/;
export const metricRecord=(value:unknown):Record<string,unknown>=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
export function metricPin(value:unknown):value is AnalysisPin{const v=metricRecord(value);return typeof v.resource_id==="string"&&uuid.test(v.resource_id)&&typeof v.version_id==="string"&&uuid.test(v.version_id)&&typeof v.content_hash==="string"&&hash.test(v.content_hash);}
export function sameMetricPin(a:unknown,b:unknown):boolean{return metricPin(a)&&metricPin(b)&&a.resource_id===b.resource_id&&a.version_id===b.version_id&&a.content_hash===b.content_hash;}
export function metricCanonical(value:unknown):string {if(Array.isArray(value))return `[${value.map(metricCanonical).join(",")}]`;if(value&&typeof value==="object")return `{${Object.entries(value).sort(([a],[b])=>a<b?-1:a>b?1:0).map(([k,v])=>`${JSON.stringify(k)}:${metricCanonical(v)}`).join(",")}}`;return JSON.stringify(value);}
const time=(a:unknown,b:unknown)=>Boolean(restorationInstant(a)&&restorationInstant(a)===restorationInstant(b));
function fail(message:string):never{throw Error(message);}
export type MetricSource={companyId:string;invocationId:string;receiptHash:string;runId:string;planHash:string;function:AnalysisPin;validAt:string;knownAt:string;output:Record<string,unknown>};
export function completedMetricSource(value:unknown):MetricSource {
 const v=metricRecord(value),receipt=metricRecord(v.receipt),output=metricRecord(v.output),request=metricRecord(receipt.request),query=metricRecord(output.query);
 if(v.status!=="SUCCEEDED"||typeof v.invocation_id!=="string"||!uuid.test(v.invocation_id)||typeof v.receipt_hash!=="string"||!hash.test(v.receipt_hash)||!metricPin(output.function)||!sameMetricPin(output.function,receipt.function)||output.contract!=="function-result/1"||output.calculation_runtime!=="shared-functions/1"||typeof output.run_id!=="string"||!run.test(output.run_id)||output.run_id!==receipt.run_id||typeof receipt.plan_hash!=="string"||!hash.test(receipt.plan_hash)||output.invocation_plan_hash!==receipt.plan_hash||request.request_id!==v.invocation_id||output.invocation_request_id!==v.invocation_id||![v,receipt,output].every(x=>x.current_use_authorized===false&&x.business_effect_authorized===false)||!time(query.valid_at,request.valid_at)||!time(query.known_at,request.known_at))fail("A completed, exact shared Function result is required before retaining a measurement.");
 const scope=metricRecord(output.scope);if(typeof scope.legal_entity_id!=="string"||!uuid.test(scope.legal_entity_id)||metricCanonical(scope)!==metricCanonical(receipt.exact_scope))fail("The completed analysis company scope could not be verified.");
 return {companyId:scope.legal_entity_id,invocationId:v.invocation_id,receiptHash:v.receipt_hash,runId:output.run_id,planHash:receipt.plan_hash,function:output.function,validAt:String(query.valid_at),knownAt:String(query.known_at),output};
}
export function assertMetricDefinition(value:unknown):asserts value is MetricDefinition {
 const d=value as MetricDefinition;
 if(!d||d.contract!=="metric-definition/1"||d.aggregation!=="non_additive"||typeof d.grain!=="string"||!d.grain.length||d.grain.length>128||!Array.isArray(d.dimensions)||d.dimensions.length>20||d.dimensions.some(x=>typeof x!=="string")||new Set(d.dimensions).size!==d.dimensions.length)fail("The measurement definition is unsupported.");
 if(d.unit?.kind==="COUNT"?d.unit.symbol!=="objects":d.unit?.kind!=="CURRENCY"||!metricPin(d.unit.reference))fail("The measurement unit lacks an exact definition.");
 if(d.selector?.kind==="OBJECT_COUNT"?(d.unit.kind!=="COUNT"||d.grain!=="OBJECT_SET_SNAPSHOT"||d.dimensions.length!==0):d.selector?.kind!=="MEASURE"||!/^[a-zA-Z][a-zA-Z0-9_]{0,127}$/.test(d.selector.key))fail("The measurement selector is unsupported.");
}
export function assertMetricCatalog(value:unknown,source:MetricSource,companyId:string,after:string|null):asserts value is MetricCatalog {
 assertMetricCompany(source,companyId);
 const v=value as MetricCatalog;if(!v||v.contract!=="metric-catalog/1"||v.current_use_authorized!==false||v.business_effect_authorized!==false||!Array.isArray(v.items)||v.items.length>50||v.next_cursor!==null&&(typeof v.next_cursor!=="string"||!uuid.test(v.next_cursor)||v.next_cursor===after))fail("Available measurements could not be verified.");
 for(const item of v.items){if(!metricPin(item.metric)||!sameMetricPin(item.function,source.function)||typeof item.display_name!=="string"||item.company!==null&&(!metricPin(item.company)||item.company.resource_id!==companyId))fail("A measurement belongs to a different Function revision or company.");assertMetricDefinition(item.definition);if(!restorationInstant(item.definition_snapshot?.valid_at)||!restorationInstant(item.definition_snapshot?.known_at)||!restorationInstant(item.definition_temporal?.system_from)||!restorationInstant(item.definition_temporal?.valid_from)||item.definition_temporal.valid_to!==null&&!restorationInstant(item.definition_temporal.valid_to))fail("The measurement definition time is unavailable.");}
 if(new Set(v.items.map(i=>i.metric.resource_id)).size!==v.items.length)fail("The measurement catalog has ambiguous identities.");
}
export type SavedMetricObservation={version:1;runId:string;request:MetricObservationRequest;function:AnalysisPin;inputRunId:string;inputPlanHash:string;company:AnalysisPin|null};
export function savedMetricObservation(value:MetricObservation,request:MetricObservationRequest):SavedMetricObservation{return {version:1,runId:value.run_id,request:requestOnly(request),function:referenceOnly(value.function),inputRunId:value.input_run_id,inputPlanHash:value.input_plan_hash,company:value.observation.company?referenceOnly(value.observation.company):null};}
export function parseSavedMetricObservation(raw:string,source:MetricSource,companyId:string):SavedMetricObservation|null {
 try{assertMetricCompany(source,companyId);const v=JSON.parse(raw) as SavedMetricObservation,r=v.request;if(v.version!==1||!run.test(v.runId)||!metricPin(r?.metric)||r.invocation_id!==source.invocationId||r.expected_receipt_hash!==source.receiptHash||!time(r.valid_at,source.validAt)||!time(r.known_at,source.knownAt)||r.definition_snapshot!=null&&(!restorationInstant(r.definition_snapshot.valid_at)||!restorationInstant(r.definition_snapshot.known_at))||!sameMetricPin(v.function,source.function)||v.inputRunId!==source.runId||v.inputPlanHash!==source.planHash||v.company!==null&&(!metricPin(v.company)||v.company.resource_id!==companyId))return null;return {version:1,runId:v.runId,request:{metric:referenceOnly(r.metric),invocation_id:r.invocation_id,expected_receipt_hash:r.expected_receipt_hash,valid_at:r.valid_at,known_at:r.known_at,definition_snapshot:r.definition_snapshot?{valid_at:r.definition_snapshot.valid_at,known_at:r.definition_snapshot.known_at}:undefined},function:referenceOnly(v.function),inputRunId:v.inputRunId,inputPlanHash:v.inputPlanHash,company:v.company?referenceOnly(v.company):null};}catch{return null;}
}
export function assertMetricObservation(value:unknown,source:MetricSource,request:MetricObservationRequest,companyId:string,expected?:MetricCatalogItem|SavedMetricObservation):asserts value is MetricObservation {
 assertMetricCompany(source,companyId);
 const v=value as MetricObservation,o=v?.observation;
 if(!v||v.contract!=="metric-observation/1"||v.calculation_runtime!=="metric-observations/1"||!run.test(v.run_id)||!sameMetricPin(v.metric,request.metric)||!sameMetricPin(v.function,source.function)||v.invocation_id!==source.invocationId||v.input_receipt_hash!==source.receiptHash||v.input_receipt_hash!==request.expected_receipt_hash||v.input_run_id!==source.runId||v.input_plan_hash!==source.planHash||v.current_use_authorized!==false||v.business_effect_authorized!==false)fail("The retained measurement does not match this exact Function result.");
 if(!time(v.definition_snapshot?.valid_at,request.definition_snapshot?.valid_at??request.valid_at)||!time(v.definition_snapshot?.known_at,request.definition_snapshot?.known_at??request.known_at))fail("The measurement definition snapshot changed.");
 assertMetricDefinition(v.definition);
 if(!o||!time(o.valid_at,request.valid_at)||!time(o.known_at,request.known_at)||!time(o.valid_at,source.validAt)||!time(o.known_at,source.knownAt)||o.company!==null&&(!metricPin(o.company)||o.company.resource_id!==companyId)||o.grain!==v.definition.grain||metricCanonical(o.unit)!==metricCanonical(v.definition.unit)||metricCanonical(o.dimensions)!==metricCanonical(v.definition.dimensions)||!["COMPLETE","PARTIAL"].includes(o.coverage)||!Array.isArray(o.contributors)||o.contributors.length>1000||!o.contributors.every(metricPin)||new Set(o.contributors.map(p=>p.resource_id)).size!==o.contributors.length||(o.state==="VALUE"?typeof o.value!=="string"||o.value.length>128||!/^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?$/.test(o.value):o.state!=="UNAVAILABLE"||o.value!==null))fail("The measurement value, time, company or evidence contract changed.");
 const sourceResult=metricRecord(v.source_result);if(sourceResult.run_id!==source.runId||sourceResult.invocation_request_id!==source.invocationId||sourceResult.invocation_plan_hash!==source.planHash||!sameMetricPin(sourceResult.function,source.function)||metricCanonical(sourceResult)!==metricCanonical(source.output))fail("The observation does not retain the original source result.");
 if(expected&&("runId" in expected?(v.run_id!==expected.runId||(expected.company===null?o.company!==null:!sameMetricPin(o.company,expected.company))):(metricCanonical(v.definition)!==metricCanonical(expected.definition)||(expected.company===null?o.company!==null:!sameMetricPin(o.company,expected.company)))))fail("The saved observation or selected measurement definition changed.");
 const selector=v.definition.selector;
 if(selector.kind==="MEASURE"){const outputs=source.output.metric_outputs;if(!Array.isArray(outputs))fail("The Function has no declared measurement outputs.");const matches=outputs.filter(x=>metricRecord(x).key===selector.key);if(matches.length!==1||metricCanonical(matches[0])!==metricCanonical(o))fail("The measurement differs from its retained Function output.");}
 else if(o.key!=="object_count"||source.output.coverage!=="COMPLETE_BOUNDED_MATERIALIZATION"||o.value!==String(source.output.total)||!Array.isArray(source.output.objects)||o.contributors.length!==source.output.objects.length||o.contributors.some(p=>!(source.output.objects as unknown[]).some(node=>sameMetricPin(p,node))))fail("The count does not match the complete retained object result.");
}
export type FinancialFunctionChoice={reference:{resource_id:string;version_id:string};content_hash:string;display_name:string;attributes:Record<string,unknown>};
export type AcceptedMetricFunctionRequest=AcceptedMovementFunctionInvocation;
export function financialFunctionMatches(item:FinancialFunctionChoice,company:AnalysisPin):boolean {const d=metricRecord(item.attributes?.definition),c=metricRecord(d.company);return metricPin({...item.reference,content_hash:item.content_hash})&&d.implementation_id==="finance.accepted-journal-movements/v1"&&d.determinism==="DETERMINISTIC_FOR_PINNED_INPUTS"&&hash.test(String(d.code_sha256))&&hash.test(String(d.dependency_sha256))&&c.resource_id===company.resource_id&&c.version_id===company.version_id;}
export function acceptedMetricFunctionRequest(id:string,item:FinancialFunctionChoice,metrics:FinancialMetricResult,company:AnalysisPin,validAt:string,knownAt:string):AcceptedMetricFunctionRequest {
 if(!uuid.test(id)||!financialFunctionMatches(item,company)||metrics.company_id!==company.resource_id||!uuid.test(metrics.invocation_id)||id===metrics.invocation_id||!restorationInstant(validAt)||!restorationInstant(knownAt)||!restorationInstant(metrics.snapshot_at)||!hash.test(metrics.reconciliation_receipt_hash)||!hash.test(metrics.result_sha256))fail("An approved Function for this exact company and financial source is required.");
 return {request_id:id,function:{resource_id:item.reference.resource_id,version_id:item.reference.version_id},valid_at:validAt,known_at:knownAt,offset:0,limit:50,accepted_movements:{source_invocation_id:metrics.invocation_id,company_id:metrics.company_id,journal_snapshot_at:metrics.snapshot_at,expected_reconciliation_sha256:metrics.reconciliation_receipt_hash,expected_result_sha256:metrics.result_sha256}};
}
export function assertAcceptedMetricFunction(value:unknown,request:AcceptedMetricFunctionRequest,fn:AnalysisPin):MetricSource {
 const source=completedMetricSource(value),receipt=metricRecord(metricRecord(value).receipt),echo=metricRecord(receipt.request),frozen=metricRecord(source.output.accepted_movements),input=request.accepted_movements;
 assertMetricCompany(source,input.company_id);
 if(source.invocationId!==request.request_id||!sameMetricPin(source.function,fn)||!time(source.validAt,request.valid_at)||!time(source.knownAt,request.known_at)||metricCanonical({...metricRecord(echo.accepted_movements),journal_snapshot_at:restorationInstant(metricRecord(echo.accepted_movements).journal_snapshot_at)})!==metricCanonical({...input,journal_snapshot_at:restorationInstant(input.journal_snapshot_at)})||metricCanonical(echo.function)!==metricCanonical(request.function)||echo.offset!==(request.offset??0)||echo.limit!==(request.limit??50)||frozen.source_invocation_id!==input.source_invocation_id||frozen.company_id!==input.company_id||frozen.reconciliation_receipt_hash!==input.expected_reconciliation_sha256||frozen.result_sha256!==input.expected_result_sha256||!time(frozen.journal_observed_at,input.journal_snapshot_at))fail("The shared financial Function returned a different retained request or source revision.");return source;
}

export function referenceOnly(p:AnalysisPin):AnalysisPin{return {resource_id:p.resource_id,version_id:p.version_id,content_hash:p.content_hash};}
export function metricObservationRequest(item:MetricCatalogItem,source:MetricSource):MetricObservationRequest{return {metric:referenceOnly(item.metric),invocation_id:source.invocationId,expected_receipt_hash:source.receiptHash,valid_at:source.validAt,known_at:source.knownAt,definition_snapshot:{valid_at:item.definition_snapshot.valid_at,known_at:item.definition_snapshot.known_at}};}

function requestOnly(r:MetricObservationRequest):MetricObservationRequest{return {metric:referenceOnly(r.metric),invocation_id:r.invocation_id,expected_receipt_hash:r.expected_receipt_hash,valid_at:r.valid_at,known_at:r.known_at,...(r.definition_snapshot?{definition_snapshot:{valid_at:r.definition_snapshot.valid_at,known_at:r.definition_snapshot.known_at}}:{})};}

export function assertMetricCompany(source:MetricSource,companyId:string):void {if(!uuid.test(companyId)||source.companyId!==companyId)fail("This completed analysis belongs to another company. Reopen an analysis for the selected company.");}

export type SavedFinancialMeasurementSource={version:1;request:AcceptedMovementFunctionInvocation;function:AnalysisPin;receiptHash:string;runId:string;planHash:string};
export function savedFinancialMeasurementSource(source:MetricSource,request:AcceptedMovementFunctionInvocation):SavedFinancialMeasurementSource{return {version:1,request:{request_id:request.request_id,function:{resource_id:request.function.resource_id,version_id:request.function.version_id},valid_at:request.valid_at,known_at:request.known_at,offset:0,limit:50,accepted_movements:{source_invocation_id:request.accepted_movements.source_invocation_id,company_id:request.accepted_movements.company_id,journal_snapshot_at:request.accepted_movements.journal_snapshot_at,expected_reconciliation_sha256:request.accepted_movements.expected_reconciliation_sha256,expected_result_sha256:request.accepted_movements.expected_result_sha256}},function:referenceOnly(source.function),receiptHash:source.receiptHash,runId:source.runId,planHash:source.planHash};}
export function parseFinancialMeasurementSource(raw:string,metrics:FinancialMetricResult,company:AnalysisPin,validAt:string,knownAt:string):SavedFinancialMeasurementSource|null {
 try{const v=JSON.parse(raw) as SavedFinancialMeasurementSource,r=v.request,i=r.accepted_movements;if(v.version!==1||!metricPin(v.function)||!uuid.test(r.request_id)||r.request_id===metrics.invocation_id||r.function.resource_id!==v.function.resource_id||r.function.version_id!==v.function.version_id||!hash.test(v.receiptHash)||!hash.test(v.planHash)||!run.test(v.runId)||!time(r.valid_at,validAt)||!time(r.known_at,knownAt)||r.offset!==0||r.limit!==50||i.company_id!==company.resource_id||i.company_id!==metrics.company_id||i.source_invocation_id!==metrics.invocation_id||!time(i.journal_snapshot_at,metrics.snapshot_at)||i.expected_reconciliation_sha256!==metrics.reconciliation_receipt_hash||i.expected_result_sha256!==metrics.result_sha256)return null;return savedFinancialMeasurementSource({companyId:company.resource_id,invocationId:r.request_id,function:v.function,receiptHash:v.receiptHash,runId:v.runId,planHash:v.planHash,validAt,knownAt,output:{}},r);}catch{return null;}
}
