"use client";
import {useEffect,useState,type FormEvent} from "react";
import dynamic from "next/dynamic";
import type {CanonicalResource,ResourceProposalDetail} from "@finai/contracts";
import {operationsRequest,type MapSnapshot,type MapWorkspaceState,type MapSelection} from "./operations-model";
import {Badge} from "./g8-ui";
import {readable} from "./g8-model";
import "./operations.css";
const Canvas=dynamic(()=>import("./operations-canvas"),{ssr:false,loading:()=> <p role="status">Opening geographic canvas…</p>});
interface Props {token:string;companyId?:string;canPropose:boolean;state:MapWorkspaceState;onState:(state:MapWorkspaceState)=>void;onSelect:(selection:MapSelection|null)=>void;onReview:(id:string)=>void;selection?:MapSelection|null;compact?:boolean;onOpen?:()=>void}
export default function OperationsMap({token,companyId,canPropose,state,onState,onSelect,onReview,selection,compact=false,onOpen}:Props){
 const [snapshot,setSnapshot]=useState<MapSnapshot|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
 const [bbox,setBbox]=useState("");const [revision,setRevision]=useState(0);const [search,setSearch]=useState("");const [importing,setImporting]=useState(false);
 const selected=selection?.resource??null;
 // Clear the previous authorized result while synchronizing with a changed server query.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const controller=new AbortController();setLoading(true);setSnapshot(null);setError("");
  const query=new URLSearchParams({lens:state.lens,limit:"500"});if(companyId)query.set("company_id",companyId);if(bbox)query.set("bbox",bbox);if(state.validAt)query.set("valid_at",state.validAt);if(state.knownAt)query.set("known_at",state.knownAt);
  void operationsRequest<MapSnapshot>(`map?${query}`,token,controller.signal).then(value=>{if(!controller.signal.aborted)setSnapshot(value);}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Map data unavailable");}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();
 },[token,companyId,state.lens,state.validAt,state.knownAt,bbox,revision]);
 const features=snapshot?.features??[];const rows=[...features.map(f=>({resource:f.properties.resource,reason:"Mapped"})),...(snapshot?.unmapped??[])].filter(row=>`${row.resource.display_name} ${row.resource.object_type}`.toLowerCase().includes(search.toLowerCase()));
 function select(resource:CanonicalResource){if(!snapshot)return;onSelect({resource,validAt:snapshot.valid_at,knownAt:snapshot.known_at});}
 function time(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const valid=String(form.get("valid")??"");const known=String(form.get("known")??"");onSelect(null);onState({...state,validAt:valid?new Date(valid).toISOString():"",knownAt:known?new Date(known).toISOString():""});}
 return <section className={`ops-workspace ${compact?"ops-compact":""}`} aria-label="Network and operations"><header className="ops-heading"><div><h2>Network & operations</h2><small>{state.validAt||state.knownAt?"Historical accepted snapshot":"Latest accepted geography"}</small></div>{compact?<button onClick={onOpen}>Open Maps ↗</button>:<button disabled={loading} onClick={()=>{onSelect(null);setRevision(r=>r+1);}}>Refresh</button>}</header><div className="ops-toolbar"><label><span className="sr-only">Map lens</span><select value={state.lens} onChange={e=>{onState({...state,lens:e.target.value as MapWorkspaceState["lens"]});}}><option value="enterprise_assets">Enterprise assets</option><option value="gas_network">Gas network</option></select></label><Badge>{companyId?"Company scope":"Authorized scope"}</Badge>{bbox&&<button onClick={()=>setBbox("")}>Clear area filter</button>}{!compact&&<button disabled={!canPropose||!companyId} title={!companyId?"Select an accepted company first":!canPropose?"Proposal permission required":"Submit locations for review"} onClick={()=>setImporting(!importing)}>{importing?"Close import":"Import GeoJSON"}</button>}</div>
 {!compact&&<details className="ops-time"><summary>Time context · effective state and recorded knowledge</summary><form onSubmit={time}><label>Effective at (local time)<input type="datetime-local" name="valid"/></label><label>Known at (local time)<input type="datetime-local" name="known"/></label><button>Apply snapshot</button><button type="button" onClick={()=>{onSelect(null);onState({...state,validAt:"",knownAt:""});}}>Latest accepted</button></form><small>Blank dates use the present. This is a historical snapshot, not a live telemetry replay.</small></details>}
 {importing&&companyId&&<SpatialImport token={token} companyId={companyId} onReview={onReview}/>}
 {error&&<p className="g8-inline-error" role="alert">{error}</p>}
 <div className="ops-canvas-section"><Canvas selectedId={selected?.resource_id} features={features} state={state} onViewport={(center,zoom)=>onState({...state,center,zoom})} onSelect={f=>select(f.properties.resource)} onBounds={setBbox}/>{(loading||(!error&&snapshot&&!features.length))&&<div className="ops-map-notice" role="status"><strong>{loading?"Loading reviewed geography…":"No mapped assets in this view"}</strong><span>{loading?"Checking your authorized snapshot.":snapshot?.counts.unmapped?"Accepted resources exist but have no usable geography. Review the list below.":"Import your company’s locations for independent review. The basemap shows geographic context only."}</span></div>}</div>
 <div className="ops-facts"><div><strong>{snapshot?.counts.mapped_in_bounds??"—"}</strong><small>Mapped in area</small></div><div><strong>{snapshot?.counts.unmapped??"—"}</strong><small>Without geography</small></div><div><strong>Not connected</strong><small>Live telemetry</small></div></div>
 {snapshot&&(snapshot.completeness.snapshot_bounded||snapshot.completeness.features_truncated||snapshot.completeness.unmapped_truncated)&&<p className="g8-inline-error">Bounded result: scanned at most {snapshot.completeness.scan_limit} resources and returned at most {snapshot.completeness.limit} per list. Counts do not establish full network coverage.</p>}
 {!compact&&<>{selected&&!rows.some(row=>row.resource.resource_id===selected.resource_id)&&<p className="ops-empty">Pinned selection is outside this lens or filter; its recorded snapshot remains in NYX.</p>}<div className="ops-list-heading"><h3>Assets & geography</h3><input aria-label="Filter loaded map assets" placeholder="Filter loaded assets…" value={search} onChange={e=>setSearch(e.target.value)}/><small>{snapshot?.counts.outside_bounds??0} outside area</small></div><div className="g8-table-scroll"><table><thead><tr><th>Asset</th><th>Type</th><th>Geography</th><th>Evidence</th></tr></thead><tbody>{rows.map(({resource,reason})=><tr key={resource.resource_id} aria-selected={selected?.resource_id===resource.resource_id}><td><button className="g8-link" onClick={()=>select(resource)}>{resource.display_name}</button></td><td>{readable(resource.object_type)}</td><td>{reason}</td><td>{readable(resource.evidence_class)}</td></tr>)}</tbody></table>{!rows.length&&<p className="ops-empty">{loading?"Loading assets…":error?"Asset inventory unavailable.":"No matching assets in this bounded snapshot."}</p>}</div>{selected&&snapshot&&<Connections key={`${selected.resource_id}:${snapshot.valid_at}:${snapshot.known_at}`} token={token} resource={selected} snapshot={{...snapshot,valid_at:selection?.validAt??snapshot.valid_at,known_at:selection?.knownAt??snapshot.known_at}} companyId={companyId} onSelect={select}/>}</>}
 <footer className="ops-footer"><span>Position does not establish connectivity or operating condition.</span>{snapshot&&<small>Effective {new Date(snapshot.valid_at).toLocaleString()} · Known {new Date(snapshot.known_at).toLocaleString()}</small>}</footer></section>;
}
function SpatialImport({token,companyId,onReview}:{token:string;companyId:string;onReview:(id:string)=>void}){
 const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [saved,setSaved]=useState<ResourceProposalDetail|null>(null);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=new FormData(e.currentTarget);const file=values.get("file");setError("");setBusy(true);try{if(!(file instanceof File)||!file.size||file.size>1_800_000)throw new Error("Choose a GeoJSON file smaller than 1.8 MB.");const geojson=JSON.parse(await file.text());const effective=String(values.get("valid"));const proposal=await operationsRequest<ResourceProposalDetail>("import-proposal",token,undefined,{company_id:companyId,title:String(values.get("title")),rationale:String(values.get("rationale")),valid_from:new Date(effective).toISOString(),geojson});setSaved(proposal);}catch(err){setError(err instanceof Error?err.message:"Import unavailable");}finally{setBusy(false);}}
 return <div className="ops-import"><h3>Bring your geography into the workspace</h3><p>Submit up to 99 WGS84 Point, LineString or Polygon features. Each needs properties.name and a unique properties.code. Coordinates use longitude, latitude.</p><p>Locations remain user supplied and require independent review. This does not establish physical pipe connections, certified GIS evidence or live telemetry.</p>{saved?<div role="status"><p>Proposal submitted. Geography will appear only after approval.</p><button onClick={()=>onReview(saved.proposal.proposal_id)}>Open independent review</button></div>:<form onSubmit={submit}><label>GeoJSON file<input name="file" type="file" accept=".geojson,.json,application/geo+json" required/></label><label>Import title<input name="title" required minLength={3} maxLength={200}/></label><label>Effective from (local time)<input name="valid" type="datetime-local" required/></label><label>Reason and source reference<textarea name="rationale" required minLength={10} maxLength={2000}/></label><button disabled={busy}>{busy?"Validating…":"Submit for review"}</button></form>}{error&&<p className="g8-inline-error" role="alert">{error}</p>}</div>;
}
function Connections({token,resource,snapshot,companyId,onSelect}:{token:string;resource:CanonicalResource;snapshot:MapSnapshot;companyId?:string;onSelect:(resource:CanonicalResource)=>void}){
 const [data,setData]=useState<{resources:CanonicalResource[];edges:{source_id:string;target_id:string;relation:string}[];completeness:Record<string,boolean|number>}|null>(null);const [error,setError]=useState("");
 useEffect(()=>{const controller=new AbortController();const query=new URLSearchParams({valid_at:snapshot.valid_at,known_at:snapshot.known_at,depth:"2"});if(companyId)query.set("company_id",companyId);void operationsRequest<NonNullable<typeof data>>(`map/${resource.resource_id}/connections?${query}`,token,controller.signal).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Connections unavailable");});return()=>controller.abort();},[token,resource.resource_id,snapshot.valid_at,snapshot.known_at,companyId]);
 return <section className="ops-connections"><h3>Recorded downstream connections · {resource.display_name}</h3><p>Two steps along explicit directed relationships. Connectivity is not a hydraulic or customer-impact prediction.</p>{error?<p role="alert">{error}</p>:!data?<p role="status">Loading connections…</p>:!data.edges.length?<p>No explicit outgoing connections are recorded in this snapshot.</p>:<ul>{data.edges.map((edge,i)=><li key={i}>{data.resources.find(r=>r.resource_id===edge.source_id)?.display_name} <Badge>{edge.relation}</Badge> <button onClick={()=>{const target=data.resources.find(r=>r.resource_id===edge.target_id);if(target)onSelect(target);}}>{data.resources.find(r=>r.resource_id===edge.target_id)?.display_name}</button></li>)}</ul>}{data&&(data.completeness.snapshot_bounded||data.completeness.depth_bounded||data.completeness.node_bounded)&&<p className="g8-inline-error">Traversal is bounded; further connections may exist.</p>}</section>;
}
