"use client";

import { useEffect, useState } from "react";
import type { ProjectionCatalog, WorkspaceSelection, WorkspaceSelectionResponse } from "@finai/contracts";

export default function ProjectionControlSurface({ token, companyId }: { token: string; companyId: string }) {
  const [catalog, setCatalog] = useState<ProjectionCatalog | null>(null);
  const [selection, setSelection] = useState<WorkspaceSelection>({ company_id: companyId, workspace: "BRIDGE_FIRST" });
  const [validated, setValidated] = useState<WorkspaceSelectionResponse | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); void fetch("/api/workspace/projections/catalog", { headers: { Authorization: `Bearer ${token}` }, cache: "no-store", signal: controller.signal }).then(async response => { const data = await response.json() as ProjectionCatalog & { detail?: string }; if (!response.ok) throw new Error(data.detail ?? "Projection registry unavailable"); setCatalog(data); }).catch(failure => { if (!controller.signal.aborted) setError(failure instanceof Error ? failure.message : "Projection registry unavailable"); }); return () => controller.abort(); }, [token]);
  async function validate() { setError(""); try { const response = await fetch("/api/workspace/projections/selection", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify(selection), cache: "no-store" }); const data = await response.json() as WorkspaceSelectionResponse & { detail?: string }; if (!response.ok) throw new Error(data.detail ?? "Selection refused"); setValidated(data); } catch (failure) { setError(failure instanceof Error ? failure.message : "Selection refused"); } }
  return <section className="g8-panel" aria-label="Cross-projection control surface"><div className="g8-panel-heading"><div><p className="overline">PROJECTION FABRIC · EXACT CONTEXT</p><h3>One selection, many governed views</h3><p>Operations, planning, evidence, lineage, bridge and NYX projections must inherit the same selection. This control validates scope without changing authority.</p></div><span className="g8-badge">{validated?.scope_state ?? "NOT VALIDATED"}</span></div><div className="g8-actionbar"><label>Workspace<select value={selection.workspace ?? ""} onChange={event => setSelection({ ...selection, workspace: (event.target.value || null) as WorkspaceSelection["workspace"] })}><option value="">All workspaces</option><option value="TABLE_FIRST">Table first</option><option value="GRAPH_FIRST">Graph first</option><option value="TIMELINE_FIRST">Timeline first</option><option value="BRIDGE_FIRST">Bridge first</option><option value="COMMAND_EXECUTIVE">Command / executive</option><option value="REPORT">Report</option></select></label><label>Product<input value={selection.product_id ?? ""} onChange={event => setSelection({ ...selection, product_id: event.target.value || null })} placeholder="Optional product" /></label><label>Station<input value={selection.station_id ?? ""} onChange={event => setSelection({ ...selection, station_id: event.target.value || null })} placeholder="Optional station" /></label><label>Period<input value={selection.period ?? ""} onChange={event => setSelection({ ...selection, period: event.target.value || null })} placeholder="YYYY-MM" /></label><label>Replay as of<input value={selection.replay_as_of ?? ""} onChange={event => setSelection({ ...selection, replay_as_of: event.target.value || null })} placeholder="Optional known time" /></label><button onClick={() => void validate()}>Validate exact selection</button></div>{error && <p className="g8-inline-error" role="alert">{error}</p>}{validated && <p role="status">Validated company scope: <strong>{validated.selection.company_id}</strong>. {validated.eligible_projections.length} projections are eligible for this exact context. No authority or business effect was changed.</p>}{catalog && <div className="g8-table-scroll"><table><caption>Server-owned projection registry · all cards synchronize through WORKSPACE_SELECTION</caption><thead><tr><th>Projection</th><th>Kind</th><th>Chart</th><th>Workspace</th><th>Status</th><th>Contract</th></tr></thead><tbody>{catalog.projections.map(item => <tr key={item.projection_id}><th>{item.label}</th><td>{item.kind}</td><td>{item.chart_type ?? "—"}</td><td>{item.workspaces.join(" · ")}</td><td>{item.status}</td><td>{item.backend_contracts.join(" · ")}</td></tr>)}</tbody></table></div>}</section>;
}
