"use client";

import {useEffect,useRef,useState} from "react";
import type {AnalysisProjection,CompanyFinancialResults,ReportPreview,ReportSectionReference,ReportComposition,RetainedReport,RetainedReportPage} from "@finai/contracts";
import SemanticWorksheet,{type WorksheetLayout} from "./semantic-worksheet";
import {assertReportPreview,assertRetainedReport,reportCellLabel,reportCompositionReferences,reportEvidenceTarget,reportSectionFromProjection} from "./retained-report-state";
import {useSourceReview} from "./source-review-navigation";
import "./semantic-analysis-workspace.css";
import "./reporting-workspace.css";

type ReportingProps={token:string;companyId:string;companyName:string};
const api=async<T>(path:string,token:string,init?:RequestInit):Promise<T>=>{const response=await fetch(`/api/${path}`,{...init,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(init?.headers??{})},cache:"no-store"});const body=await response.json();if(!response.ok)throw Error(typeof body?.detail==="string"?body.detail:`Reporting request unavailable (${response.status})`);return body as T;};

/** Reporting stays a retained-result workflow: discover, inspect, preview, save and reopen. */
export function ReportingWorkspace({token,companyId,companyName}:ReportingProps){
 const [discovery,setDiscovery]=useState<CompanyFinancialResults|null>(null);const [saved,setSaved]=useState<RetainedReportPage|null>(null);const [sections,setSections]=useState<Array<{reference:ReportSectionReference;projection:AnalysisProjection}>>([]);const [title,setTitle]=useState("");const [commentary,setCommentary]=useState("");const [preview,setPreview]=useState<ReportPreview|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const refresh=async()=>{if(!companyId)return;try{setError("");const [results,reports]=await Promise.all([api<CompanyFinancialResults>(`ontology/company-financial-results?company_id=${encodeURIComponent(companyId)}`,token),api<RetainedReportPage>(`ontology/retained-reports?company_id=${encodeURIComponent(companyId)}`,token)]);setDiscovery(results);setSaved(reports);if(!title)setTitle(`${companyName} financial review`);}catch(cause){setError(cause instanceof Error?cause.message:"Reporting context unavailable.");}};
 useEffect(()=>{setSections([]);setPreview(null);void refresh();},[companyId,token]);
 const openResult=async(result:CompanyFinancialResults["results"][number])=>{try{setBusy(true);setError("");const projection=await api<AnalysisProjection>("ontology/analysis/project",token,{method:"POST",body:JSON.stringify({invocation_id:result.invocation_id,company_id:companyId})});setSections(current=>current.some(item=>item.projection.descriptor.invocation_id===projection.descriptor.invocation_id)?current:[...current,{projection,reference:reportSectionFromProjection(projection,companyId,crypto.randomUUID())}]);}catch(cause){setError(cause instanceof Error?cause.message:"This retained result could not be reopened.");}finally{setBusy(false);}};
 const composition=():ReportComposition=>reportCompositionReferences({company_id:companyId,valid_at:discovery?.valid_at??new Date(0).toISOString(),known_at:discovery?.known_at??new Date(0).toISOString(),title:title.trim(),commentary,sections:sections.map(item=>item.reference)});
 const previewReport=async()=>{try{setBusy(true);setError("");const result=await api<ReportPreview>("ontology/retained-reports/preview",token,{method:"POST",body:JSON.stringify(composition())});assertReportPreview(result,companyId?composition():composition());setPreview(result);}catch(cause){setPreview(null);setError(cause instanceof Error?cause.message:"Report preview unavailable.");}finally{setBusy(false);}};
 const saveReport=async()=>{if(!preview)return;try{setBusy(true);setError("");const request={request_id:crypto.randomUUID(),report_id:crypto.randomUUID(),previous_proposal_id:null,expected_preview_sha256:preview.snapshot_sha256,composition:composition()};const report=await api<RetainedReport>("ontology/retained-reports",token,{method:"POST",body:JSON.stringify(request)});assertRetainedReport(report,companyId,undefined,request,preview);await refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Report draft could not be retained.");}finally{setBusy(false);}};
 return <section className="reporting-workspace" aria-label="Reporting workspace"><header className="reporting-header"><div><p className="overline">RETAINED RESULT REPORTING</p><h2>{companyName||"Selected company"}</h2><p>Compose a report from exact retained financial results. Values remain server-owned and unavailable capabilities stay explicit.</p></div><button type="button" disabled={busy||!sections.length||!title.trim()} onClick={()=>void previewReport()}>Preview report</button></header>{error&&<p role="alert" className="error-banner">{error}</p>}<div className="reporting-layout"><section className="reporting-results"><h3>Available retained results</h3>{discovery?.results.length?discovery.results.map(result=><article key={result.invocation_id}><div><strong>{result.implementation_id}</strong><small>{new Date(result.recorded_at).toLocaleString()} · {result.state}</small></div><button type="button" disabled={busy||sections.some(item=>item.projection.descriptor.invocation_id===result.invocation_id)} onClick={()=>void openResult(result)}>{sections.some(item=>item.projection.descriptor.invocation_id===result.invocation_id)?"Added":"Open exact result"}</button></article>):<p role="status">{discovery?"No retained financial results are available for this company and snapshot.":"Loading retained results…"}</p>}{discovery?.unavailable_capabilities.map(item=><p className="reporting-unavailable" key={item.function.resource_id}>Unavailable: {item.reason}</p>)}</section><section className="reporting-editor"><label>Report title<input value={title} maxLength={200} onChange={event=>{setTitle(event.target.value);setPreview(null);}}/></label><label>Commentary<textarea value={commentary} maxLength={8000} onChange={event=>{setCommentary(event.target.value);setPreview(null);}}/></label>{sections.map((item,index)=><ReportSectionEditor key={item.reference.section_id} section={item.reference} projection={item.projection} companyId={companyId} disabled={busy} onChange={reference=>{setSections(current=>current.map((entry,entryIndex)=>entryIndex===index?{...entry,reference}:entry));setPreview(null);}}/>)}{preview&&<div className="reporting-preview" role="status"><strong>Preview retained</strong><span>{preview.snapshot.sections.length} sections · exact preview {preview.snapshot_sha256.slice(0,12)}…</span><button type="button" disabled={busy} onClick={()=>void saveReport()}>Save immutable draft</button></div>}</section><section className="reporting-revisions"><h3>Saved report revisions</h3>{saved?.items.length?saved.items.map(report=><article key={report.reference.proposal_id}><strong>{report.title}</strong><small>{report.review_state} · {new Date(report.created_at).toLocaleString()}</small><span>Exact report {report.reference.report_id.slice(0,8)}…</span></article>):<p role="status">No saved report revisions for this company.</p>}</section></div></section>;
}

/** Edits only the report's reference composition; preview values stay server-owned. */
export function ReportSectionEditor({section,projection,companyId,disabled,onChange}:{section:ReportSectionReference;projection:AnalysisProjection;companyId:string;disabled:boolean;onChange:(section:ReportSectionReference)=>void}){
 const openSourceReview=useSourceReview();
 const scroll=useRef<HTMLDivElement>(null);
 const [layout,setLayout]=useState<WorksheetLayout>({widths:{},pinned:[],focus:null,left:0,search:""});
 const [error,setError]=useState("");
 const fields=projection.descriptor.fields;
 return <section className="reporting-section semantic-analysis" aria-label={section.title}>
  <label>Section title<input value={section.title} disabled={disabled} onChange={event=>onChange({...section,title:event.target.value})}/></label>
  <details className="reporting-section-filters"><summary>Report filters and arrangement</summary><p>Changes take effect in the next server preview. No measures are recalculated in this browser.</p><fieldset disabled={disabled}>{fields.filter(field=>field.filterable).map(field=>{
   const filter=section.filters.find(item=>item.field===field.key);
   return <label key={field.key}>{field.label}<select value={filter?String(field.options.findIndex(option=>option.state===filter.state&&option.value===filter.value)):""} disabled={!filter&&section.filters.length>=4} onChange={event=>{const filters=section.filters.filter(item=>item.field!==field.key),option=field.options[Number(event.target.value)];if(event.target.value!==""&&option)filters.push({field:field.key,state:option.state,value:option.value});onChange({...section,filters});}}><option value="">All retained values</option>{field.options.map((option,index)=><option key={index} value={index}>{reportCellLabel(option,field)}</option>)}</select></label>;
  })}<label>Arrange rows<select value={section.group_by??""} onChange={event=>onChange({...section,group_by:event.target.value||null})}><option value="">Original order</option>{fields.filter(field=>field.groupable).map(field=><option key={field.key} value={field.key}>{field.label}</option>)}</select></label></fieldset></details>
  {error&&<p role="alert">{error}</p>}
  <fieldset className="reporting-grid" disabled={disabled}><legend className="semantic-sr-only">Report section worksheet</legend><SemanticWorksheet projection={projection} fields={fields} columns={section.columns} layout={layout} onLayout={setLayout} onColumns={columns=>{if(!columns.length||columns.length>32){setError("Choose one to 32 report columns.");return;}setError("");onChange({...section,columns});}} scroll={scroll} label={reportCellLabel} onPick={row=>{try{const target=reportEvidenceTarget(projection,companyId,row.key);if(target)openSourceReview(target);else setError("This retained row has no contributor evidence.");}catch(cause){setError(String(cause));}}}/></fieldset>
 </section>;
}
