"use client";
import type {OperatorInspection} from "@finai/contracts";
import {ArrowRight} from "@phosphor-icons/react";
import {Badge} from "./g8-ui";
import {displayName} from "./display-name";
import {readable} from "./g8-model";
import ResourceAuthority from "./resource-authority";
const date=(value:string)=>new Date(value).toLocaleDateString(undefined,{month:"short",day:"numeric"});
const tone=(state:string)=>state==="APPROVED"?"good":state==="REJECTED"||state==="REVOKED"?"bad":state==="PENDING"?"warning":"neutral";
export default function ResourceInspection({token,selected,onTrace,onHistory,onAccountPolicy,onCalculate,onInspect,onClear}:{token:string;selected:OperatorInspection;onTrace:()=>void;onHistory:()=>void;onAccountPolicy?:()=>void;onCalculate?:()=>void;onInspect:(resourceId:string,versionId:string,knownAt:string)=>void;onClear:()=>void}) {
 return <div className="g8-inspector"><p className="overline">RESOURCE CONTEXT</p><h3>{displayName(selected.resource.display_name)}</h3><Badge tone={tone(selected.resource.authority_state)}>Definition review: {readable(selected.resource.authority_state)}</Badge><p>{readable(selected.resource.object_type)} · {readable(selected.resource.evidence_class)}</p><button onClick={onTrace}>Show system trace</button><button onClick={onHistory}>View history & compare</button>{selected.resource.object_type==="LocalAccount"&&onAccountPolicy&&<button onClick={onAccountPolicy}>Review analytical requirements</button>}<ResourceAuthority key={selected.resource.version_id} token={token} resource={selected.resource} knownAt={selected.known_at}/>{typeof selected.resource.attributes.minimum_authority_state==="string"&&onCalculate&&<button onClick={onCalculate}>Calculate with this authority contract</button>}<dl><dt>Effective from</dt><dd>{date(selected.resource.valid_from)}</dd><dt>Known by G8 at</dt><dd>{new Date(selected.known_at).toLocaleString()}</dd><dt>Versions known then</dt><dd>{selected.versions.length}{selected.versions_truncated?"+ (bounded)":""}</dd><dt>Visible dependents</dt><dd>{selected.dependents.length}{selected.dependents_truncated?"+ (bounded)":""}</dd></dl>{selected.dependents.slice(0,8).map(item=><button className="g8-panel-action" key={`${item.version_id}:${item.relation}`} onClick={()=>onInspect(item.resource_id,item.version_id,selected.known_at)}>{displayName(item.display_name)}<ArrowRight size={13}/></button>)}<details><summary>Advanced: identity & version</summary><small>{selected.resource.resource_id}<br/>{selected.resource.version_id}</small></details><button className="g8-link" onClick={onClear}>Clear selection</button></div>;
}
