"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import type {CanonicalResource} from "@finai/contracts";
import WorksheetAnalysisResult,{type WorksheetResult} from "./worksheet-analysis-result";
import {displayName} from "./display-name";
import "./saved-analysis-workbench.css";
type Pin={resource_id:string;version_id:string};
type SavedFunction={reference:Pin;display_name:string;attributes:Record<string,unknown>;content_hash:string};
type Request={request_id:string;function:Pin;valid_at:string;known_at:string;offset:number;limit:number};
type BaseOutput={run_id:string;contract:"function-result/1";function:Pin;mode:"EVIDENCE_ANALYSIS_ONLY";coverage:"QUERY_PAGE_ONLY"|"REVIEWED_WORKSHEET_PAGE_ONLY";current_use_authorized:false;business_effect_authorized:false;invocation_request_id:string;query:{valid_at:string;known_at:string;offset:number;limit:number};objects:CanonicalResource[];total:number;next_offset:number|null;derived_values:Array<{object_id:string;object_version_id:string;definition_version_id:string;name:string;value:string|null;status:string;reason?:string}>};
type Output=BaseOutput&Partial<Omit<WorksheetResult,"coverage">>;
function worksheet(output:BaseOutput):output is BaseOutput&WorksheetResult{return output.coverage==="REVIEWED_WORKSHEET_PAGE_ONLY"&&"temporal_semantics" in output&&output.temporal_semantics==="IMMUTABLE_RETAINED_SNAPSHOT_NOT_VALID_TIME_FACTS"&&"authority" in output&&output.authority==="SOURCE_CELLS_ONLY"&&"source_rows" in output&&Array.isArray(output.source_rows)&&"source_document" in output&&typeof output.source_document==="object"&&output.source_document!==null&&"source_query" in output&&typeof output.source_query==="object"&&output.source_query!==null;}
type Invocation={invocation_id:string;status:"SUCCEEDED"|"FAILED"|"INTENT_RETAINED";receipt_hash:string|null;receipt:{request?:Request;recorded_at?:string;failure_code?:string};output:Output|null;current_use_authorized:false;business_effect_authorized:false};
type Props={initialInvocationId?:string;token:string;companyName:string;onInspect:(resource:CanonicalResource,knownAt:string)=>void;onTrace:(resource:CanonicalResource,knownAt:string)=>void};
export default function SavedAnalysisWorkbench(props:Props){return <Workbench key={`${props.token}:${props.initialInvocationId??""}`} {...props}/>;}
function Workbench({initialInvocationId,token,companyName,onInspect,onTrace}:Props){
 const [library,setLibrary]=useState<SavedFunction[]>([]);const [after,setAfter]=useState<string|null>(null);const [next,setNext]=useState<string|null>(null);const [libraryRevision,setLibraryRevision]=useState(0);const [libraryBusy,setLibraryBusy]=useState(true);const [libraryError,setLibraryError]=useState("");
 const [selected,setSelected]=useState("");const [validAt,setValidAt]=useState(()=>new Date().toISOString());const [knownAt,setKnownAt]=useState(()=>new Date().toISOString());
 const [request,setRequest]=useState<Request|null>(null);const [result,setResult]=useState<Invocation|null>(null);const [saved,setSaved]=useState("");const [busy,setBusy]=useState(Boolean(initialInvocationId));const [error,setError]=useState("");const pending=useRef<AbortController|null>(null);
 useEffect(()=>()=>{pending.current?.abort();pending.current=null;},[]);
 useEffect(()=>{const controller=new AbortController();let disposed=false;const timer=setTimeout(()=>controller.abort(),20000);
  async function load(){setLibraryBusy(true);setLibraryError("");try{const response=await fetch(`/api/ontology/functions${after?`?after_resource_id=${encodeURIComponent(after)}`:""}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store",signal:controller.signal});if(!response.ok)throw new Error("Saved analyses are unavailable in your authorized scope.");const data:{items:SavedFunction[];next_cursor:string|null;purpose:string}=await response.json();if(data.purpose!=="EVIDENCE_ANALYSIS_ONLY"||!Array.isArray(data.items)||after&&data.next_cursor===after)throw new Error("Saved analysis catalog could not be verified.");if(!disposed){setLibrary(previous=>Array.from(new Map([...(after?previous:[]),...data.items].map(item=>[item.reference.version_id,item])).values()));setNext(data.next_cursor);}}catch(failure){if(!disposed)setLibraryError(controller.signal.aborted?"Saved analyses timed out. Retry this page.":failure instanceof Error?failure.message:"Catalog unavailable");}finally{clearTimeout(timer);if(!disposed)setLibraryBusy(false);}}
  void load();return()=>{disposed=true;clearTimeout(timer);controller.abort();};
 },[token,after,libraryRevision]);
 const execute=useCallback(async(frozen:Request|null,reopenId?:string)=>{
  pending.current?.abort();const controller=new AbortController();pending.current=controller;const timer=setTimeout(()=>controller.abort(),20000);
  try{const response=await fetch(reopenId?`/api/ontology/functions/invocations/${encodeURIComponent(reopenId)}`:"/api/ontology/functions/invocations",{method:reopenId?"GET":"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},...(!reopenId?{body:JSON.stringify(frozen)}:{}),cache:"no-store",signal:controller.signal});if(!response.ok)throw new Error("The retained run could not be confirmed. Retry preserves the original request and time cutoffs.");const data:Invocation=await response.json();const output=data.output;
   if(data.invocation_id!==(reopenId??frozen?.request_id)||data.current_use_authorized!==false||data.business_effect_authorized!==false||!["SUCCEEDED","FAILED","INTENT_RETAINED"].includes(data.status)||data.status==="SUCCEEDED"&&(!output||output.contract!=="function-result/1"||output.mode!=="EVIDENCE_ANALYSIS_ONLY"||(output.coverage!=="QUERY_PAGE_ONLY"&&!worksheet(output))||output.invocation_request_id!==data.invocation_id||output.current_use_authorized!==false||output.business_effect_authorized!==false)||output&&frozen&&(output.function.resource_id!==frozen.function.resource_id||output.function.version_id!==frozen.function.version_id||Date.parse(output.query.known_at)!==Date.parse(frozen.known_at)||Date.parse(output.query.valid_at)!==Date.parse(frozen.valid_at)||output.query.offset!==frozen.offset))throw new Error("The retained result did not match the exact analysis, request and time cutoffs.");
   if(data.status==="INTENT_RETAINED"&&reopenId){const retained=data.receipt.request;const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;const aware=(value:string)=>typeof value==="string"&&/(Z|[+-]\d{2}:\d{2})$/i.test(value)&&Number.isFinite(Date.parse(value));if(!retained||retained.request_id!==data.invocation_id||!uuid.test(retained.function?.resource_id??"")||!uuid.test(retained.function?.version_id??"")||!aware(retained.valid_at)||!aware(retained.known_at)||!Number.isInteger(retained.offset)||retained.offset<0||retained.offset>1000000||!Number.isInteger(retained.limit)||retained.limit<1||retained.limit>200)throw new Error("Retained intent has no valid original request to resume safely.");if(pending.current===controller&&!controller.signal.aborted){setRequest(retained);setSelected(retained.function.version_id);setValidAt(retained.valid_at);setKnownAt(retained.known_at);}}
   if(pending.current===controller&&!controller.signal.aborted){setResult(data);setSaved(data.invocation_id);}
  }catch(failure){if(pending.current===controller)setError(controller.signal.aborted?"The response timed out; the intent may be retained. Retry the same request to check or resume it.":failure instanceof Error?failure.message:"Analysis unavailable");}finally{clearTimeout(timer);if(pending.current===controller)setBusy(false);}
 },[token]);
 // execute updates React state only after awaiting the retained invocation response.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(initialInvocationId)void execute(null,initialInvocationId);},[initialInvocationId,execute]);
 function run(frozen:Request|null,reopenId?:string){setBusy(true);setError("");setResult(null);void execute(frozen,reopenId);}
 function worksheetLimit(definition:SavedFunction){const adapter=definition.attributes.definition;if(adapter&&typeof adapter==="object"&&"implementation_id" in adapter&&adapter.implementation_id==="source.retained-xls-worksheet/v1"&&"row_count" in adapter&&typeof adapter.row_count==="number"&&Number.isInteger(adapter.row_count)&&adapter.row_count>=1&&adapter.row_count<=50)return adapter.row_count;return 50;}
 function start(){const definition=library.find(item=>item.reference.version_id===selected);if(!definition)return;const aware=(value:string)=>/(Z|[+-]\d{2}:\d{2})$/i.test(value)&&Number.isFinite(Date.parse(value));if(!aware(validAt)||!aware(knownAt)){setError("Enter effective and known timestamps with an explicit timezone, such as +04:00 or Z.");return;}const frozen={request_id:crypto.randomUUID(),function:definition.reference,valid_at:new Date(validAt).toISOString(),known_at:new Date(knownAt).toISOString(),offset:0,limit:worksheetLimit(definition)};setRequest(frozen);run(frozen);}
 function page(offset:number){if(!request)return;const frozen={...request,request_id:crypto.randomUUID(),offset};setRequest(frozen);run(frozen);}
 const output=result?.output;const pageNext=output?(worksheet(output)?(output.source_query.next_offset!==null&&output.source_query.next_offset-output.source_document.first_row<output.source_document.row_count?output.source_query.next_offset-output.source_document.first_row:null):output.next_offset):null;const locked=Boolean(request)||busy;
 return <section className="saved-analysis" aria-label="Saved analysis workbench"><header><p className="overline">REVIEWED SAVED ANALYSES</p><h3>Run an evidence analysis</h3><p>Navigation context: {companyName||"No company selected"}. Analysis inputs come from its reviewed source contract in your authorized scope; this does not establish company ledger applicability.</p></header>
  <div className="saved-analysis-controls"><label>Saved analysis<select value={selected} disabled={locked||libraryBusy} onChange={event=>setSelected(event.target.value)}><option value="">Choose a reviewed analysis</option>{library.map(item=><option value={item.reference.version_id} key={item.reference.version_id}>{displayName(item.display_name)}</option>)}</select></label><label>Effective at — timezone required<input value={validAt} disabled={locked} onChange={event=>setValidAt(event.target.value)}/></label><label>Known at — timezone required<input value={knownAt} disabled={locked} onChange={event=>setKnownAt(event.target.value)}/></label></div>
  {libraryBusy&&<p role="status">Loading reviewed analyses…</p>}{libraryError&&<p role="alert">{libraryError}</p>}{!libraryBusy&&!libraryError&&!library.length&&<p>No reviewed saved analyses were returned in your authorized scope.</p>}{libraryError&&<button disabled={libraryBusy} onClick={()=>setLibraryRevision(value=>value+1)}>Retry analysis catalog</button>}{next&&<button disabled={libraryBusy||locked} onClick={()=>setAfter(next)}>Load more saved analyses</button>}
  <div className="saved-analysis-actions">{!request?<button disabled={busy||!selected} onClick={start}>Run and retain analysis</button>:<><button disabled={busy} onClick={()=>run(request)}>{result?.status==="INTENT_RETAINED"?"Resume retained intent":"Retry exact run"}</button><button disabled={busy} onClick={()=>{setRequest(null);setResult(null);setError("");}}>Start a new analysis</button></>}</div>
  <details><summary>Reopen a retained invocation</summary><label>Invocation reference<input value={saved} disabled={busy} onChange={event=>setSaved(event.target.value)}/></label><button disabled={busy||!/^[a-f0-9-]{36}$/i.test(saved)} onClick={()=>{setRequest(null);run(null,saved);}}>Reopen retained result</button></details>
  {busy&&<p role="status">Awaiting the retained run response…</p>}{error&&<p role="alert">{error}</p>}{result&&<><p>{result.status==="INTENT_RETAINED"?"Invocation intent is retained; completion is not established.":result.status==="FAILED"?`Execution failed: ${result.receipt.failure_code??"reason unavailable"}.` :"Analysis result retained."}</p><details><summary>Exact invocation evidence</summary><p>{result.invocation_id}</p><p>{result.receipt_hash??"No terminal receipt hash"}</p>{output&&<p>{output.run_id}</p>}</details></>}
  {output&&<section aria-label="Retained analysis page"><p>{worksheet(output)?"Requested effective context":"Effective"} {new Date(output.query.valid_at).toLocaleString()} · known {new Date(output.query.known_at).toLocaleString()}</p>{worksheet(output)?<WorksheetAnalysisResult key={output.run_id} token={token} result={output} knownAt={output.query.known_at} onInspect={onInspect} onTrace={onTrace}/>:<><p>{output.objects.length} objects on this page, offset {output.query.offset}; {output.total} query matches. Derived values apply to this page only.</p><div className="saved-analysis-table"><table><thead><tr><th>Source object</th><th>Derived values & availability</th><th>Investigate</th></tr></thead><tbody>{output.objects.map(object=><tr key={object.version_id}><th scope="row">{displayName(object.display_name)}<small>{object.object_type}</small></th><td>{output.derived_values.filter(value=>value.object_version_id===object.version_id).map(value=><p key={value.definition_version_id}>{value.name}: {value.value??"Unavailable"} · {value.status}{value.reason?` — ${value.reason}`:""}</p>)}{!output.derived_values.some(value=>value.object_version_id===object.version_id)&&<span>No derived value requested for this object.</span>}</td><td><button onClick={()=>onInspect(object,output.query.known_at)}>Inspect</button><button onClick={()=>onTrace(object,output.query.known_at)}>Trace evidence</button></td></tr>)}</tbody></table></div>{!output.objects.length&&<p>No objects matched the reviewed query at these cutoffs.</p>}</>}{request&&<div className="saved-analysis-actions"><button disabled={busy||output.query.offset===0} onClick={()=>page(Math.max(0,output.query.offset-output.query.limit))}>Previous page</button><button disabled={busy||pageNext===null} onClick={()=>pageNext!==null&&page(pageNext)}>Next page</button></div>}</section>}
  <footer>Evidence analysis only. A retained result does not grant current-use permission, financial authority or a business action.</footer>
 </section>;
}
