"use client";

import {useEffect,useRef,useState,type RefObject,type CSSProperties} from "react";
import type {AnalysisField,AnalysisProjection,AnalysisRow,AnalysisValue} from "@finai/contracts";

export type WorksheetLayout={widths:Record<string,number>;pinned:string[];focus:{row:string;column:string}|null;left:number};
type Props={projection:AnalysisProjection;fields:AnalysisField[];columns:string[];layout:WorksheetLayout;onLayout:(next:WorksheetLayout)=>void;onColumns:(keys:string[])=>void;scroll:RefObject<HTMLDivElement|null>;label:(value:AnalysisValue,field:AnalysisField)=>string;onPick:(row:AnalysisRow,button:HTMLButtonElement)=>void};

/** Presentation only: row order, values and groups come from the canonical response. */
export default function SemanticWorksheet({projection,fields,columns,layout,onLayout,onColumns,scroll,label,onPick}:Props){
 const [top,setTop]=useState(0);const [available,setAvailable]=useState(700);
 useEffect(()=>{const el=scroll.current;if(!el)return;let previousHeight=el.clientHeight;const observer=new ResizeObserver(()=>{setAvailable(el.clientWidth);const selected=el.querySelector<HTMLElement>("tr[aria-selected=true]");if(selected){const relative=selected.getBoundingClientRect().top-el.getBoundingClientRect().top;if(relative>=0&&relative<previousHeight&&relative+36>el.clientHeight)el.scrollBy({top:relative+36-el.clientHeight});}previousHeight=el.clientHeight;});observer.observe(el);return()=>observer.disconnect();},[scroll]);
 const drag=useRef<{key:string;x:number;width:number}|null>(null);
 const ordered=columns.map(key=>fields.find(field=>field.key===key)).filter((field):field is AnalysisField=>Boolean(field));
 const shown=[...ordered.filter(field=>layout.pinned.includes(field.key)),...ordered.filter(field=>!layout.pinned.includes(field.key))];
 const flexible=shown.filter(field=>layout.widths[field.key]===undefined).length;const allocated=shown.reduce((sum,field)=>sum+(layout.widths[field.key]??0),0);
 const width=(key:string)=>layout.widths[key]??Math.max(160,(available-220-allocated)/Math.max(1,flexible));
 const offsets=new Map<string,number>();let offset=220;
 shown.forEach(field=>{if(layout.pinned.includes(field.key)){offsets.set(field.key,offset);offset+=width(field.key);}});
 const style=(key:string):CSSProperties=>({width:width(key),...(offsets.has(key)?{position:"sticky",left:offsets.get(key),zIndex:2}: {})});
 const rowsByKey=new Map(projection.rows.map(row=>[row.key,row]));
 const rows=projection.sections.flatMap(section=>section.row_keys.map(key=>({row:rowsByKey.get(key)!,section:section.label})));
 const start=Math.max(0,Math.floor(top/36)-8),end=Math.min(rows.length,start+70);
 function moveColumn(key:string,delta:number){const next=[...columns],index=next.indexOf(key),target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];onColumns(next);}
 function focusCell(rowIndex:number,columnIndex:number){const row=rows[Math.max(0,Math.min(rows.length-1,rowIndex))]?.row;if(!row)return;const column=columnIndex<=0?"$row":shown[Math.min(shown.length,columnIndex)-1]?.key??"$row";onLayout({...layout,focus:{row:row.key,column}});const el=scroll.current;if(!el)return;const y=rowIndex*36;if(y<el.scrollTop)el.scrollTo({top:y});if(y+72>el.scrollTop+el.clientHeight)el.scrollTo({top:y+72-el.clientHeight});setTop(el.scrollTop);requestAnimationFrame(()=>{const cell=el.querySelector<HTMLElement>(`[data-row="${row.key}"][data-column="${CSS.escape(column)}"]`);cell?.focus({preventScroll:true});cell?.scrollIntoView({block:"nearest",inline:"nearest"});});}
 return <div className="semantic-worksheet">
  <details className="semantic-column-menu"><summary>Columns · {shown.length}</summary><div>{fields.map(field=>{const visible=columns.includes(field.key);return <div key={field.key}><label><input type="checkbox" checked={visible} onChange={()=>onColumns(visible?columns.filter(key=>key!==field.key):[...columns,field.key])}/>{field.label}</label><button disabled={!visible||columns.indexOf(field.key)===0} aria-label={`Move ${field.label} left`} onClick={()=>moveColumn(field.key,-1)}>←</button><button disabled={!visible||columns.indexOf(field.key)===columns.length-1} aria-label={`Move ${field.label} right`} onClick={()=>moveColumn(field.key,1)}>→</button><button disabled={!visible} aria-pressed={layout.pinned.includes(field.key)} onClick={()=>onLayout({...layout,pinned:layout.pinned.includes(field.key)?layout.pinned.filter(key=>key!==field.key):[...layout.pinned,field.key]})}>Pin {field.label}</button></div>;})}</div></details>
  <div ref={scroll} className="semantic-grid" onScroll={event=>{setTop(event.currentTarget.scrollTop);if(event.currentTarget.scrollLeft!==layout.left)onLayout({...layout,left:event.currentTarget.scrollLeft});}} aria-label="Retained analysis grid">
   <table role="grid" aria-label="Analysis worksheet" aria-rowcount={rows.length+1} aria-colcount={shown.length+1} style={{width:220+shown.reduce((sum,field)=>sum+width(field.key),0)}}>
    <colgroup><col style={{width:220}}/>{shown.map(field=><col key={field.key} style={{width:width(field.key)}}/>)}</colgroup>
    <thead><tr><th scope="col">{projection.descriptor.row_noun==="objects"?"Object / evidence":"Contributors"}</th>{shown.map(field=><th key={field.key} scope="col" style={style(field.key)}>{field.label}{field.unit&&<small>{field.unit}</small>}<span role="separator" tabIndex={0} aria-label={`Resize ${field.label}`} aria-orientation="vertical" aria-valuemin={88} aria-valuemax={600} aria-valuenow={width(field.key)} onKeyDown={event=>{if(!["ArrowLeft","ArrowRight","Home","End"].includes(event.key))return;event.preventDefault();onLayout({...layout,widths:{...layout.widths,[field.key]:event.key==="Home"?88:event.key==="End"?600:Math.max(88,Math.min(600,width(field.key)+(event.key==="ArrowLeft"?-16:16)))}});}} onPointerDown={event=>{drag.current={key:field.key,x:event.clientX,width:width(field.key)};event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>{if(drag.current)onLayout({...layout,widths:{...layout.widths,[field.key]:Math.max(88,Math.min(600,drag.current.width+event.clientX-drag.current.x))}});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}/></th>)}</tr></thead>
    <tbody>{start>0&&<tr aria-hidden="true"><td colSpan={shown.length+1} style={{height:start*36,padding:0}}/></tr>}{rows.slice(start,end).map(({row,section},local)=>{const index=start+local;const cellProps=(column:string,columnIndex:number)=>({"data-row":row.key,"data-column":column,tabIndex:layout.focus?layout.focus.row===row.key&&layout.focus.column===column?0:-1:index===0&&columnIndex===0?0:-1,onFocus:()=>onLayout({...layout,focus:{row:row.key,column}})});return <tr onKeyDown={event=>{const target=(event.target as HTMLElement).closest<HTMLElement>("[data-column]");if(!target)return;const columnIndex=target.dataset.column==="$row"?0:shown.findIndex(field=>field.key===target.dataset.column)+1;const delta:{[key:string]:[number,number]}={ArrowDown:[1,0],ArrowUp:[-1,0],ArrowLeft:[0,-1],ArrowRight:[0,1],PageDown:[20,0],PageUp:[-20,0]};if(delta[event.key]){event.preventDefault();focusCell(index+delta[event.key][0],Math.max(0,Math.min(shown.length,columnIndex+delta[event.key][1])));}else if(event.key==="Home"||event.key==="End"){event.preventDefault();focusCell(event.ctrlKey?(event.key==="Home"?0:rows.length-1):index,event.key==="Home"?0:shown.length);}else if((event.key==="Enter"||event.key===" ")&&columnIndex>0){event.preventDefault();const button=scroll.current?.querySelector<HTMLButtonElement>(`button[data-row="${row.key}"]`);if(button)onPick(row,button);}}} key={row.key} aria-rowindex={index+2} aria-selected={projection.request.selected_row===row.key}><th scope="row" title={projection.request.group_by?section:undefined}><button {...cellProps("$row",0)} title={row.label} aria-pressed={projection.request.selected_row===row.key} onClick={event=>onPick(row,event.currentTarget)}><span>{row.label}</span><small>{row.contributor_count} evidence</small></button></th>{shown.map((field,columnIndex)=><td key={field.key} {...cellProps(field.key,columnIndex+1)} style={style(field.key)} className={field.role==="MEASURE"?"semantic-number":""} title={label(row.values[field.key],field)}><span>{label(row.values[field.key],field)}</span></td>)}</tr>;})}{end<rows.length&&<tr aria-hidden="true"><td colSpan={shown.length+1} style={{height:(rows.length-end)*36,padding:0}}/></tr>}</tbody>
   </table>{!rows.length&&<p>No retained rows match these selections. This is not a zero result.</p>}
  </div>
  <footer className="semantic-grid-status">{rows.length} retained rows · Arrow keys move · Enter opens evidence · Home / End · Page Up / Down</footer>
 </div>;
}
