"use client";
import {useEffect,useId,useMemo,useRef,useState} from "react";
import type {CanonicalResource} from "@finai/contracts";
import {createOntologyClient} from "@g8/ontology-client";
import type {SourceAccountNavigation} from "./seg-account-observations";
import {checkedPrepared,checkedSnapshot,requestKey,sameRef,type AdoptionDefinition,type AdoptionSelection,type FamilyDefinition,type Prepared,type Ref,type Selection,type SourceSnapshot} from "./source-adoption-types";
import "./source-adoption-workbench.css";
type Props=SourceAccountNavigation&{token:string;companyId:string;binding:Ref;sourceLabel:string;eligible:boolean;canPropose:boolean;onProposal:(id:string)=>void};
const pin=(resource:Ref):Ref=>({resource_id:resource.resource_id,version_id:resource.version_id});
const human=(value:unknown)=>typeof value==="string"?value.toLowerCase().replaceAll("_"," "):"Not established";
export default function SourceAdoptionWorkbench(props:Props){const [open,setOpen]=useState(false);return <details className="source-adoption" onToggle={event=>setOpen(event.currentTarget.open)}><summary>Recurring source review</summary>{open&&<Review key={`${props.companyId}:${props.binding.version_id}:${props.token}`} {...props}/>}</details>;}
function Review({token,companyId,binding,sourceLabel,eligible,canPropose,onProposal,onInspectResource,onTraceResource}:Props){
  const id=useId();const client=useMemo(()=>createOntologyClient({baseUrl:"/api/ontology",getToken:()=>token}),[token]);
  const [catalog,setCatalog]=useState<{families:CanonicalResource[];adoptions:CanonicalResource[];total:number}|null>(null);const [catalogError,setCatalogError]=useState("");const [revision,setRevision]=useState(0);
  const [search,setSearch]=useState("");const [query,setQuery]=useState("");const [familyId,setFamilyId]=useState("");const [predecessorId,setPredecessorId]=useState("");
  const [mode,setMode]=useState<"family"|"transition">("transition");const [name,setName]=useState("");const [familyKey,setFamilyKey]=useState("");const [system,setSystem]=useState("");const [policy,setPolicy]=useState<AdoptionSelection["policy"]|"">("");const [rationale,setRationale]=useState("");
  const [preview,setPreview]=useState<{key:string;selection:Selection;value:Prepared}|null>(null);const [reopened,setReopened]=useState<SourceSnapshot|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const pending=useRef<AbortController|null>(null);
  useEffect(()=>()=>pending.current?.abort(),[]);
  useEffect(()=>{const controller=new AbortController();const now=new Date().toISOString();
    void Promise.all(["SourceFamily","SourceSnapshotAdoption"].map(object_type=>client.query({object_type,search:query,filters:[{field:"company_id",operator:"eq",value:companyId}],traversal:[],offset:0,limit:100,valid_at:now,known_at:now},{signal:controller.signal}))).then(([families,adoptions])=>{if(!controller.signal.aborted){const approved=(items:CanonicalResource[])=>items.filter(item=>item.authority_state==="APPROVED"&&item.attributes.company_id===companyId);setCatalog({families:approved(families.objects),adoptions:approved(adoptions.objects),total:Math.max(families.total,adoptions.total)});setCatalogError("");}}).catch(cause=>{if(!controller.signal.aborted)setCatalogError(cause instanceof Error?cause.message:"Recurring source review is unavailable.");});
    return()=>controller.abort();
  },[client,companyId,query,revision]);
  const family=catalog?.families.find(item=>item.version_id===familyId);
  const predecessors:{key:string;label:string;binding:Ref;adoption?:Ref}[]=[];
  if(family){try{const definition=family.attributes.definition as FamilyDefinition;const baseline=checkedSnapshot(definition.baseline,companyId);predecessors.push({key:baseline.binding.version_id,label:`Original source · ${baseline.worksheet} · ${baseline.observed_from}–${baseline.observed_through}`,binding:baseline.binding});
    for(const adoption of catalog?.adoptions??[]){if(adoption.attributes.family_id!==family.resource_id)continue;const source=checkedSnapshot((adoption.attributes.definition as AdoptionDefinition).successor,companyId);predecessors.push({key:adoption.version_id,label:`Reviewed successor · ${source.worksheet} · ${source.observed_from}–${source.observed_through}`,binding:source.binding,adoption:pin(adoption)});}
  }catch{/* Unsupported catalog definitions cannot be selected as compatibility authority. */}}
  const predecessor=predecessors.find(item=>item.key===predecessorId);
  let selection:Selection|null=null;
  if(rationale.trim().length>=10&&eligible){if(mode==="family"&&name.trim().length>=3&&/^[A-Za-z0-9][A-Za-z0-9_.:-]{2,95}$/.test(familyKey)&&/^[A-Za-z0-9][A-Za-z0-9_.:-]{0,95}$/.test(system))selection={family_key:familyKey,source_system:system,display_name:name.trim(),baseline_binding:pin(binding),rationale:rationale.trim()};
    else if(mode==="transition"&&family&&predecessor&&policy&&!sameRef(predecessor.binding,binding))selection={family:pin(family),predecessor_binding:pin(predecessor.binding),successor_binding:pin(binding),predecessor_adoption:predecessor.adoption??null,policy,rationale:rationale.trim()};}
  const key=requestKey(selection);const current=preview?.key===key?preview:null;
  async function request(path:string,body:unknown){pending.current?.abort();const controller=new AbortController();pending.current=controller;const timer=setTimeout(()=>controller.abort(),25000);try{const response=await fetch(`/api/ontology/source-adoption/${path}`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(body),signal:controller.signal});const data=await response.json();if(!response.ok)throw Error(response.status===404?"Recurring source review is not available in this runtime yet.":typeof data.detail==="string"?data.detail:`Source review unavailable (${response.status}).`);controller.signal.throwIfAborted();return data;}finally{clearTimeout(timer);}}
  async function inspect(){if(!selection)return;setBusy(true);setError("");setPreview(null);setReopened(null);try{const result=await request(`${mode==="family"?"families":"transitions"}/inspect`,selection);setPreview({key,selection,value:checkedPrepared(result,selection,companyId)});}catch(cause){setError(cause instanceof Error?cause.message:"Inspection unavailable");}finally{setBusy(false);}}
  async function propose(){if(!current||!canPropose)return;setBusy(true);setError("");try{const result=await request(`${"baseline_binding" in current.selection?"families":"transitions"}/proposal`,current.selection);if(typeof result.proposal?.proposal_id!=="string")throw Error("The canonical proposal response is unavailable. Refresh before retrying.");onProposal(result.proposal.proposal_id);}catch(cause){setError(cause instanceof Error?cause.message:"Proposal unavailable");}finally{setBusy(false);}}
  async function reopen(adoption:CanonicalResource){setBusy(true);setError("");setReopened(null);try{const result=await request("successor",pin(adoption));if(result.accounting_aggregation_authorized!==false||!result.adoption||!sameRef(result.adoption,adoption))throw Error("The accepted successor reference changed.");const definition=adoption.attributes.definition as AdoptionDefinition;if(requestKey(result.source)!==requestKey(definition.successor)||!sameRef(result.family,definition.family)||result.policy!==definition.selection.policy)throw Error("The successor metadata no longer matches its reviewed adoption.");setReopened(checkedSnapshot(result.source,companyId));}catch(cause){setError(cause instanceof Error?cause.message:"Successor unavailable");}finally{setBusy(false);}}
  const navigation={onInspectResource,onTraceResource};
  return <section aria-label="Recurring source review"><header><h4>Review a recurring source</h4><p>Current source: {sourceLabel}. Reuse requires an explicit reviewed relationship; similar layouts do not establish compatibility.</p></header>
    <form className="source-adoption-search" onSubmit={event=>{event.preventDefault();if(busy)return;setCatalog(null);setCatalogError("");setQuery(search.trim());setRevision(value=>value+1);setFamilyId("");setPredecessorId("");}}><label>Find reviewed family or successor<input value={search} onChange={event=>setSearch(event.target.value)} maxLength={200}/></label><button disabled={busy}>Find / refresh</button></form>
    {!catalog&&!catalogError&&<p role="status">Loading this company’s reviewed source families…</p>}{catalogError&&<p role="alert">Recurring source catalog unavailable: {catalogError}</p>}{catalog&&catalog.total>100&&<p>Results are limited to 100 per category. Refine the name above to find another family or successor.</p>}
    <div className="source-adoption-mode"><button disabled={busy} aria-pressed={mode==="transition"} onClick={()=>setMode("transition")}>Review next snapshot</button><button disabled={busy} aria-pressed={mode==="family"} onClick={()=>setMode("family")}>Define source family</button></div>
    <fieldset disabled={busy}><legend>{mode==="family"?"Stable source family":"Candidate source relationship"}</legend>
      {mode==="family"?<div className="source-adoption-fields"><label>Family name<input value={name} onChange={event=>setName(event.target.value)} maxLength={200}/></label><label>Family code<input value={familyKey} onChange={event=>setFamilyKey(event.target.value)} maxLength={96} placeholder="A stable, readable code"/></label><label>Source system<input value={system} onChange={event=>setSystem(event.target.value)} maxLength={96}/></label><p>This source’s exact reviewed binding becomes the baseline. Company and accounting interpretation are read from accepted resources.</p></div>:<><label htmlFor={`${id}-family`}>Reviewed family</label><select id={`${id}-family`} value={familyId} onChange={event=>{setFamilyId(event.target.value);setPredecessorId("");}}><option value="">Choose a reviewed family</option>{catalog?.families.map(item=><option key={item.version_id} value={item.version_id}>{item.display_name}</option>)}</select>{catalog&&!catalog.families.length&&<p>No matching reviewed family is available. Define one from an eligible baseline source first.</p>}
      <label htmlFor={`${id}-prior`}>Predecessor snapshot</label><select id={`${id}-prior`} value={predecessorId} onChange={event=>setPredecessorId(event.target.value)}><option value="">Choose the exact predecessor</option>{predecessors.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select>{predecessor&&sameRef(predecessor.binding,binding)&&<p>A successor must be a distinct retained source. Open the later or replacement source to review it.</p>}
      <label htmlFor={`${id}-policy`}>Coverage policy</label><select id={`${id}-policy`} value={policy} onChange={event=>setPolicy(event.target.value as typeof policy)}><option value="">Choose how this source relates to its predecessor</option><option value="DISJOINT_PERIOD_ADDITION">Add a later, non-overlapping period</option><option value="REPLACES_PREDECESSOR_SNAPSHOT">Replace the predecessor snapshot for the same period</option></select></>}
      <label htmlFor={`${id}-reason`}>Evidence and reason for this relationship</label><textarea id={`${id}-reason`} value={rationale} onChange={event=>setRationale(event.target.value)} minLength={10} maxLength={2000}/>
    </fieldset>
    {!eligible&&<p role="status">This source needs an eligible reviewed accounting binding before recurring-source review.</p>}
    <div className="source-adoption-actions"><button disabled={busy||!selection} onClick={()=>void inspect()}>Inspect source comparison</button>{current&&canPropose&&<button disabled={busy} onClick={()=>void propose()}>Propose this relationship for review</button>}</div>
    {busy&&<p role="status">Checking exact retained source versions…</p>}{error&&<p role="alert">{error}</p>}
    {current&&<section aria-label="Server-derived source comparison"><h4>{current.value.display_name}</h4><div className="source-adoption-comparison">{"baseline" in current.value.attributes.definition?<Snapshot title="Family baseline" source={current.value.attributes.definition.baseline} {...navigation}/>:<><Snapshot title="Predecessor" source={current.value.attributes.definition.predecessor} {...navigation}/><Snapshot title="Candidate successor" source={current.value.attributes.definition.successor} {...navigation}/></>}</div><p>The server derived these snapshots from retained bytes and reviewed versions. This proposal does not authorize aggregation or certify completeness.</p></section>}
    {!!catalog?.adoptions.length&&<details><summary>Accepted successor snapshots</summary>{catalog.adoptions.map(item=><div className="source-adoption-accepted" key={item.version_id}><span>{item.display_name}</span><button disabled={busy} onClick={()=>void reopen(item)}>Open accepted successor</button></div>)}</details>}
    {reopened&&<section aria-label="Accepted successor source"><Snapshot title="Accepted successor · its own period" source={reopened} {...navigation}/><p>This is the successor’s retained source context. No period or totals have been inherited from its predecessor.</p></section>}
  </section>;
}
function Snapshot({title,source,onInspectResource,onTraceResource}:{title:string;source:SourceSnapshot}&SourceAccountNavigation){return <article><h5>{title}</h5><dl><dt>Source</dt><dd>{source.worksheet} · {human(source.source_profile)}</dd><dt>Reviewed period</dt><dd>{source.period_starts_on}–{source.period_ends_on}</dd><dt>Observed dates</dt><dd>{source.observed_from}–{source.observed_through}</dd><dt>Source rows</dt><dd>{source.source_rows}</dd><dt>Missing posted amounts</dt><dd>{source.missing_amount_count}{source.missing_amount_count>0&&<small>{source.missing_amount_coordinates.join(", ")}{source.missing_amount_count>100?" · first 100 coordinates":""}</small>}</dd><dt>Amount meaning</dt><dd>{human(source.meaning.amount_semantics)} · {human(source.meaning.vat_treatment)}</dd><dt>Coverage</dt><dd>Completeness unestablished</dd></dl><div className="source-adoption-actions">{onInspectResource&&<button onClick={()=>onInspectResource(source.scope)}>Inspect source scope</button>}{onTraceResource&&<button onClick={()=>onTraceResource(source.evidence)}>Trace original evidence</button>}</div><details><summary>Exact source, schema and mapping identities</summary><pre>{JSON.stringify({document_id:source.document_id,source_sha256:source.source_sha256,schema_sha256:source.schema_sha256,company:source.company,chart:source.chart,binding:source.binding,period:source.period,meaning:source.meaning},null,2)}</pre></details></article>;}
