"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import type {AnalysisPin,AnalysisProjection,FinancialMetricResult,InvestigationActionRequest,InvestigationOperation,RetainedSourceException,SourceExceptionRequest} from "@finai/contracts";
import {assertInvestigation,investigationRequest,assertSourceException,parseSourceException,savedSourceException,sourceExceptionChoices,sourceExceptionHistory,sourceExceptionRequest,type SavedSourceException} from "./source-exception-state";
import "./source-exception-review.css";
type Props={token:string;companyId:string;metrics:FinancialMetricResult;projection:AnalysisProjection;onProposal?:(id:string)=>void;onInspectReference?:(pin:AnalysisPin,knownAt:string)=>void;onSource:()=>void};
const reason=(value:unknown)=>value instanceof Error?value.message:"Source exception evidence is unavailable.";
async function payload(response:Response){if(!response.ok)throw Error(response.status===403?"You do not have permission to review this evidence.":response.status===409?"This source or journal revision was refused. Reopen its exact source review.":"The exact source evidence could not be read. Retry the unchanged request.");return response.json();}
export default function SourceExceptionReview(props:Props){return <Review key={`${props.token}:${props.companyId}:${props.metrics.result_sha256}:${props.projection.descriptor_sha256}`} {...props}/>;}
function Review({token,companyId,metrics,projection,onProposal,onInspectReference,onSource}:Props){
 const choices=useMemo(()=>{try{return {values:sourceExceptionChoices(metrics,projection,companyId),error:""};}catch(failure){return {values:[],error:reason(failure)};}},[metrics,projection,companyId]);
 const [selected,setSelected]=useState(""),[frozen,setFrozen]=useState<SourceExceptionRequest|null>(null),[exception,setException]=useState<RetainedSourceException|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [saved,setSaved]=useState<SavedSourceException|null>(null),[storageKey,setStorageKey]=useState(""),[storageError,setStorageError]=useState("");
 const pending=useRef<AbortController|null>(null);
 useEffect(()=>()=>{pending.current?.abort();pending.current=null;},[]);
 useEffect(()=>{let disposed=false;void crypto.subtle.digest("SHA-256",new TextEncoder().encode(token)).then(bytes=>{if(disposed)return;const actor=Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,"0")).join(""),key=`g8:source-exception:1:${actor}:${companyId}:${metrics.invocation_id}:${metrics.result_sha256}`;setStorageKey(key);try{const raw=localStorage.getItem(key);if(raw){const value=parseSourceException(raw,metrics,projection,companyId);setSaved(value);if(!value)setStorageError("The saved exception reference differs from this financial snapshot.");}}catch{setStorageError("Reference storage is unavailable.");}}).catch(()=>{if(!disposed)setStorageError("Reference storage is unavailable.");});return()=>{disposed=true;};},[token,companyId,metrics,projection]);
 async function read(historical?:SavedSourceException){if(pending.current)return;let request:SourceExceptionRequest;try{request=historical?.request??frozen??sourceExceptionRequest(metrics,projection,companyId,selected);}catch(failure){setError(reason(failure));return;}
  setFrozen(request);setSelected(request.coordinate);setException(null);setError("");setNotice("");setBusy(true);const controller=new AbortController();pending.current=controller;const timer=setTimeout(()=>controller.abort(),25000);
  try{const headers={Authorization:`Bearer ${token}`};const history=await payload(await fetch(`/api/ontology/functions/invocations/${request.invocation_id}`,{headers,cache:"no-store",signal:controller.signal}));const source=sourceExceptionHistory(history,metrics,projection);
   const value=await payload(await fetch(historical?`/api/ontology/source-exceptions/${historical.runId}`:"/api/ontology/source-exceptions",{method:historical?"GET":"POST",headers:{...headers,...(!historical?{"Content-Type":"application/json"}:{})},...(!historical?{body:JSON.stringify(request)}:{}),cache:"no-store",signal:controller.signal}));assertSourceException(value,request,metrics,projection,source,historical?.runId);if(historical&&(value.receipt_hash!==historical.receiptHash||source.receiptHash!==historical.sourceReceiptHash))throw Error("The saved exception revision changed.");if(pending.current===controller){setException(value);setNotice(historical?"Exact historical exception reopened.":"Source exception retained for the selected journal snapshot.");}
  }catch(failure){if(pending.current===controller)setError(controller.signal.aborted?"The evidence request timed out. Retry its unchanged inputs.":reason(failure));}finally{clearTimeout(timer);if(pending.current===controller){pending.current=null;setBusy(false);}}
 }
 function save(){if(!exception||!frozen||!storageKey)return;try{const reference=savedSourceException(exception,frozen,metrics);localStorage.setItem(storageKey,JSON.stringify(reference));setSaved(reference);setStorageError("");setNotice("Historical reference saved on this device; source values were not copied.");}catch{setStorageError("The exception reference could not be saved.");}}
 return <details className="source-exception-review"><summary>Review unmatched source evidence{choices.values.length?` · ${choices.values.length} returned coordinates`:""}</summary>
  <p>These are source cells the server found without an accepted journal at this fixed snapshot. Financial impact and materiality remain unassessed.</p>
  {choices.error?<p role="alert">{choices.error}</p>:!choices.values.length?<p>No eligible missing coordinates were returned. Partial coverage alone does not establish an exception.</p>:<div className="source-exception-actions"><label>Missing source cell<select value={selected} disabled={busy||Boolean(frozen)} onChange={e=>setSelected(e.target.value)}><option value="">Choose a returned source cell</option>{choices.values.map(value=><option key={value} value={value}>{value}</option>)}</select></label><button disabled={busy||!selected} onClick={()=>void read()}>{frozen?"Retry exact retention":"Retain source exception"}</button>{frozen&&<button disabled={busy} onClick={()=>{setFrozen(null);setException(null);setError("");setNotice("");}}>Choose another source cell</button>}</div>}
  {saved&&<button disabled={busy} onClick={()=>void read(saved)}>Reopen saved exception</button>}{busy&&<p role="status">Reading exact source and journal evidence…</p>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{storageError&&<p role="status">{storageError}</p>}
  {exception&&<section aria-label="Retained source exception"><h4>Unmatched at the retained snapshot</h4><dl><div><dt>Worksheet</dt><dd>{exception.source.sheet}</dd></div><div><dt>Source row</dt><dd>{exception.source.row}</dd></div><div><dt>Source cell</dt><dd>{exception.source.coordinate}</dd></div><div><dt>Journal observation</dt><dd>{new Date(exception.journal_observed_at).toLocaleString()}</dd></div></dl><div className="source-exception-actions"><button disabled={!storageKey} onClick={save}>Save historical reference</button>{onInspectReference&&<button onClick={()=>onInspectReference(exception.source.evidence,exception.source_known_at)}>Inspect retained source evidence</button>}<button onClick={onSource}>Open financial source review</button></div><InvestigationReview key={`${exception.run_id}:${storageKey}`} token={token} exception={exception} storageKey={storageKey} onProposal={onProposal}/><details><summary>Advanced · exact source, clocks and retained exception</summary><pre>{JSON.stringify({request:frozen,result:exception},null,2)}</pre></details></section>}
 </details>;
}

function InvestigationReview({token,exception,storageKey,onProposal}:{token:string;exception:RetainedSourceException;storageKey:string;onProposal?:Props["onProposal"]}){
 const key=storageKey?`${storageKey}:investigation:${exception.run_id}:${exception.receipt_hash}`:"";
 const [stored]=useState(()=>{if(!key)return {id:"",error:""};try{const id=localStorage.getItem(key)??"";if(id&&!/^opa_[a-f0-9]{64}$/.test(id))throw Error();return {id,error:""};}catch{return {id:"",error:"The saved investigation reference is unavailable."};}});
 const [rationale,setRationale]=useState(""),[frozen,setFrozen]=useState<InvestigationActionRequest|null>(null),[operation,setOperation]=useState<InvestigationOperation|null>(null),[savedId,setSavedId]=useState(stored.id),[busy,setBusy]=useState(false),[error,setError]=useState(stored.error);
 const pending=useRef<AbortController|null>(null);
 useEffect(()=>()=>{pending.current?.abort();pending.current=null;},[]);
 async function act(mode:"create"|"read"|"resume"){
  if(pending.current)return;let request:InvestigationActionRequest|null=null;try{if(mode==="create"){request=frozen??investigationRequest(crypto.randomUUID(),exception,rationale);setFrozen(request);}}catch(failure){setError(reason(failure));return;}
  const operationId=operation?.operation_id??savedId;if(mode!=="create"&&!operationId)return;const controller=new AbortController();pending.current=controller;const timer=setTimeout(()=>controller.abort(),25000);setBusy(true);setError("");setOperation(null);
  try{const url=mode==="create"?"/api/ontology/operations/investigations":`/api/ontology/operations/${operationId}${mode==="resume"?"/resume":""}`;const value=await payload(await fetch(url,{method:mode==="read"?"GET":"POST",headers:{Authorization:`Bearer ${token}`,...(request?{"Content-Type":"application/json"}:{})},...(request?{body:JSON.stringify(request)}:{}),cache:"no-store",signal:controller.signal}));assertInvestigation(value,exception,request?{request}:{operationId});if(pending.current===controller){setOperation(value);setSavedId(value.operation_id);if(key)try{localStorage.setItem(key,value.operation_id);}catch{setError("Investigation returned, but its reference could not be saved on this device.");}}}
  catch(failure){if(pending.current===controller)setError(controller.signal.aborted?"Investigation request timed out. Retry its exact retained inputs.":reason(failure));}finally{clearTimeout(timer);if(pending.current===controller){pending.current=null;setBusy(false);}}
 }
 return <section className="source-investigation"><h4>Investigate this evidence</h4><p>Create a proposal for governed review. No automatic approval, journal posting or financial impact follows.</p><label>Reason for investigation<textarea value={rationale} maxLength={2000} disabled={busy||Boolean(frozen)} onChange={e=>setRationale(e.target.value)} rows={3}/></label><div className="source-exception-actions"><button disabled={busy||!frozen&&rationale.trim().length<10} onClick={()=>void act("create")}>{frozen?"Retry exact proposal request":"Create investigation proposal"}</button>{savedId&&<button disabled={busy} onClick={()=>void act("read")}>Reopen investigation</button>}</div>{busy&&<p role="status">Reading governed investigation state…</p>}{error&&<p role="alert">{error}</p>}
  {operation&&<><p role="status">{operation.state==="PUBLISHED"?"Finding and investigation published; both remain open.":operation.state==="PENDING_REVIEW"?"Proposal awaits independent review.":operation.state==="PREPARED"?"Proposal prepared; submission is not yet confirmed.":operation.state==="REJECTED"?"The proposal was rejected.":"Approval does not establish publication. Exact published versions are unavailable."}</p><p>Retained proposal rationale: {operation.frozen_rationale}</p>{frozen&&frozen.rationale!==operation.frozen_rationale&&<p>This action reused an existing effect. The original proposal rationale remains unchanged.</p>}<div className="source-exception-actions">{operation.proposal&&onProposal&&<button onClick={()=>onProposal(operation.prepared_proposal_id)}>Open existing review</button>}{operation.state==="PREPARED"&&<button disabled={busy} onClick={()=>void act("resume")}>Resume proposal submission</button>}<button disabled={busy} onClick={()=>void act("read")}>Refresh review and publication</button></div><details><summary>Advanced · exact action, proposal and publication</summary><pre>{JSON.stringify({request:frozen,operation},null,2)}</pre></details></>}
 </section>;
}
