import type {AnalysisProjection,FinancialMetricResult,InvestigationActionRequest,InvestigationOperation,RetainedSourceException,SourceExceptionRequest} from "@finai/contracts";
import {assertHomeFinancialMetrics} from "./company-financial-metric-state";
import {completedMetricSource,assertMetricCompany,metricCanonical,metricPin,metricRecord,sameMetricPin,type MetricSource} from "./metric-observation-state";
import {restorationInstant} from "./definition-restoration-time";
const hash=/^[a-f0-9]{64}$/,run=/^fcr_[a-f0-9]{64}$/,uuid=/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i;
const sameTime=(a:unknown,b:unknown)=>Boolean(restorationInstant(a)&&restorationInstant(a)===restorationInstant(b));
function refuse():never{throw Error("The source exception does not match the selected company, source cell and journal snapshot.");}
export function sourceExceptionChoices(metrics:FinancialMetricResult,projection:AnalysisProjection,companyId:string):string[]{
 assertHomeFinancialMetrics(metrics,{company_id:companyId,invocation_id:projection.descriptor.invocation_id,snapshot_at:metrics.snapshot_at,expected_reconciliation_sha256:projection.descriptor.receipt_hash,expected_result_sha256:metrics.result_sha256},projection);
 const values=metrics.coverage.missing_coordinates;
 if(!Array.isArray(values)||values.length>5000||values.some(v=>typeof v!=="string"||v.length>300||!/^.+![A-Z]+[1-9][0-9]*$/.test(v))||new Set(values).size!==values.length)refuse();
 return [...values];
}
export function sourceExceptionRequest(metrics:FinancialMetricResult,projection:AnalysisProjection,companyId:string,coordinate:string):SourceExceptionRequest {
 if(!sourceExceptionChoices(metrics,projection,companyId).includes(coordinate))refuse();
 return {company_id:companyId,invocation_id:metrics.invocation_id,journal_snapshot_at:metrics.snapshot_at,expected_reconciliation_receipt_hash:metrics.reconciliation_receipt_hash,coordinate};
}
export function sourceExceptionHistory(value:unknown,metrics:FinancialMetricResult,projection:AnalysisProjection):MetricSource {
 const source=completedMetricSource(value);assertMetricCompany(source,metrics.company_id);
 if(source.invocationId!==metrics.invocation_id||!sameMetricPin(source.function,metrics.source_function)||!sameTime(source.validAt,projection.descriptor.valid_at)||!sameTime(source.knownAt,projection.descriptor.known_at))refuse();return source;
}
export function assertSourceException(value:unknown,request:SourceExceptionRequest,metrics:FinancialMetricResult,projection:AnalysisProjection,source:MetricSource,expectedRun?:string):asserts value is RetainedSourceException {
 const v=value as RetainedSourceException;
 assertMetricCompany(source,request.company_id);
 if(!v||v.contract!=="source-reconciliation-exception/1"||v.detector!=="source-reconciliation-exceptions/1"||v.calculation_runtime!==v.detector||!run.test(v.run_id)||expectedRun&&v.run_id!==expectedRun||!hash.test(v.receipt_hash)||metricCanonical(v.scope)!==metricCanonical(source.output.scope)||!Array.isArray(v.read_permissions)||v.read_permissions.some(p=>typeof p!=="string")||!sameMetricPin(v.company,projection.descriptor.company)||!sameMetricPin(v.source_function,metrics.source_function)||!sameMetricPin(v.binding,metrics.binding)||metricCanonical(v.selection)!==metricCanonical(metrics.selection))refuse();
 if(!Array.isArray(v.context_versions)||v.context_versions.length!==7||!v.context_versions.every(metricPin)||new Set(v.context_versions.map(p=>p.resource_id)).size!==7||Object.values(metrics.selection).some(ref=>!v.context_versions.some(p=>p.resource_id===ref.resource_id&&p.version_id===ref.version_id))||!v.context_versions.some(p=>sameMetricPin(p,v.company)))refuse();
 for(const pin of projection.descriptor.definitions){const context=v.context_versions.find(p=>p.resource_id===pin.resource_id);if(context&&!sameMetricPin(context,pin))refuse();}
 const cell=v.source;
 if(!cell||cell.invocation_id!==request.invocation_id||cell.invocation_id!==source.invocationId||cell.invocation_receipt_hash!==source.receiptHash||cell.source_receipt_hash!==metrics.source_receipt_hash||cell.sha256!==metrics.source_sha256||cell.coordinate!==request.coordinate||typeof cell.sheet!=="string"||cell.coordinate.slice(0,cell.coordinate.lastIndexOf("!"))!==cell.sheet||!Number.isSafeInteger(cell.row)||cell.row<1||String(cell.row)!==/[0-9]+$/.exec(cell.coordinate)?.[0]||!metricPin(cell.evidence)||!uuid.test(cell.document_id)||!sameTime(v.source_valid_at,source.validAt)||!sameTime(v.source_known_at,source.knownAt)||!sameTime(v.journal_observed_at,request.journal_snapshot_at)||v.reconciliation?.receipt_hash!==metrics.reconciliation_receipt_hash||v.reconciliation.status!==metrics.coverage.state||v.financial_impact!==null||v.materiality!=="UNASSESSED"||v.automatic_resolution!==false||v.current_use_authorized!==false||v.business_effect_authorized!==false)refuse();
 const document=metricRecord(source.output.source_document);
 if(!sameMetricPin(cell.evidence,document.evidence)||cell.document_id!==document.document_id||cell.sheet!==document.sheet||cell.sha256!==document.sha256)refuse();
 if(v.state!=="UNMATCHED_AT_SNAPSHOT"||v.finding_eligible!==true||v.exclusion_reason!==null||!Array.isArray(v.matched_journals)||v.matched_journals.length!==0||!metrics.coverage.missing_coordinates.includes(cell.coordinate))refuse();
}
export type SavedSourceException={version:1;runId:string;receiptHash:string;request:SourceExceptionRequest;metricResultHash:string;sourceReceiptHash:string};
export function savedSourceException(value:RetainedSourceException,request:SourceExceptionRequest,metrics:FinancialMetricResult):SavedSourceException{return {version:1,runId:value.run_id,receiptHash:value.receipt_hash,request:{company_id:request.company_id,invocation_id:request.invocation_id,journal_snapshot_at:request.journal_snapshot_at,expected_reconciliation_receipt_hash:request.expected_reconciliation_receipt_hash,coordinate:request.coordinate},metricResultHash:metrics.result_sha256,sourceReceiptHash:value.source.invocation_receipt_hash};}
export function parseSourceException(raw:string,metrics:FinancialMetricResult,projection:AnalysisProjection,companyId:string):SavedSourceException|null{try{const v=JSON.parse(raw) as SavedSourceException,r=sourceExceptionRequest(metrics,projection,companyId,v.request.coordinate);if(v.version!==1||!run.test(v.runId)||!hash.test(v.receiptHash)||!hash.test(v.sourceReceiptHash)||v.metricResultHash!==metrics.result_sha256||metricCanonical(r)!==metricCanonical(v.request))return null;return {version:1,runId:v.runId,receiptHash:v.receiptHash,request:r,metricResultHash:v.metricResultHash,sourceReceiptHash:v.sourceReceiptHash};}catch{return null;}}

export function investigationRequest(id:string,exception:RetainedSourceException,rationale:string):InvestigationActionRequest {
 if(!uuid.test(id)||!run.test(exception.run_id)||exception.state!=="UNMATCHED_AT_SNAPSHOT"||exception.finding_eligible!==true||rationale.trim().length<10||rationale.trim().length>2000)throw Error("Select retained unmatched evidence and explain why investigation is needed.");return {request_id:id,exception_run_id:exception.run_id,rationale:rationale.trim()};
}
export function assertInvestigation(value:unknown,exception:RetainedSourceException,expected:{request?:InvestigationActionRequest;operationId?:string}):asserts value is InvestigationOperation {
 const v=value as InvestigationOperation,d=metricRecord(v?.definition),p=metricRecord(metricRecord(v?.proposal).proposal);
 if(!v||!/^opa_[a-f0-9]{64}$/.test(v.operation_id)||expected.operationId&&v.operation_id!==expected.operationId||!uuid.test(v.prepared_proposal_id)||!uuid.test(v.finding_id)||!uuid.test(v.investigation_id)||v.finding_id===v.investigation_id||v.current_use_authorized!==false||v.business_effect_authorized!==false||d.version!=="ontology-action/1"||d.kind!=="SOURCE_EXCEPTION_INVESTIGATION"||d.exception_run_id!==exception.run_id||d.company_id!==exception.company.resource_id||d.effect!=="CANONICAL_RESOURCE_PROPOSAL"||d.publication!=="EXISTING_RESOURCE_REVIEW"||!["PREPARED","PENDING_REVIEW","REJECTED","PUBLISHED","PUBLICATION_UNAVAILABLE"].includes(v.state)||typeof v.frozen_rationale!=="string"||v.frozen_rationale.length<10||!Array.isArray(v.events))refuse();
 if(expected.request){const r=v.intent_request;if(!r||r.request_id!==expected.request.request_id||r.exception_run_id!==exception.run_id||r.rationale!==expected.request.rationale||(r.expected_finding_version_id??null)!==(expected.request.expected_finding_version_id??null)||(r.expected_investigation_version_id??null)!==(expected.request.expected_investigation_version_id??null))refuse();}
 if(v.state!=="PREPARED"&&v.proposal===null)refuse();
 if(v.proposal!==null){if(p.proposal_id!==v.prepared_proposal_id||p.rationale!==v.frozen_rationale||!Array.isArray(p.mutations)||p.mutations.length!==2)refuse();const mutations=p.mutations.map(metricRecord);for(const kind of ["Finding","Investigation"]){const matches=mutations.filter(m=>m.object_type===kind);if(matches.length!==1)refuse();const m=matches[0],definition=metricRecord(metricRecord(m.attributes).definition);if(m.resource_id!==(kind==="Finding"?v.finding_id:v.investigation_id)||definition.exception_run_id!==exception.run_id||definition.exception_receipt_hash!==exception.receipt_hash||definition.contract!==(kind==="Finding"?"source-finding/1":"source-investigation/1")||definition.state!=="OPEN"||definition.automatic_resolution!==false)refuse();if(kind==="Finding"){const retained=Object.fromEntries(Object.entries(exception).filter(([key])=>!["run_id","scope","calculation_runtime","read_permissions"].includes(key)));if(metricCanonical(definition.evidence)!==metricCanonical(retained)||definition.financial_impact!==null||definition.materiality!=="UNASSESSED")refuse();}}}
 if(v.state==="PUBLISHED"){if(!v.publication||!metricPin(v.publication.finding)||!metricPin(v.publication.investigation)||v.publication.finding.resource_id!==v.finding_id||v.publication.investigation.resource_id!==v.investigation_id||metricRecord(v.proposal).decision!=="APPROVED")refuse();}else if(v.publication!==null)refuse();
}
