"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowDown,ArrowRight,Database,FileCsv,MagnifyingGlass,ShieldCheck} from "@phosphor-icons/react";
import type {IntakeItem,Principal,ReceiptDetail,SourcePreview} from "@finai/contracts";
import {Badge,Empty} from "./g8-ui";
import {readable} from "./g8-model";
import ArtifactPreservation from "./artifact-preservation";
import SourceAccountingContext from "./source-accounting-context";
import type {SourceAccountNavigation} from "./seg-account-observations";

export default function SourceExplorer({token,principal,sources,initialReceiptId,onReview,onSelect,companyId,onProposal,onInspectResource,onTraceResource}: {
  token:string;principal:Principal;sources:IntakeItem[];initialReceiptId?:string;onReview:(receiptId:string)=>void;onSelect:(source:IntakeItem)=>void;companyId?:string;onProposal?:(proposalId:string)=>void;
} & SourceAccountNavigation) {
  const [selected,setSelected]=useState(initialReceiptId ?? "");const [tab,setTab]=useState("rows");
  const [filter,setFilter]=useState("");const [query,setQuery]=useState("");const [search,setSearch]=useState("");const [offset,setOffset]=useState(0);
  const [preview,setPreview]=useState<SourcePreview|null>(null);const [detail,setDetail]=useState<ReceiptDetail|null>(null);
  const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [downloadError,setDownloadError]=useState("");
  const [accounting,setAccounting]=useState({receiptId:"",sheet:"",profile:""});
  const requestedReceiptId=initialReceiptId??selected;
  const current=requestedReceiptId?sources.find(item=>item.receipt_id===requestedReceiptId):sources[0];
  const receiptId=current?.receipt_id;
  const accountingChoice=accounting.receiptId===receiptId?accounting:{receiptId:receiptId??"",sheet:"",profile:""};
  const accountingSheets=detail&&detail.receipt.receipt_id===receiptId?detail.receipt.source_profile?.sheets??[]:[];
  function chooseAccounting(key:"sheet"|"profile",value:string){setAccounting({...accountingChoice,[key]:value});}
  const canExport=principal.permissions.includes("export");
  // Only deliberate source selection may replace the shared investigation context.
  const downloadRequest=useRef<AbortController|null>(null);
  useEffect(()=>()=>downloadRequest.current?.abort(),[token,receiptId]);
  useEffect(()=>{
    if(!receiptId)return;
    let cancelled=false;const controller=new AbortController();
    async function read<T>(path:string):Promise<T>{const response=await fetch(`/api/workspace/constructions/${receiptId}${path}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store",signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail === "string"?data.detail:"Source unavailable");return data;}
    async function load(){setBusy(true);setError("");setPreview(null);setDetail(null);
      const results=await Promise.allSettled([read<ReceiptDetail>(""),canExport?read<SourcePreview>(`/preview?offset=${offset}&search=${encodeURIComponent(search)}`):Promise.resolve(null)]);
      if(cancelled)return;
      if(results[0].status === "fulfilled")setDetail(results[0].value);else setError(results[0].reason instanceof Error?results[0].reason.message:"Review state unavailable");
      if(results[1].status === "fulfilled")setPreview(results[1].value);else setError(results[1].reason instanceof Error?results[1].reason.message:"Source preview unavailable");
      setBusy(false);
    }
    void load();return()=>{cancelled=true;controller.abort();};
  },[token,receiptId,offset,search,canExport]);
  async function download(){if(!current)return;downloadRequest.current?.abort();const controller=new AbortController();downloadRequest.current=controller;setDownloadError("");try{
    const response=await fetch(`/api/workspace/constructions/${current.receipt_id}/source`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store",signal:controller.signal});
    if(!response.ok)throw new Error("Original source could not be retrieved.");const blob=await response.blob();
    const hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",await blob.arrayBuffer())),b=>b.toString(16).padStart(2,"0")).join("");
    if(hash!==current.source_sha256)throw new Error("Integrity verification failed. Download withheld.");
    if(controller.signal.aborted)return;
    const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=current.filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }catch(error){if(!controller.signal.aborted)setDownloadError(error instanceof Error?error.message:"Download unavailable");}}
  if(!current&&requestedReceiptId)return <Empty title="Selected source is not in the loaded company inventory">Choose an available retained source to continue.{sources.map(source=><button className="g8-link" key={source.receipt_id} onClick={()=>{setSelected(source.receipt_id);onSelect(source);setOffset(0);setSearch("");setQuery("");}}>{source.filename}</button>)}</Empty>;
  if(!current)return <Empty title="Your sources belong here">Retained data will be searchable and inspectable here, with original values, quality findings and version lineage.</Empty>;
  return <section className="source-explorer" aria-label="Source data explorer"><aside className="source-browser"><header><Database size={18}/><strong>Sources</strong><Badge>{sources.length} loaded</Badge></header><label className="source-search"><MagnifyingGlass size={15}/><input aria-label="Find retained source" value={filter} onChange={event=>setFilter(event.target.value)} placeholder="Find a source…"/></label><div className="source-list">{sources.filter(item=>item.filename.toLowerCase().includes(filter.toLowerCase())).map(item=><button key={item.receipt_id} aria-pressed={current.receipt_id===item.receipt_id} onClick={()=>{setSelected(item.receipt_id);onSelect(item);setOffset(0);setSearch("");setQuery("");setDownloadError("");}}><FileCsv size={20}/><span>{item.filename}<small>{readable(item.source_class)} · {item.review_state.toLowerCase()}</small></span></button>)}</div><footer>Latest 50 receipts<br/>Original values are retained as text.</footer></aside><div className="source-canvas"><header className="source-heading"><div><p className="overline">RETAINED SOURCE</p><h2>{current.filename}</h2><p>{readable(current.source_class)} · {new Date(current.ingested_at).toLocaleString()}</p></div><button className="g8-icon" disabled={!canExport} aria-label="Download original source" onClick={()=>void download()}><ArrowDown size={20}/></button></header><div className="source-meta"><button className="g8-link" onClick={()=>onSelect(current)}>Inspect source<ArrowRight size={13}/></button><Badge tone={current.review_state==="APPROVED"?"good":"warning"}>{current.review_state}</Badge><span>{current.is_current?"Current accepted version":"Retained version"}</span><span>{preview?`${preview.total_rows} rows · ${preview.columns.length} columns`:busy?"Inspecting source":canExport?"Source preview unavailable":"Original cell access restricted"}</span>{preview&&<span className="source-verified"><ShieldCheck size={13}/> Integrity verified</span>}</div><ArtifactPreservation token={token} artifact={{kind:"SOURCE_RECEIPT",receipt_id:current.receipt_id}} canRecord={principal.permissions.includes("ontology_read")}/><div className="source-tabs" role="tablist" aria-label="Source views">{[["rows","Source rows"],["profile","Column profile"],["quality","Quality & review"],["lineage","Version & lineage"],["accounting","Accounting interpretation"]].map(([id,label])=><button role="tab" key={id} aria-selected={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>{error&&<p role="status" className="g8-inline-error">{error}</p>}{downloadError&&<p role="alert" className="g8-inline-error">{downloadError}</p>}
  {tab==="rows"&&<><form className="source-query" onSubmit={event=>{event.preventDefault();setOffset(0);setSearch(query);}}><MagnifyingGlass size={16}/><input aria-label="Search source rows" placeholder="Find an account, reference or source value…" value={query} onChange={event=>setQuery(event.target.value)} maxLength={128}/><button className="quiet" disabled={busy}>Search</button></form>{!canExport?<Empty title="Source access is restricted">Your identity can inspect review state. Original cell access requires source export permission.</Empty>:busy?<Empty title="Opening retained source…">Verifying original content before displaying values.</Empty>:preview?<><div className="source-table"><table><thead><tr><th>Row</th>{preview.columns.map((column,index)=><th key={index}>{column||`Unnamed column ${index+1}`}</th>)}</tr></thead><tbody>{preview.rows.map(row=><tr key={row.source_row}><th scope="row">{row.source_row}{!row.width_matches_header&&<Badge tone="warning">Width</Badge>}</th>{row.values.map((value,index)=><td key={index}>{value||<span className="source-null">Empty</span>}</td>)}</tr>)}</tbody></table>{!preview.rows.length&&<Empty title="No source rows match">Try another value or clear the row search.</Empty>}</div><div className="source-pagination"><span>{preview.matching_rows} matching rows · Original text, no numeric conversion</span><button className="quiet" disabled={offset===0||busy} onClick={()=>setOffset(Math.max(0,offset-100))}>Previous</button><button className="quiet" disabled={!preview.has_more||busy} onClick={()=>setOffset(offset+100)}>Next</button></div></>:null}</>}
  {tab==="profile"&&<div className="source-detail"><h3>Column completeness & variety</h3><p>Entire retained source, independent of the row search. Values remain text; no financial meaning is inferred.</p>{!canExport?<Empty title="Source access is restricted">Column profiling requires source export permission.</Empty>:busy?<p role="status">Profiling retained source...</p>:preview&&<><p>{preview.total_rows} source records · {preview.extra_width_rows} records contain extra cells</p><div className="source-table"><table><thead><tr><th>Column</th><th>Empty</th><th>Missing</th><th>Distinct non-empty</th></tr></thead><tbody>{preview.profile.map(field=><tr key={field.column_index}><th scope="row">{preview.columns[field.column_index]||`Unnamed column ${field.column_index+1}`}<small className="g8-block">Column {field.column_index+1} · Source text</small></th><td>{field.empty_cells}</td><td>{field.missing_cells}</td><td>{field.distinct_nonempty_values}</td></tr>)}</tbody></table></div><p>Empty = a retained blank cell. Missing = a row ends before this column. Distinct compares exact non-empty text, so 001 and 1 remain different.</p></>}</div>}
  {tab==="quality"&&detail&&<div className="source-detail"><h3>What this source establishes</h3><p>{detail.receipt.binding_state==="CANONICAL_BOUND"?"Bound to accepted canonical context.":"Source observations only. Canonical company and accounting context are not bound."}</p><div className="source-quality-grid"><div><small>Proposed objects</small><strong>{detail.receipt.candidates.length}</strong></div><div><small>Rejected rows</small><strong>{detail.receipt.rejects.length}</strong></div><div><small>Reconciliation</small><strong>{detail.receipt.reconciliation.status??"Not applicable"}</strong></div></div><h3>Quality findings</h3>{[...detail.receipt.rejects,...detail.receipt.warnings].length?[...detail.receipt.rejects,...detail.receipt.warnings].map((value,index)=><p className="g8-inline-error" key={index}>{value}</p>):<p>No source validation warnings were recorded. This does not establish financial certification.</p>}<h3>Review eligibility</h3>{detail.approval_blockers.map(reason=><p className="g8-inline-error" key={reason}>{reason}</p>)}<button className="g8-panel-action" onClick={()=>onReview(current.receipt_id)}>Open governed review<ArrowRight size={16}/></button></div>}
  {tab==="lineage"&&detail&&<div className="source-detail"><h3>From retained source to accepted state</h3><ol className="source-lineage"><li><strong>Original evidence retained</strong><p>{current.filename}</p><small>SHA-256 · {current.source_sha256}</small></li><li><strong>Source interpretation recorded</strong><p>{readable(detail.receipt.source_class)} · {detail.receipt.candidates.length} proposed objects</p><small>{readable(detail.receipt.binding_state)}</small></li><li><strong>{detail.decision?`${detail.decision.decision.toLowerCase()} decision retained`:"Independent review pending"}</strong><p>{detail.decision?.reason??"No accepted object version has been established by this receipt."}</p>{detail.decision&&<small>{new Date(detail.decision.decided_at).toLocaleString()}</small>}</li><li><strong>{current.is_current?"Current accepted construction":"Retained historical / pending construction"}</strong><p>Financial certification remains separate from source review.</p></li></ol></div>}
  {tab==="accounting"&&<div className="source-detail"><h3>Accounting interpretation</h3><p>Select the retained sheet and its supported source layout. The original source company, dates and amount observations will be inspected before any accounting choice is proposed.</p>
    {!companyId?<p role="status">Select a canonical company in the workspace before inspecting its source binding. Source names do not choose a company automatically.</p>:!principal.permissions.includes("ontology_read")?<p role="status">Canonical source interpretation is unavailable for this session.</p>:<>
      <label>Source sheet{accountingSheets.length?<select value={accountingChoice.sheet} onChange={event=>chooseAccounting("sheet",event.target.value)}><option value="">Select a retained sheet</option>{accountingSheets.map(item=><option key={item.sheet} value={item.sheet}>{item.sheet}</option>)}</select>:<input value={accountingChoice.sheet} onChange={event=>chooseAccounting("sheet",event.target.value)} maxLength={128} aria-label="Exact source sheet name"/>}</label>
      <label>Source layout<select value={accountingChoice.profile} onChange={event=>chooseAccounting("profile",event.target.value)}><option value="">Select a supported layout</option><option value="seg_expense_base">Recorder-line Base with accounting annotations</option><option value="1c_tb">1C trial balance</option><option value="1c_journal">1C journal movement</option></select></label>
      {accountingChoice.sheet.trim()&&accountingChoice.profile&&<SourceAccountingContext key={`${receiptId}:${accountingChoice.sheet}:${accountingChoice.profile}:${companyId}`} token={token} documentId={current.receipt_id} sheet={accountingChoice.sheet} profile={accountingChoice.profile} companyId={companyId} canPropose={Boolean(onProposal)&&principal.permissions.includes("ontology_propose")} onProposal={onProposal??(()=>{})} onInspectResource={onInspectResource?reference=>{setSelected(current.receipt_id);onInspectResource(reference);}:undefined} onTraceResource={onTraceResource}/>}
    </>}
  </div>}
  </div></section>;
}
