"use client";
import {useEffect,useRef,useState} from "react";
import SourceFactPublication from "./source-fact-publication";

type Inspection={accounts:{code:string;coordinate:string;occurrences:number;status:string;definition_candidates:{name:string;version_id:string}[]}[];control_groups:unknown[];company_candidates:{resource_id:string;name:string}[]};
export default function SourceAccountBindings({token,documentId,sheet,profile,canPropose,onProposal}:{token:string;documentId:string;sheet:string;profile:string;canPropose:boolean;onProposal:(id:string)=>void}){
  const [inspection,setInspection]=useState<Inspection|null>(null);const [company,setCompany]=useState("");const [offset,setOffset]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const pending=useRef<AbortController|null>(null);
  useEffect(()=>()=>pending.current?.abort(),[token]);
  async function run(proposal=false){pending.current?.abort();const controller=new AbortController();pending.current=controller;setBusy(true);setError("");try{
    const response=await fetch(`/api/ontology/source-documents/${documentId}/accounts/${proposal?"proposal":"inspect"}`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({sheet,profile,...(proposal?{company_id:company,offset}:{})}),signal:controller.signal});
    const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==="string"?data.detail:"Account binding rejected");if(controller.signal.aborted)return;
    if(proposal)onProposal(data.proposal.proposal_id);else{setInspection(data);setCompany(data.company_candidates.length===1?data.company_candidates[0].resource_id:"");}
  }catch(failure){if(!controller.signal.aborted)setError(failure instanceof Error?failure.message:"Account binding unavailable");}finally{if(!controller.signal.aborted)setBusy(false);}}
  return <section><h3>Company account bindings</h3><p>Resolve observed account codes against reviewed 1C definitions. Control groups remain outside the posting-account chart.</p><button disabled={busy||!sheet||!/^doc_[a-f0-9]{64}$/.test(documentId)} onClick={()=>void run()}>Inspect account usage</button>
    {inspection&&<><p>{inspection.accounts.length} observed account codes · {inspection.control_groups.length} source control groups excluded.</p><label htmlFor="source-account-company">Reviewed source company</label><select id="source-account-company" value={company} onChange={e=>setCompany(e.target.value)}><option value="">Select reviewed company</option>{inspection.company_candidates.map(c=><option key={c.resource_id} value={c.resource_id}>{c.name}</option>)}</select><div className="g8-table-scroll"><table><thead><tr><th>Code</th><th>Source cell</th><th>Uses</th><th>Definition</th><th>Binding</th></tr></thead><tbody>{inspection.accounts.slice(offset,offset+20).map(a=><tr key={a.code}><td>{a.code}</td><td>{a.coordinate}</td><td>{a.occurrences}</td><td>{a.definition_candidates.map(d=><span key={d.version_id}>{d.name}</span>)}</td><td>{a.status}</td></tr>)}</tbody></table></div><button disabled={busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-20))}>Previous accounts</button><button disabled={busy||offset+20>=inspection.accounts.length} onClick={()=>setOffset(offset+20)}>Next accounts</button>{canPropose&&<button disabled={busy||!company||inspection.accounts.some(a=>a.status!=="EXACT_MATCH")} onClick={()=>void run(true)}>Propose this account page for review</button>}<p>Account usage establishes a source-observed chart subset. Ledger, currency, mandatory dimensions and reporting mappings require separate bindings.</p></>}{busy&&<p role="status">Resolving source account identities…</p>}{error&&<p role="alert">{error}</p>}
    {company&&<SourceFactPublication key={company} token={token} documentId={documentId} sheet={sheet} profile={profile} companyId={company} canPropose={canPropose} onProposal={onProposal}/>}
  </section>;
}
