import {restorationInstant} from "./definition-restoration-time";
export type TransformationRequest={request_id:string;transformation:{resource_id:string;version_id:string};valid_at:string;known_at:string};
export type TransformationPreview={contract:"transformation-preview/1";request:TransformationRequest;plan_hash:string;exact_scope:Record<string,unknown>;coverage:"PLAN_METADATA_ONLY";transformed_rows_available:false;current_use_authorized:false;business_effect_authorized:false;compiled_plan:{contract:"transformation-plan/1";plan_hash:string;request:TransformationRequest;nodes:Array<{node_id:string;depends_on:string[]}>;outputs:Array<{output_id:string;node_id:string}>;resource_budget:{max_returned_rows:number;max_derived_evaluations:number;max_published_result_bytes:number};publication_review?:{question:string};binding_review?:unknown;current_use_authorized:false;business_effect_authorized:false}};
function sameRequest(a:TransformationRequest|undefined,b:TransformationRequest){return a?.request_id===b.request_id&&a.transformation?.resource_id===b.transformation.resource_id&&a.transformation?.version_id===b.transformation.version_id&&Boolean(restorationInstant(a.valid_at))&&restorationInstant(a.valid_at)===restorationInstant(b.valid_at)&&Boolean(restorationInstant(a.known_at))&&restorationInstant(a.known_at)===restorationInstant(b.known_at);}
export function assertTransformationPreview(value:unknown,request:TransformationRequest):asserts value is TransformationPreview {
 const p=value as TransformationPreview|null;
 if(!p||p.contract!=="transformation-preview/1"||p.coverage!=="PLAN_METADATA_ONLY"||p.transformed_rows_available!==false||p.current_use_authorized!==false||p.business_effect_authorized!==false||!sameRequest(p.request,request)||typeof p.plan_hash!=="string"||!/^[a-f0-9]{64}$/.test(p.plan_hash))throw Error("The preview does not match the requested transformation and snapshot.");
 const plan=p.compiled_plan,budget=plan?.resource_budget;
 if(!plan||plan.contract!=="transformation-plan/1"||plan.plan_hash!==p.plan_hash||!sameRequest(plan.request,request)||plan.current_use_authorized!==false||plan.business_effect_authorized!==false||!Array.isArray(plan.nodes)||!plan.nodes.length||plan.nodes.length>32||plan.nodes.some(n=>!n||typeof n.node_id!=="string"||!Array.isArray(n.depends_on))||!Array.isArray(plan.outputs)||!plan.outputs.length||plan.outputs.some(o=>!o||typeof o.output_id!=="string"||!plan.nodes.some(n=>n.node_id===o.node_id))||!budget||![budget.max_returned_rows,budget.max_derived_evaluations,budget.max_published_result_bytes].every(n=>Number.isSafeInteger(n)&&n>=0))throw Error("The transformation plan is incomplete. Refresh its preview before starting.");
}
