"use client";

import { useState } from "react";
import type { IngestReceipt, Principal, ReceiptDetail } from "@finai/contracts";

type Props = { detail: ReceiptDetail; principal: Principal; onClose: () => void; onExport: (format: "source" | "export") => void };
type Row = IngestReceipt["candidates"][number];
const amount = (value?: string) => !value ? "—" : Number.isFinite(Number(value)) ? Number(value).toLocaleString("en-US", { maximumFractionDigits: 6 }) : value;
const rowName = (row: Row) => row.values.analytic_label || row.values.source_account_name || row.values.cell_D || "Unlabelled source row";

export default function TrialBalanceReview({ detail, principal, onClose, onExport }: Props) {
  const { receipt } = detail;
  const [tab, setTab] = useState("data");
  const [kind, setKind] = useState("accounts");
  const [measure, setMeasure] = useState("turnover");
  const [query, setQuery] = useState("");
  const [page, setPage] = useState(0);
  const [selected, setSelected] = useState<Row | null>(null);
  const context = (receipt as IngestReceipt & { observed_bindings?: Record<string, string> }).observed_bindings;
  const period = context?.period || receipt.candidates.find(row => row.values.observed_period)?.values.observed_period;
  const filtered = receipt.candidates.filter(row => (kind === "all" || (kind === "accounts" ? !!row.values.source_account_code : !row.values.source_account_code)) && `${row.values.source_account_code || ""} ${rowName(row)} ${row.source_row}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const pageCount = Math.max(1, Math.ceil(filtered.length / 25));
  const changeQuery = (value: string) => { setQuery(value); setPage(0); };
  return <section className="tb-review" aria-label="Trial balance review">
    <header className="tb-header"><div><button className="quiet" onClick={onClose}>← All uploads</button><h2>{detail.filename}</h2><p>Trial balance <span>· Original saved</span></p></div>{principal.permissions.includes("export") && <button className="quiet" onClick={() => onExport("source")}>Download original</button>}</header>
    <div className="tb-context"><div><span>Company in file</span><strong>{context?.company_label || "See original company header"}</strong></div><div><span>Month in file</span><strong>{period ? new Date(`${period}-01T12:00:00`).toLocaleDateString("en-US", { month: "long", year: "numeric" }) : "Needs review"}</strong></div><div><span>Source rows</span><strong>{receipt.candidates.length.toLocaleString()}</strong></div><div><span>Financial use</span><strong className="tb-amber">Mapping needed</strong></div></div>
    <div className="tb-notice"><div><strong>The file is saved. Financial reports have not changed.</strong><p>Confirm the company, currency and account mappings before using these amounts in reports.</p></div><button className="quiet" onClick={() => setTab("checks")}>View checks →</button></div>
    <nav className="tb-tabs" aria-label="Upload review sections">{[["data", "Data preview"], ["checks", "Checks & next steps"], ["history", "Source history"]].map(([id, label]) => <button key={id} aria-pressed={tab === id} onClick={() => setTab(id)}>{label}</button>)}</nav>
    {tab === "data" && <><div className="tb-toolbar"><label>Find an account<input type="search" placeholder="Account code, name or source row" value={query} onChange={event => changeQuery(event.target.value)} /></label><label>Show<select value={kind} onChange={event => { setKind(event.target.value); setPage(0); }}><option value="accounts">Accounts</option><option value="breakdown">Analytical & other rows</option><option value="all">All source rows</option></select></label><label>Amounts<select value={measure} onChange={event => setMeasure(event.target.value)}><option value="turnover">Monthly activity</option><option value="closing">Closing balances</option><option value="opening">Opening balances</option></select></label></div><p className="tb-caption">{filtered.length.toLocaleString()} matching rows · Amounts as supplied; currency unconfirmed. Summary and detail rows overlap and must not be added together.</p>
      <div className={`tb-data ${selected ? "tb-data-selected" : ""}`}><div className="tb-table-wrap"><table><thead><tr><th>Account / description</th><th>Row type</th><th className="tb-number">Debit</th><th className="tb-number">Credit</th><th>Source</th></tr></thead><tbody>{filtered.slice(page * 25, page * 25 + 25).map(row => <tr key={row.source_row} className={selected?.source_row === row.source_row ? "tb-selected" : ""}><td><button className="tb-row-link" onClick={() => setSelected(row)}><strong>{row.values.source_account_code || "—"}</strong><span>{rowName(row)}</span></button></td><td><span className="tb-row-type">{row.values.source_row_role?.toLowerCase().replaceAll("_", " ") || "Source row"}</span></td><td className="tb-number">{amount(row.values[`${measure}_debit`])}</td><td className="tb-number">{amount(row.values[`${measure}_credit`])}</td><td><button className="tb-source-link" onClick={() => setSelected(row)}>Row {row.source_row}</button></td></tr>)}</tbody></table>{!filtered.length && <p className="tb-empty">No matching rows. Try another account code or choose all source rows.</p>}</div>
      {selected && <aside className="tb-inspector" aria-label="Source row details"><button className="quiet" onClick={() => setSelected(null)}>Close details ×</button><h3>{selected.values.source_account_code || "Source row"}</h3><p>{rowName(selected)}</p><p className="tb-caption">{selected.values.source_sheet} · Row {selected.source_row}</p>{["opening", "turnover", "closing"].map(group => <div key={group}><h4>{group === "turnover" ? "Monthly activity" : `${group} balances`}</h4><dl><dt>Debit</dt><dd>{amount(selected.values[`${group}_debit`])}</dd><dt>Credit</dt><dd>{amount(selected.values[`${group}_credit`])}</dd></dl></div>)}<p className="tb-caption">Original source values. A dash means no value was supplied.</p></aside>}</div>
      <div className="tb-pagination"><span>Page {page + 1} of {pageCount}</span><button className="quiet" disabled={page === 0} onClick={() => setPage(page - 1)}>Previous</button><button className="quiet" disabled={page + 1 >= pageCount} onClick={() => setPage(page + 1)}>Next</button></div></>}
    {tab === "checks" && <div className="tb-checks"><article><span className="tb-check-label">Saved</span><h3>Original file preserved</h3><p>You can download the original workbook and trace each displayed value to its source row.</p></article><article><span className="tb-check-label tb-amber">Needs review</span><h3>Company and currency</h3><p>The company name and month are observations from the file. They do not establish an approved company mapping. The source header does not explicitly identify a currency.</p></article><article><span className="tb-check-label tb-amber">Needs review</span><h3>Account hierarchy and repeated rows</h3><p>Account groups, individual accounts and analytical breakdowns overlap. Repeated codes need review before selecting reportable balances.</p><button className="quiet" onClick={() => { setKind("all"); setPage(0); setTab("data"); }}>Inspect all source rows</button></article><article><span className="tb-check-label tb-amber">Not available yet</span><h3>Use in financial reports</h3><p>Financial mapping for this XLS is not available yet. This upload retains source evidence; it does not create journals or populate management reports.</p></article>{receipt.rejects.map(item => <p className="warning" key={item}>{item}</p>)}</div>}
    {tab === "history" && <div className="tb-history"><h3>Source retained</h3><p>{new Date(detail.ingested_at).toLocaleString()} · {detail.filename}</p><p>{receipt.source_storage?.byte_length.toLocaleString() || "Unknown"} bytes · {receipt.candidates[0]?.values.source_sheet || "Original workbook"}</p><details><summary>Technical provenance</summary><p>Source fingerprint</p><code>{receipt.source_sha256}</code><p>Reader contract: {receipt.authority_contract_version}</p><p>Recorded processing plan: {receipt.plan.join(" → ")}</p><p>This plan lists processing steps; it is not a live progress timeline.</p>{principal.permissions.includes("export") && <button className="quiet" onClick={() => onExport("export")}>Download evidence bundle</button>}</details></div>}
  </section>;
}
