import assert from "node:assert/strict";
import test from "node:test";
import {loadTypeScript} from "./load-typescript.mjs";
const s=await loadTypeScript(new URL("../app/source-exception-state.ts",import.meta.url));
const id=n=>`${n.toString(16).padStart(8,"0")}-aaaa-4aaa-8aaa-aaaaaaaaaaaa`;
const pin=n=>({resource_id:id(n),version_id:id(n+100),content_hash:"a".repeat(64)});
const keys=["debit_movement","credit_movement","net_movement"];
const sourceTime="2025-01-31T00:00:00.123456Z",snapshot="2026-09-08T12:00:00.654321Z";
const metricValues=values=>Object.fromEntries(keys.map((key,index)=>[key,{state:"VALUE",value:values[index]}]));

// Isolated fixture: one balanced retained journal, two contributing local accounts.
// The decimal literals mirror C's supported 731.97 movement example, not a live result.
function fixture(){
 const company=pin(1),invocation=id(2),accountA=pin(10),accountB=pin(11),sourceFunction=pin(30),currency=pin(40);
 const rowKeys=["row_"+"b".repeat(64),"row_"+"c".repeat(64)];
 const fields=[{key:"account_code",kind:"identifier",role:"ATTRIBUTE"},{key:"account",kind:"reference",role:"DIMENSION"},...keys.map(key=>({key,kind:"decimal",role:"ATTRIBUTE"}))].map(field=>({...field,label:field.key,aggregation:"NONE",definition:sourceFunction,filterable:false,groupable:false,options:[]}));
 const rows=[{account:accountA,code:"7310.02.1",label:"ხარჯი · Расход · Expense",values:["731.97","0.00","731.97"]},{account:accountB,code:"3110",label:"მომწოდებელი · Поставщик · Supplier",values:["0.00","731.97","-731.97"]}].map((item,index)=>({key:rowKeys[index],label:item.label,trace:item.account,contributor_count:1,values:{account_code:{state:"VALUE",value:item.code,label:null,reference:null},account:{state:"VALUE",value:item.account.resource_id,label:item.label,reference:item.account},...Object.fromEntries(keys.map((key,i)=>[key,{state:"VALUE",value:item.values[i],label:null,reference:null}]))}}));
 const projection={descriptor:{contract:"semantic-analysis/2",row_noun:"objects",invocation_id:invocation,company,company_label:"Fixture company",function:sourceFunction,receipt_hash:"d".repeat(64),valid_at:sourceTime,known_at:sourceTime,recorded_at:sourceTime,current_use_authorized:false,business_effect_authorized:false,visual:"NONE",measure:null,filtering:"RETAINED_GROUP_SELECTION",grouping:"RETAINED_ROWS_WITHOUT_AGGREGATION",fields,coverage:[{label:"Snapshot",value:snapshot}]},descriptor_sha256:"e".repeat(64),request:{company_id:company.resource_id,invocation_id:invocation,descriptor_sha256:"e".repeat(64)},total_rows:2,rows,sections:[{label:"Accepted account movements",row_keys:rowKeys}],selection:null};
 const selection={legal_entity_id:company,ledger_id:pin(41),book_id:pin(42),period_id:pin(43),chart_id:pin(44),currency_id:currency,calendar_id:pin(45)};
 const journal={journal:pin(50),lines:[pin(51),pin(52)],dimension_policies:[pin(53)],source_coordinate:"Base!S2"};
 const nodes=[{key:"company",parent_key:null,kind:"COMPANY_MOVEMENTS",label:"Fixture company",account_code:null,subject:company,metrics:metricValues(["731.97","731.97","0.00"]),source_coordinates:["Base!S2"],journal_keys:[journal.journal.resource_id],analysis_row_key:null},...rows.map((row,index)=>({key:`account-${index}`,parent_key:"company",kind:"ACCOUNT_MOVEMENTS",label:row.label,account_code:row.values.account_code.value,subject:row.trace,metrics:metricValues(keys.map(key=>row.values[key].value)),source_coordinates:["Base!S2"],journal_keys:[journal.journal.resource_id],analysis_row_key:row.key}))];
 const result={contract:"company-financial-metrics/1",company_id:company.resource_id,invocation_id:invocation,snapshot_at:snapshot,selection,binding:pin(60),source_function:sourceFunction,source_sha256:"f".repeat(64),source_receipt_hash:"1".repeat(64),reconciliation_receipt_hash:projection.descriptor.receipt_hash,implementation_sha256:"2".repeat(64),result_sha256:"3".repeat(64),definitions:keys.map((code,index)=>({code,label:["Accepted debit movements","Accepted credit movements","Accepted net movements"][index],function_reference:"finance.accepted-journal-movements/v1",definition_authority:"CODE_DEFINED_NOT_PUBLISHED",operation:["ACCEPTED_DEBIT","ACCEPTED_CREDIT","DEBIT_MINUS_CREDIT"][index],unit:currency,unit_label:"GEL"})),nodes,journals:[journal],coverage:{state:"RECONCILED",source_rows:1,literal_source_rows:1,accepted_journals:1,unmatched_source_rows:0,excluded_source_rows:0,rejected_journals:0,missing_coordinates:[],excluded_rows:[],rejected:[],ledger_completeness:"UNESTABLISHED"},hierarchy_basis:"COMPANY_AND_EXACT_LOCAL_ACCOUNT",aggregation:"SERVER_OWNED_VALUES_DO_NOT_SUM_HIERARCHY",unavailable:["OPENING_BALANCE","CLOSING_BALANCE","FINANCIAL_STATEMENTS"],current_use_authorized:false,business_effect_authorized:false};
 const request={company_id:company.resource_id,invocation_id:invocation,snapshot_at:snapshot,expected_reconciliation_sha256:result.reconciliation_receipt_hash,expected_result_sha256:result.result_sha256};
 const reference={kind:"EXACT",invocationId:invocation,journalSnapshot:snapshot,revision:{descriptorSha256:projection.descriptor_sha256,receiptHash:projection.descriptor.receipt_hash,validAt:sourceTime,knownAt:sourceTime}};
 return {result,request,projection,reference};
}

function exceptionFixture(){
 const f=fixture(),m=f.result,p=f.projection;m.coverage.state="PARTIAL";m.coverage.missing_coordinates=["Base!S3"];m.coverage.unmatched_source_rows=1;p.descriptor.definitions=[];
 const flags={current_use_authorized:false,business_effect_authorized:false},scope={tenant_id:id(70),legal_entity_id:m.company_id,ledger_id:m.selection.ledger_id.resource_id,book_id:m.selection.book_id.resource_id};
 const source={invocationId:m.invocation_id,companyId:m.company_id,receiptHash:"4".repeat(64),runId:`fcr_${"5".repeat(64)}`,planHash:"6".repeat(64),function:m.source_function,validAt:sourceTime,knownAt:sourceTime,output:{scope,source_document:{evidence:pin(80),document_id:id(81),sheet:"Base",sha256:m.source_sha256}}};
 const request=s.sourceExceptionRequest(m,p,m.company_id,"Base!S3");
 const exception={...flags,contract:"source-reconciliation-exception/1",detector:"source-reconciliation-exceptions/1",calculation_runtime:"source-reconciliation-exceptions/1",run_id:`fcr_${"7".repeat(64)}`,scope,read_permissions:["ontology_read"],receipt_hash:"8".repeat(64),company:p.descriptor.company,selection:m.selection,context_versions:Object.values(m.selection),binding:m.binding,source_function:m.source_function,source:{invocation_id:m.invocation_id,invocation_receipt_hash:source.receiptHash,source_receipt_hash:m.source_receipt_hash,sha256:m.source_sha256,evidence:pin(80),document_id:id(81),sheet:"Base",row:3,coordinate:"Base!S3"},source_valid_at:sourceTime,source_known_at:sourceTime,journal_observed_at:snapshot,reconciliation:{receipt_hash:m.reconciliation_receipt_hash,status:"PARTIAL"},state:"UNMATCHED_AT_SNAPSHOT",finding_eligible:true,exclusion_reason:null,matched_journals:[],financial_impact:null,materiality:"UNASSESSED",automatic_resolution:false};
 return {...f,source,request,exception};
}
test("only returned missing coordinates are choices; PARTIAL is not a detector",()=>{const f=exceptionFixture();assert.deepEqual(s.sourceExceptionChoices(f.result,f.projection,f.result.company_id),["Base!S3"]);f.result.coverage.missing_coordinates=[];assert.deepEqual(s.sourceExceptionChoices(f.result,f.projection,f.result.company_id),[]);assert.throws(()=>s.sourceExceptionRequest(f.result,f.projection,f.result.company_id,"Base!S3"));});
test("request is exact shared wire without result amounts or invented fields",()=>{const f=exceptionFixture();assert.deepEqual(Object.keys(f.request).sort(),["company_id","coordinate","expected_reconciliation_receipt_hash","invocation_id","journal_snapshot_at"]);s.assertSourceException(f.exception,f.request,f.result,f.projection,f.source);});
for(const [label,change] of [
 ["wrong company",v=>v.company=pin(90)], ["wrong scope",v=>v.scope={...v.scope,legal_entity_id:id(90)}],
 ["source and journal receipt conflation",v=>v.source.invocation_receipt_hash=v.reconciliation.receipt_hash],
 ["source receipt mismatch",v=>v.source.source_receipt_hash="9".repeat(64)], ["context revision",v=>v.context_versions=[...v.context_versions.slice(1),pin(91)]],
 ["source evidence revision",v=>v.source.evidence=pin(92)], ["source cell",v=>v.source.coordinate="Base!S4"],
 ["source row",v=>v.source.row=4], ["source time",v=>v.source_known_at=snapshot], ["journal time",v=>v.journal_observed_at=sourceTime],
 ["matched cell",v=>{v.state="MATCHED_AT_SNAPSHOT";v.finding_eligible=false;}],
 ["excluded cell",v=>{v.state="EXCLUDED_SOURCE_VALUE";v.finding_eligible=false;v.exclusion_reason="FORMULA";}],
 ["inferred impact",v=>v.financial_impact="20"], ["authority promotion",v=>v.business_effect_authorized=true],
])test(`exception refuses ${label}`,()=>{const f=exceptionFixture();change(f.exception);assert.throws(()=>s.assertSourceException(f.exception,f.request,f.result,f.projection,f.source));});
test("saved exception contains references only and refuses new metric snapshot",()=>{const f=exceptionFixture(),saved=s.savedSourceException(f.exception,f.request,f.result),raw=JSON.stringify(saved);assert.ok(s.parseSourceException(raw,f.result,f.projection,f.result.company_id));assert.equal(raw.includes('source_document'),false);assert.equal(raw.includes('financial_impact'),false);assert.equal(s.parseSourceException(raw,{...f.result,result_sha256:"9".repeat(64)},f.projection,f.result.company_id),null);});
function actionFixture(){const f=exceptionFixture(),request=s.investigationRequest(id(90),f.exception,"Investigate the missing accepted journal"),{run_id,scope,calculation_runtime,read_permissions,...evidence}=f.exception;const mutations=[{object_type:"Finding",resource_id:id(91),attributes:{definition:{contract:"source-finding/1",state:"OPEN",exception_run_id:run_id,exception_receipt_hash:f.exception.receipt_hash,evidence:structuredClone(evidence),financial_impact:null,materiality:"UNASSESSED",automatic_resolution:false}}},{object_type:"Investigation",resource_id:id(92),attributes:{definition:{contract:"source-investigation/1",state:"OPEN",exception_run_id:run_id,exception_receipt_hash:f.exception.receipt_hash,automatic_resolution:false}}}];const operation={operation_id:`opa_${"a".repeat(64)}`,intent_id:null,intent_request:{...request,expected_finding_version_id:null,expected_investigation_version_id:null},state:"PENDING_REVIEW",proposal:{proposal:{proposal_id:id(93),rationale:request.rationale,mutations},decision:null},prepared_proposal_id:id(93),definition:{version:"ontology-action/1",kind:"SOURCE_EXCEPTION_INVESTIGATION",company_id:f.exception.company.resource_id,exception_run_id:run_id,effect:"CANONICAL_RESOURCE_PROPOSAL",publication:"EXISTING_RESOURCE_REVIEW"},events:[],finding_id:id(91),investigation_id:id(92),frozen_rationale:request.rationale,publication:null,publication_limitation:null,current_use_authorized:false,business_effect_authorized:false};return {...f,actionRequest:request,operation};}
test("explicit Action request contains no caller-authored Finding facts",()=>{const f=actionFixture();assert.deepEqual(Object.keys(f.actionRequest).sort(),["exception_run_id","rationale","request_id"]);s.assertInvestigation(f.operation,f.exception,{request:f.actionRequest});});
test("approved alone never establishes publication",()=>{const f=actionFixture();f.operation.proposal.decision="APPROVED";f.operation.state="PUBLICATION_UNAVAILABLE";s.assertInvestigation(f.operation,f.exception,{operationId:f.operation.operation_id});f.operation.state="PUBLISHED";assert.throws(()=>s.assertInvestigation(f.operation,f.exception,{operationId:f.operation.operation_id}));});
test("published pair requires matching exact canonical references",()=>{const f=actionFixture();f.operation.proposal.decision="APPROVED";f.operation.state="PUBLISHED";f.operation.publication={finding:pin(91),investigation:pin(92)};s.assertInvestigation(f.operation,f.exception,{operationId:f.operation.operation_id});f.operation.publication.finding=pin(90);assert.throws(()=>s.assertInvestigation(f.operation,f.exception,{operationId:f.operation.operation_id}));});
test("shared effect preserves first rationale, separately from current request",()=>{const f=actionFixture();f.operation.frozen_rationale="Original operator investigation reason";f.operation.proposal.proposal.rationale=f.operation.frozen_rationale;s.assertInvestigation(f.operation,f.exception,{request:f.actionRequest});});
for(const [label,change] of [["other exception",v=>v.definition.exception_run_id=`fcr_${"b".repeat(64)}`],["other request",v=>v.intent_request.request_id=id(95)],["different finding evidence",v=>v.proposal.proposal.mutations[0].attributes.definition.evidence.source.coordinate="Base!S5"],["automatic resolution",v=>v.proposal.proposal.mutations[1].attributes.definition.automatic_resolution=true]])test(`Action refuses ${label}`,()=>{const f=actionFixture();change(f.operation);assert.throws(()=>s.assertInvestigation(f.operation,f.exception,{request:f.actionRequest}));});
