// Generated by scripts/generate-ontology-query-contracts.py. Do not edit.

// Dynamic resource attributes remain owned by the canonical ontology schemas.

export const ontologyQueryWireVersion = "ontology-object-set/1";

export const ontologyQuerySchemaSha256 = "48e3cf41ea7f44db64e83a1b6f9fa30cf81194779cfadc1daac37db60a91ed27";

export type WireInterfacePin = { "resource_id" : string; "version_id" : string; };

export type WireInterfaceRoot = { "resource_id" : string; "version_id" : string; "implementations" : Array<WireInterfacePin>; };

export type WirePropertyFilter = { "field" : string; "value" : (string | number | boolean | Array<(string | number | boolean)> | null); "operator"?: "eq" | "lt" | "lte" | "gt" | "gte" | "in" | "not_in"; };

export type WireTraversal = { "kind"?: "reference" | "link"; "name" : string; "direction"?: "outgoing" | "incoming"; "filters"?: Array<WirePropertyFilter>; };

export type WireObjectSetQuery = { "object_type" : string; "resource_ids"?: (Array<string> | null); "filters"?: Array<WirePropertyFilter>; "traversal"?: Array<WireTraversal>; "search"?: string; "limit"?: number; "offset"?: number; "valid_at"?: (string | null); "known_at"?: (string | null); "interface"?: (WireInterfaceRoot | null); "type_group"?: (WireInterfacePin | null); };

export type WireFilterSchemaVersion = { "object_type" : string; "resource_id" : string; "version_id" : string; [key: string]: unknown; };

export type WireGroupSchemaBinding = { "object_type" : string; "schema" : WireHashedPin; [key: string]: unknown; };

export type WireHashedPin = { "resource_id" : string; "version_id" : string; "content_hash" : string; };

export type WireInterfaceBindings = { "interface" : WireHashedPin; "fields" : { [key: string]: WireSharedField; }; "implementations" : Array<WireInterfaceImplementationBinding>; [key: string]: unknown; };

export type WireInterfaceImplementationBinding = { "implementation" : WireHashedPin; "schema" : WireHashedPin; "object_type" : string; "fields" : { [key: string]: string; }; [key: string]: unknown; };

export type WireInterfaceValue = { "object_id" : string; "object_version_id" : string; "implementation_resource_id" : string; "implementation_version_id" : string; "schema_version_id" : string; "status" : "AVAILABLE" | "SCHEMA_CHANGED"; "values" : ({ [key: string]: unknown; } | null); [key: string]: unknown; };

export type WireQueryResource = { "resource_id" : string; "version_id" : string; "object_type" : string; "identity_key" : string; "display_name" : string; "access_entity" : string; "schema_version_id" : (string | null); "attributes" : { [key: string]: unknown; }; "content_hash" : string; "valid_from" : string; "valid_to" : (string | null); "system_from" : string; "authority_state" : "APPROVED" | "REVOKED"; "evidence_class" : string; "proposal_id" : (string | null); [key: string]: unknown; };

export type WireResolvedQuery = { "object_type" : string; "resource_ids"?: (Array<string> | null); "filters"?: Array<WirePropertyFilter>; "traversal"?: Array<WireTraversal>; "search"?: string; "limit"?: number; "offset"?: number; "valid_at" : string; "known_at" : string; "interface"?: (WireInterfaceRoot | null); "type_group"?: (WireInterfacePin | null); };

export type WireSharedField = { "kind" : string; "required" : boolean; "semantic_id"?: (string | null); "target_type"?: (string | null); [key: string]: unknown; };

export type WireTraversalSchemaVersion = { "object_type" : string; "resource_id" : string; "version_id" : string; "step" : number; [key: string]: unknown; };

export type WireTypeGroupBindings = { "group" : WireHashedPin; "schemas" : Array<WireGroupSchemaBinding>; "fields" : { [key: string]: WireSharedField; }; [key: string]: unknown; };

export type WireTypeGroupValue = { "object_id" : string; "object_version_id" : string; "schema_version_id" : string; "status" : "AVAILABLE" | "SCHEMA_CHANGED"; [key: string]: unknown; };

export type WireObjectSetResponse = { "contract" : "ontology-object-set/1"; "query" : WireResolvedQuery; "total" : number; "counts_by_type" : { [key: string]: number; }; "objects" : Array<WireQueryResource>; "next_offset" : (number | null); "filter_schema_versions"?: Array<WireFilterSchemaVersion>; "traversal_schema_versions"?: Array<WireTraversalSchemaVersion>; "interface_bindings"?: (WireInterfaceBindings | null); "interface_values"?: (Array<WireInterfaceValue> | null); "type_group_bindings"?: (WireTypeGroupBindings | null); "type_group_values"?: (Array<WireTypeGroupValue> | null); [key: string]: unknown; };

export type WireDefinedObjectSetResponse = { "contract" : "ontology-object-set/1"; "query" : WireResolvedQuery; "total" : number; "counts_by_type" : { [key: string]: number; }; "objects" : Array<WireQueryResource>; "next_offset" : (number | null); "filter_schema_versions"?: Array<WireFilterSchemaVersion>; "traversal_schema_versions"?: Array<WireTraversalSchemaVersion>; "interface_bindings"?: (WireInterfaceBindings | null); "interface_values"?: (Array<WireInterfaceValue> | null); "type_group_bindings"?: (WireTypeGroupBindings | null); "type_group_values"?: (Array<WireTypeGroupValue> | null); "definition_id" : string; "definition_version_id" : string; [key: string]: unknown; };

export const querySchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$defs": {
    "InterfacePin": {
      "additionalProperties": false,
      "properties": {
        "resource_id": {
          "format": "uuid",
          "title": "Resource Id",
          "type": "string"
        },
        "version_id": {
          "format": "uuid",
          "title": "Version Id",
          "type": "string"
        }
      },
      "required": [
        "resource_id",
        "version_id"
      ],
      "title": "InterfacePin",
      "type": "object"
    },
    "InterfaceRoot": {
      "additionalProperties": false,
      "properties": {
        "resource_id": {
          "format": "uuid",
          "title": "Resource Id",
          "type": "string"
        },
        "version_id": {
          "format": "uuid",
          "title": "Version Id",
          "type": "string"
        },
        "implementations": {
          "items": {
            "$ref": "#/$defs/InterfacePin"
          },
          "maxItems": 100,
          "minItems": 1,
          "title": "Implementations",
          "type": "array"
        }
      },
      "required": [
        "resource_id",
        "version_id",
        "implementations"
      ],
      "title": "InterfaceRoot",
      "type": "object"
    },
    "PropertyFilter": {
      "additionalProperties": false,
      "properties": {
        "field": {
          "maxLength": 128,
          "minLength": 1,
          "title": "Field",
          "type": "string"
        },
        "value": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "integer"
            },
            {
              "type": "boolean"
            },
            {
              "items": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "integer"
                  },
                  {
                    "type": "boolean"
                  }
                ]
              },
              "maxItems": 100,
              "minItems": 1,
              "type": "array"
            },
            {
              "type": "null"
            }
          ],
          "title": "Value"
        },
        "operator": {
          "default": "eq",
          "enum": [
            "eq",
            "lt",
            "lte",
            "gt",
            "gte",
            "in",
            "not_in"
          ],
          "title": "Operator",
          "type": "string"
        }
      },
      "required": [
        "field",
        "value"
      ],
      "title": "PropertyFilter",
      "type": "object"
    },
    "Traversal": {
      "additionalProperties": false,
      "properties": {
        "kind": {
          "default": "reference",
          "enum": [
            "reference",
            "link"
          ],
          "title": "Kind",
          "type": "string"
        },
        "name": {
          "maxLength": 128,
          "minLength": 1,
          "title": "Name",
          "type": "string"
        },
        "direction": {
          "default": "outgoing",
          "enum": [
            "outgoing",
            "incoming"
          ],
          "title": "Direction",
          "type": "string"
        },
        "filters": {
          "items": {
            "$ref": "#/$defs/PropertyFilter"
          },
          "maxItems": 20,
          "title": "Filters",
          "type": "array"
        }
      },
      "required": [
        "name"
      ],
      "title": "Traversal",
      "type": "object"
    }
  },
  "additionalProperties": false,
  "properties": {
    "object_type": {
      "pattern": "^[A-Z][A-Za-z0-9]{1,63}$",
      "title": "Object Type",
      "type": "string"
    },
    "resource_ids": {
      "anyOf": [
        {
          "items": {
            "format": "uuid",
            "type": "string"
          },
          "maxItems": 100,
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Resource Ids"
    },
    "filters": {
      "items": {
        "$ref": "#/$defs/PropertyFilter"
      },
      "maxItems": 20,
      "title": "Filters",
      "type": "array"
    },
    "traversal": {
      "items": {
        "$ref": "#/$defs/Traversal"
      },
      "maxItems": 4,
      "title": "Traversal",
      "type": "array"
    },
    "search": {
      "default": "",
      "maxLength": 128,
      "title": "Search",
      "type": "string"
    },
    "limit": {
      "default": 50,
      "maximum": 200,
      "minimum": 1,
      "title": "Limit",
      "type": "integer"
    },
    "offset": {
      "default": 0,
      "maximum": 1000000,
      "minimum": 0,
      "title": "Offset",
      "type": "integer"
    },
    "valid_at": {
      "anyOf": [
        {
          "format": "date-time",
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Valid At"
    },
    "known_at": {
      "anyOf": [
        {
          "format": "date-time",
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Known At"
    },
    "interface": {
      "anyOf": [
        {
          "$ref": "#/$defs/InterfaceRoot"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "type_group": {
      "anyOf": [
        {
          "$ref": "#/$defs/InterfacePin"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    }
  },
  "required": [
    "object_type"
  ],
  "title": "ObjectSetQuery",
  "type": "object"
};

export const responseSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$defs": {
    "FilterSchemaVersion": {
      "properties": {
        "object_type": {
          "title": "Object Type",
          "type": "string"
        },
        "resource_id": {
          "format": "uuid",
          "title": "Resource Id",
          "type": "string"
        },
        "version_id": {
          "format": "uuid",
          "title": "Version Id",
          "type": "string"
        }
      },
      "required": [
        "object_type",
        "resource_id",
        "version_id"
      ],
      "title": "FilterSchemaVersion",
      "type": "object"
    },
    "GroupSchemaBinding": {
      "properties": {
        "object_type": {
          "title": "Object Type",
          "type": "string"
        },
        "schema": {
          "$ref": "#/$defs/HashedPin"
        }
      },
      "required": [
        "object_type",
        "schema"
      ],
      "title": "GroupSchemaBinding",
      "type": "object"
    },
    "HashedPin": {
      "additionalProperties": false,
      "properties": {
        "resource_id": {
          "format": "uuid",
          "title": "Resource Id",
          "type": "string"
        },
        "version_id": {
          "format": "uuid",
          "title": "Version Id",
          "type": "string"
        },
        "content_hash": {
          "title": "Content Hash",
          "type": "string"
        }
      },
      "required": [
        "resource_id",
        "version_id",
        "content_hash"
      ],
      "title": "HashedPin",
      "type": "object"
    },
    "InterfaceBindings": {
      "properties": {
        "interface": {
          "$ref": "#/$defs/HashedPin"
        },
        "fields": {
          "additionalProperties": {
            "$ref": "#/$defs/SharedField"
          },
          "title": "Fields",
          "type": "object"
        },
        "implementations": {
          "items": {
            "$ref": "#/$defs/InterfaceImplementationBinding"
          },
          "title": "Implementations",
          "type": "array"
        }
      },
      "required": [
        "interface",
        "fields",
        "implementations"
      ],
      "title": "InterfaceBindings",
      "type": "object"
    },
    "InterfaceImplementationBinding": {
      "properties": {
        "implementation": {
          "$ref": "#/$defs/HashedPin"
        },
        "schema": {
          "$ref": "#/$defs/HashedPin"
        },
        "object_type": {
          "title": "Object Type",
          "type": "string"
        },
        "fields": {
          "additionalProperties": {
            "type": "string"
          },
          "title": "Fields",
          "type": "object"
        }
      },
      "required": [
        "implementation",
        "schema",
        "object_type",
        "fields"
      ],
      "title": "InterfaceImplementationBinding",
      "type": "object"
    },
    "InterfacePin": {
      "additionalProperties": false,
      "properties": {
        "resource_id": {
          "format": "uuid",
          "title": "Resource Id",
          "type": "string"
        },
        "version_id": {
          "format": "uuid",
          "title": "Version Id",
          "type": "string"
        }
      },
      "required": [
        "resource_id",
        "version_id"
      ],
      "title": "InterfacePin",
      "type": "object"
    },
    "InterfaceRoot": {
      "additionalProperties": false,
      "properties": {
        "resource_id": {
          "format": "uuid",
          "title": "Resource Id",
          "type": "string"
        },
        "version_id": {
          "format": "uuid",
          "title": "Version Id",
          "type": "string"
        },
        "implementations": {
          "items": {
            "$ref": "#/$defs/InterfacePin"
          },
          "maxItems": 100,
          "minItems": 1,
          "title": "Implementations",
          "type": "array"
        }
      },
      "required": [
        "resource_id",
        "version_id",
        "implementations"
      ],
      "title": "InterfaceRoot",
      "type": "object"
    },
    "InterfaceValue": {
      "properties": {
        "object_id": {
          "format": "uuid",
          "title": "Object Id",
          "type": "string"
        },
        "object_version_id": {
          "format": "uuid",
          "title": "Object Version Id",
          "type": "string"
        },
        "implementation_resource_id": {
          "format": "uuid",
          "title": "Implementation Resource Id",
          "type": "string"
        },
        "implementation_version_id": {
          "format": "uuid",
          "title": "Implementation Version Id",
          "type": "string"
        },
        "schema_version_id": {
          "format": "uuid",
          "title": "Schema Version Id",
          "type": "string"
        },
        "status": {
          "enum": [
            "AVAILABLE",
            "SCHEMA_CHANGED"
          ],
          "title": "Status",
          "type": "string"
        },
        "values": {
          "anyOf": [
            {
              "additionalProperties": true,
              "type": "object"
            },
            {
              "type": "null"
            }
          ],
          "title": "Values"
        }
      },
      "required": [
        "object_id",
        "object_version_id",
        "implementation_resource_id",
        "implementation_version_id",
        "schema_version_id",
        "status",
        "values"
      ],
      "title": "InterfaceValue",
      "type": "object"
    },
    "PropertyFilter": {
      "additionalProperties": false,
      "properties": {
        "field": {
          "maxLength": 128,
          "minLength": 1,
          "title": "Field",
          "type": "string"
        },
        "value": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "integer"
            },
            {
              "type": "boolean"
            },
            {
              "items": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "integer"
                  },
                  {
                    "type": "boolean"
                  }
                ]
              },
              "maxItems": 100,
              "minItems": 1,
              "type": "array"
            },
            {
              "type": "null"
            }
          ],
          "title": "Value"
        },
        "operator": {
          "default": "eq",
          "enum": [
            "eq",
            "lt",
            "lte",
            "gt",
            "gte",
            "in",
            "not_in"
          ],
          "title": "Operator",
          "type": "string"
        }
      },
      "required": [
        "field",
        "value"
      ],
      "title": "PropertyFilter",
      "type": "object"
    },
    "QueryResource": {
      "additionalProperties": true,
      "properties": {
        "resource_id": {
          "format": "uuid",
          "title": "Resource Id",
          "type": "string"
        },
        "version_id": {
          "format": "uuid",
          "title": "Version Id",
          "type": "string"
        },
        "object_type": {
          "title": "Object Type",
          "type": "string"
        },
        "identity_key": {
          "title": "Identity Key",
          "type": "string"
        },
        "display_name": {
          "title": "Display Name",
          "type": "string"
        },
        "access_entity": {
          "title": "Access Entity",
          "type": "string"
        },
        "schema_version_id": {
          "anyOf": [
            {
              "format": "uuid",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Schema Version Id"
        },
        "attributes": {
          "additionalProperties": true,
          "title": "Attributes",
          "type": "object"
        },
        "content_hash": {
          "title": "Content Hash",
          "type": "string"
        },
        "valid_from": {
          "format": "date-time",
          "title": "Valid From",
          "type": "string"
        },
        "valid_to": {
          "anyOf": [
            {
              "format": "date-time",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Valid To"
        },
        "system_from": {
          "format": "date-time",
          "title": "System From",
          "type": "string"
        },
        "authority_state": {
          "enum": [
            "APPROVED",
            "REVOKED"
          ],
          "title": "Authority State",
          "type": "string"
        },
        "evidence_class": {
          "title": "Evidence Class",
          "type": "string"
        },
        "proposal_id": {
          "anyOf": [
            {
              "format": "uuid",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Proposal Id"
        }
      },
      "required": [
        "resource_id",
        "version_id",
        "object_type",
        "identity_key",
        "display_name",
        "access_entity",
        "schema_version_id",
        "attributes",
        "content_hash",
        "valid_from",
        "valid_to",
        "system_from",
        "authority_state",
        "evidence_class",
        "proposal_id"
      ],
      "title": "QueryResource",
      "type": "object"
    },
    "ResolvedQuery": {
      "additionalProperties": false,
      "properties": {
        "object_type": {
          "pattern": "^[A-Z][A-Za-z0-9]{1,63}$",
          "title": "Object Type",
          "type": "string"
        },
        "resource_ids": {
          "anyOf": [
            {
              "items": {
                "format": "uuid",
                "type": "string"
              },
              "maxItems": 100,
              "type": "array"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Resource Ids"
        },
        "filters": {
          "items": {
            "$ref": "#/$defs/PropertyFilter"
          },
          "maxItems": 20,
          "title": "Filters",
          "type": "array"
        },
        "traversal": {
          "items": {
            "$ref": "#/$defs/Traversal"
          },
          "maxItems": 4,
          "title": "Traversal",
          "type": "array"
        },
        "search": {
          "default": "",
          "maxLength": 128,
          "title": "Search",
          "type": "string"
        },
        "limit": {
          "default": 50,
          "maximum": 200,
          "minimum": 1,
          "title": "Limit",
          "type": "integer"
        },
        "offset": {
          "default": 0,
          "maximum": 1000000,
          "minimum": 0,
          "title": "Offset",
          "type": "integer"
        },
        "valid_at": {
          "format": "date-time",
          "title": "Valid At",
          "type": "string"
        },
        "known_at": {
          "format": "date-time",
          "title": "Known At",
          "type": "string"
        },
        "interface": {
          "anyOf": [
            {
              "$ref": "#/$defs/InterfaceRoot"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "type_group": {
          "anyOf": [
            {
              "$ref": "#/$defs/InterfacePin"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        }
      },
      "required": [
        "object_type",
        "valid_at",
        "known_at"
      ],
      "title": "ResolvedQuery",
      "type": "object"
    },
    "SharedField": {
      "additionalProperties": true,
      "properties": {
        "kind": {
          "title": "Kind",
          "type": "string"
        },
        "required": {
          "title": "Required",
          "type": "boolean"
        },
        "semantic_id": {
          "anyOf": [
            {
              "format": "uuid",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Semantic Id"
        },
        "target_type": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Target Type"
        }
      },
      "required": [
        "kind",
        "required"
      ],
      "title": "SharedField",
      "type": "object"
    },
    "Traversal": {
      "additionalProperties": false,
      "properties": {
        "kind": {
          "default": "reference",
          "enum": [
            "reference",
            "link"
          ],
          "title": "Kind",
          "type": "string"
        },
        "name": {
          "maxLength": 128,
          "minLength": 1,
          "title": "Name",
          "type": "string"
        },
        "direction": {
          "default": "outgoing",
          "enum": [
            "outgoing",
            "incoming"
          ],
          "title": "Direction",
          "type": "string"
        },
        "filters": {
          "items": {
            "$ref": "#/$defs/PropertyFilter"
          },
          "maxItems": 20,
          "title": "Filters",
          "type": "array"
        }
      },
      "required": [
        "name"
      ],
      "title": "Traversal",
      "type": "object"
    },
    "TraversalSchemaVersion": {
      "properties": {
        "object_type": {
          "title": "Object Type",
          "type": "string"
        },
        "resource_id": {
          "format": "uuid",
          "title": "Resource Id",
          "type": "string"
        },
        "version_id": {
          "format": "uuid",
          "title": "Version Id",
          "type": "string"
        },
        "step": {
          "maximum": 4,
          "minimum": 1,
          "title": "Step",
          "type": "integer"
        }
      },
      "required": [
        "object_type",
        "resource_id",
        "version_id",
        "step"
      ],
      "title": "TraversalSchemaVersion",
      "type": "object"
    },
    "TypeGroupBindings": {
      "properties": {
        "group": {
          "$ref": "#/$defs/HashedPin"
        },
        "schemas": {
          "items": {
            "$ref": "#/$defs/GroupSchemaBinding"
          },
          "title": "Schemas",
          "type": "array"
        },
        "fields": {
          "additionalProperties": {
            "$ref": "#/$defs/SharedField"
          },
          "title": "Fields",
          "type": "object"
        }
      },
      "required": [
        "group",
        "schemas",
        "fields"
      ],
      "title": "TypeGroupBindings",
      "type": "object"
    },
    "TypeGroupValue": {
      "properties": {
        "object_id": {
          "format": "uuid",
          "title": "Object Id",
          "type": "string"
        },
        "object_version_id": {
          "format": "uuid",
          "title": "Object Version Id",
          "type": "string"
        },
        "schema_version_id": {
          "format": "uuid",
          "title": "Schema Version Id",
          "type": "string"
        },
        "status": {
          "enum": [
            "AVAILABLE",
            "SCHEMA_CHANGED"
          ],
          "title": "Status",
          "type": "string"
        }
      },
      "required": [
        "object_id",
        "object_version_id",
        "schema_version_id",
        "status"
      ],
      "title": "TypeGroupValue",
      "type": "object"
    }
  },
  "properties": {
    "contract": {
      "const": "ontology-object-set/1",
      "title": "Contract",
      "type": "string"
    },
    "query": {
      "$ref": "#/$defs/ResolvedQuery"
    },
    "total": {
      "minimum": 0,
      "title": "Total",
      "type": "integer"
    },
    "counts_by_type": {
      "additionalProperties": {
        "type": "integer"
      },
      "title": "Counts By Type",
      "type": "object"
    },
    "objects": {
      "items": {
        "$ref": "#/$defs/QueryResource"
      },
      "title": "Objects",
      "type": "array"
    },
    "next_offset": {
      "anyOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "title": "Next Offset"
    },
    "filter_schema_versions": {
      "items": {
        "$ref": "#/$defs/FilterSchemaVersion"
      },
      "title": "Filter Schema Versions",
      "type": "array"
    },
    "traversal_schema_versions": {
      "items": {
        "$ref": "#/$defs/TraversalSchemaVersion"
      },
      "title": "Traversal Schema Versions",
      "type": "array"
    },
    "interface_bindings": {
      "anyOf": [
        {
          "$ref": "#/$defs/InterfaceBindings"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "interface_values": {
      "anyOf": [
        {
          "items": {
            "$ref": "#/$defs/InterfaceValue"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Interface Values"
    },
    "type_group_bindings": {
      "anyOf": [
        {
          "$ref": "#/$defs/TypeGroupBindings"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "type_group_values": {
      "anyOf": [
        {
          "items": {
            "$ref": "#/$defs/TypeGroupValue"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Type Group Values"
    }
  },
  "required": [
    "contract",
    "query",
    "total",
    "counts_by_type",
    "objects",
    "next_offset"
  ],
  "title": "ObjectSetResponse",
  "type": "object"
};

export const definedResponseSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$defs": {
    "FilterSchemaVersion": {
      "properties": {
        "object_type": {
          "title": "Object Type",
          "type": "string"
        },
        "resource_id": {
          "format": "uuid",
          "title": "Resource Id",
          "type": "string"
        },
        "version_id": {
          "format": "uuid",
          "title": "Version Id",
          "type": "string"
        }
      },
      "required": [
        "object_type",
        "resource_id",
        "version_id"
      ],
      "title": "FilterSchemaVersion",
      "type": "object"
    },
    "GroupSchemaBinding": {
      "properties": {
        "object_type": {
          "title": "Object Type",
          "type": "string"
        },
        "schema": {
          "$ref": "#/$defs/HashedPin"
        }
      },
      "required": [
        "object_type",
        "schema"
      ],
      "title": "GroupSchemaBinding",
      "type": "object"
    },
    "HashedPin": {
      "additionalProperties": false,
      "properties": {
        "resource_id": {
          "format": "uuid",
          "title": "Resource Id",
          "type": "string"
        },
        "version_id": {
          "format": "uuid",
          "title": "Version Id",
          "type": "string"
        },
        "content_hash": {
          "title": "Content Hash",
          "type": "string"
        }
      },
      "required": [
        "resource_id",
        "version_id",
        "content_hash"
      ],
      "title": "HashedPin",
      "type": "object"
    },
    "InterfaceBindings": {
      "properties": {
        "interface": {
          "$ref": "#/$defs/HashedPin"
        },
        "fields": {
          "additionalProperties": {
            "$ref": "#/$defs/SharedField"
          },
          "title": "Fields",
          "type": "object"
        },
        "implementations": {
          "items": {
            "$ref": "#/$defs/InterfaceImplementationBinding"
          },
          "title": "Implementations",
          "type": "array"
        }
      },
      "required": [
        "interface",
        "fields",
        "implementations"
      ],
      "title": "InterfaceBindings",
      "type": "object"
    },
    "InterfaceImplementationBinding": {
      "properties": {
        "implementation": {
          "$ref": "#/$defs/HashedPin"
        },
        "schema": {
          "$ref": "#/$defs/HashedPin"
        },
        "object_type": {
          "title": "Object Type",
          "type": "string"
        },
        "fields": {
          "additionalProperties": {
            "type": "string"
          },
          "title": "Fields",
          "type": "object"
        }
      },
      "required": [
        "implementation",
        "schema",
        "object_type",
        "fields"
      ],
      "title": "InterfaceImplementationBinding",
      "type": "object"
    },
    "InterfacePin": {
      "additionalProperties": false,
      "properties": {
        "resource_id": {
          "format": "uuid",
          "title": "Resource Id",
          "type": "string"
        },
        "version_id": {
          "format": "uuid",
          "title": "Version Id",
          "type": "string"
        }
      },
      "required": [
        "resource_id",
        "version_id"
      ],
      "title": "InterfacePin",
      "type": "object"
    },
    "InterfaceRoot": {
      "additionalProperties": false,
      "properties": {
        "resource_id": {
          "format": "uuid",
          "title": "Resource Id",
          "type": "string"
        },
        "version_id": {
          "format": "uuid",
          "title": "Version Id",
          "type": "string"
        },
        "implementations": {
          "items": {
            "$ref": "#/$defs/InterfacePin"
          },
          "maxItems": 100,
          "minItems": 1,
          "title": "Implementations",
          "type": "array"
        }
      },
      "required": [
        "resource_id",
        "version_id",
        "implementations"
      ],
      "title": "InterfaceRoot",
      "type": "object"
    },
    "InterfaceValue": {
      "properties": {
        "object_id": {
          "format": "uuid",
          "title": "Object Id",
          "type": "string"
        },
        "object_version_id": {
          "format": "uuid",
          "title": "Object Version Id",
          "type": "string"
        },
        "implementation_resource_id": {
          "format": "uuid",
          "title": "Implementation Resource Id",
          "type": "string"
        },
        "implementation_version_id": {
          "format": "uuid",
          "title": "Implementation Version Id",
          "type": "string"
        },
        "schema_version_id": {
          "format": "uuid",
          "title": "Schema Version Id",
          "type": "string"
        },
        "status": {
          "enum": [
            "AVAILABLE",
            "SCHEMA_CHANGED"
          ],
          "title": "Status",
          "type": "string"
        },
        "values": {
          "anyOf": [
            {
              "additionalProperties": true,
              "type": "object"
            },
            {
              "type": "null"
            }
          ],
          "title": "Values"
        }
      },
      "required": [
        "object_id",
        "object_version_id",
        "implementation_resource_id",
        "implementation_version_id",
        "schema_version_id",
        "status",
        "values"
      ],
      "title": "InterfaceValue",
      "type": "object"
    },
    "PropertyFilter": {
      "additionalProperties": false,
      "properties": {
        "field": {
          "maxLength": 128,
          "minLength": 1,
          "title": "Field",
          "type": "string"
        },
        "value": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "integer"
            },
            {
              "type": "boolean"
            },
            {
              "items": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "integer"
                  },
                  {
                    "type": "boolean"
                  }
                ]
              },
              "maxItems": 100,
              "minItems": 1,
              "type": "array"
            },
            {
              "type": "null"
            }
          ],
          "title": "Value"
        },
        "operator": {
          "default": "eq",
          "enum": [
            "eq",
            "lt",
            "lte",
            "gt",
            "gte",
            "in",
            "not_in"
          ],
          "title": "Operator",
          "type": "string"
        }
      },
      "required": [
        "field",
        "value"
      ],
      "title": "PropertyFilter",
      "type": "object"
    },
    "QueryResource": {
      "additionalProperties": true,
      "properties": {
        "resource_id": {
          "format": "uuid",
          "title": "Resource Id",
          "type": "string"
        },
        "version_id": {
          "format": "uuid",
          "title": "Version Id",
          "type": "string"
        },
        "object_type": {
          "title": "Object Type",
          "type": "string"
        },
        "identity_key": {
          "title": "Identity Key",
          "type": "string"
        },
        "display_name": {
          "title": "Display Name",
          "type": "string"
        },
        "access_entity": {
          "title": "Access Entity",
          "type": "string"
        },
        "schema_version_id": {
          "anyOf": [
            {
              "format": "uuid",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Schema Version Id"
        },
        "attributes": {
          "additionalProperties": true,
          "title": "Attributes",
          "type": "object"
        },
        "content_hash": {
          "title": "Content Hash",
          "type": "string"
        },
        "valid_from": {
          "format": "date-time",
          "title": "Valid From",
          "type": "string"
        },
        "valid_to": {
          "anyOf": [
            {
              "format": "date-time",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Valid To"
        },
        "system_from": {
          "format": "date-time",
          "title": "System From",
          "type": "string"
        },
        "authority_state": {
          "enum": [
            "APPROVED",
            "REVOKED"
          ],
          "title": "Authority State",
          "type": "string"
        },
        "evidence_class": {
          "title": "Evidence Class",
          "type": "string"
        },
        "proposal_id": {
          "anyOf": [
            {
              "format": "uuid",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Proposal Id"
        }
      },
      "required": [
        "resource_id",
        "version_id",
        "object_type",
        "identity_key",
        "display_name",
        "access_entity",
        "schema_version_id",
        "attributes",
        "content_hash",
        "valid_from",
        "valid_to",
        "system_from",
        "authority_state",
        "evidence_class",
        "proposal_id"
      ],
      "title": "QueryResource",
      "type": "object"
    },
    "ResolvedQuery": {
      "additionalProperties": false,
      "properties": {
        "object_type": {
          "pattern": "^[A-Z][A-Za-z0-9]{1,63}$",
          "title": "Object Type",
          "type": "string"
        },
        "resource_ids": {
          "anyOf": [
            {
              "items": {
                "format": "uuid",
                "type": "string"
              },
              "maxItems": 100,
              "type": "array"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Resource Ids"
        },
        "filters": {
          "items": {
            "$ref": "#/$defs/PropertyFilter"
          },
          "maxItems": 20,
          "title": "Filters",
          "type": "array"
        },
        "traversal": {
          "items": {
            "$ref": "#/$defs/Traversal"
          },
          "maxItems": 4,
          "title": "Traversal",
          "type": "array"
        },
        "search": {
          "default": "",
          "maxLength": 128,
          "title": "Search",
          "type": "string"
        },
        "limit": {
          "default": 50,
          "maximum": 200,
          "minimum": 1,
          "title": "Limit",
          "type": "integer"
        },
        "offset": {
          "default": 0,
          "maximum": 1000000,
          "minimum": 0,
          "title": "Offset",
          "type": "integer"
        },
        "valid_at": {
          "format": "date-time",
          "title": "Valid At",
          "type": "string"
        },
        "known_at": {
          "format": "date-time",
          "title": "Known At",
          "type": "string"
        },
        "interface": {
          "anyOf": [
            {
              "$ref": "#/$defs/InterfaceRoot"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "type_group": {
          "anyOf": [
            {
              "$ref": "#/$defs/InterfacePin"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        }
      },
      "required": [
        "object_type",
        "valid_at",
        "known_at"
      ],
      "title": "ResolvedQuery",
      "type": "object"
    },
    "SharedField": {
      "additionalProperties": true,
      "properties": {
        "kind": {
          "title": "Kind",
          "type": "string"
        },
        "required": {
          "title": "Required",
          "type": "boolean"
        },
        "semantic_id": {
          "anyOf": [
            {
              "format": "uuid",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Semantic Id"
        },
        "target_type": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Target Type"
        }
      },
      "required": [
        "kind",
        "required"
      ],
      "title": "SharedField",
      "type": "object"
    },
    "Traversal": {
      "additionalProperties": false,
      "properties": {
        "kind": {
          "default": "reference",
          "enum": [
            "reference",
            "link"
          ],
          "title": "Kind",
          "type": "string"
        },
        "name": {
          "maxLength": 128,
          "minLength": 1,
          "title": "Name",
          "type": "string"
        },
        "direction": {
          "default": "outgoing",
          "enum": [
            "outgoing",
            "incoming"
          ],
          "title": "Direction",
          "type": "string"
        },
        "filters": {
          "items": {
            "$ref": "#/$defs/PropertyFilter"
          },
          "maxItems": 20,
          "title": "Filters",
          "type": "array"
        }
      },
      "required": [
        "name"
      ],
      "title": "Traversal",
      "type": "object"
    },
    "TraversalSchemaVersion": {
      "properties": {
        "object_type": {
          "title": "Object Type",
          "type": "string"
        },
        "resource_id": {
          "format": "uuid",
          "title": "Resource Id",
          "type": "string"
        },
        "version_id": {
          "format": "uuid",
          "title": "Version Id",
          "type": "string"
        },
        "step": {
          "maximum": 4,
          "minimum": 1,
          "title": "Step",
          "type": "integer"
        }
      },
      "required": [
        "object_type",
        "resource_id",
        "version_id",
        "step"
      ],
      "title": "TraversalSchemaVersion",
      "type": "object"
    },
    "TypeGroupBindings": {
      "properties": {
        "group": {
          "$ref": "#/$defs/HashedPin"
        },
        "schemas": {
          "items": {
            "$ref": "#/$defs/GroupSchemaBinding"
          },
          "title": "Schemas",
          "type": "array"
        },
        "fields": {
          "additionalProperties": {
            "$ref": "#/$defs/SharedField"
          },
          "title": "Fields",
          "type": "object"
        }
      },
      "required": [
        "group",
        "schemas",
        "fields"
      ],
      "title": "TypeGroupBindings",
      "type": "object"
    },
    "TypeGroupValue": {
      "properties": {
        "object_id": {
          "format": "uuid",
          "title": "Object Id",
          "type": "string"
        },
        "object_version_id": {
          "format": "uuid",
          "title": "Object Version Id",
          "type": "string"
        },
        "schema_version_id": {
          "format": "uuid",
          "title": "Schema Version Id",
          "type": "string"
        },
        "status": {
          "enum": [
            "AVAILABLE",
            "SCHEMA_CHANGED"
          ],
          "title": "Status",
          "type": "string"
        }
      },
      "required": [
        "object_id",
        "object_version_id",
        "schema_version_id",
        "status"
      ],
      "title": "TypeGroupValue",
      "type": "object"
    }
  },
  "properties": {
    "contract": {
      "const": "ontology-object-set/1",
      "title": "Contract",
      "type": "string"
    },
    "query": {
      "$ref": "#/$defs/ResolvedQuery"
    },
    "total": {
      "minimum": 0,
      "title": "Total",
      "type": "integer"
    },
    "counts_by_type": {
      "additionalProperties": {
        "type": "integer"
      },
      "title": "Counts By Type",
      "type": "object"
    },
    "objects": {
      "items": {
        "$ref": "#/$defs/QueryResource"
      },
      "title": "Objects",
      "type": "array"
    },
    "next_offset": {
      "anyOf": [
        {
          "minimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "title": "Next Offset"
    },
    "filter_schema_versions": {
      "items": {
        "$ref": "#/$defs/FilterSchemaVersion"
      },
      "title": "Filter Schema Versions",
      "type": "array"
    },
    "traversal_schema_versions": {
      "items": {
        "$ref": "#/$defs/TraversalSchemaVersion"
      },
      "title": "Traversal Schema Versions",
      "type": "array"
    },
    "interface_bindings": {
      "anyOf": [
        {
          "$ref": "#/$defs/InterfaceBindings"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "interface_values": {
      "anyOf": [
        {
          "items": {
            "$ref": "#/$defs/InterfaceValue"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Interface Values"
    },
    "type_group_bindings": {
      "anyOf": [
        {
          "$ref": "#/$defs/TypeGroupBindings"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "type_group_values": {
      "anyOf": [
        {
          "items": {
            "$ref": "#/$defs/TypeGroupValue"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Type Group Values"
    },
    "definition_id": {
      "format": "uuid",
      "title": "Definition Id",
      "type": "string"
    },
    "definition_version_id": {
      "format": "uuid",
      "title": "Definition Version Id",
      "type": "string"
    }
  },
  "required": [
    "contract",
    "query",
    "total",
    "counts_by_type",
    "objects",
    "next_offset",
    "definition_id",
    "definition_version_id"
  ],
  "title": "DefinedObjectSetResponse",
  "type": "object"
};
