/** Wire mirror of the canonical semantic-analysis/1 and /2 projections. No rendering authority. */
export type AnalysisScalar = string | number | boolean | null;
export type AnalysisPin = {resource_id:string;version_id:string;content_hash:string};
export type AnalysisValue = {state:"VALUE"|"NULL"|"MISSING";value:AnalysisScalar;label:string|null;reference:AnalysisPin|null};
export type AnalysisFilter = Pick<AnalysisValue,"state"|"value"> & {field:string};
export type AnalysisRequest = {invocation_id:string;company_id:string;descriptor_sha256?:string|null;filters?:AnalysisFilter[];group_by?:string|null;selected_row?:string|null;contributor_index?:number};
export type AnalysisField = {key:string;label:string;kind:"text"|"identifier"|"reference"|"integer"|"decimal"|"boolean"|"date"|"datetime";role:"DIMENSION"|"MEASURE"|"ATTRIBUTE";unit:string|null;unit_reference:AnalysisPin|null;definition:AnalysisPin;semantic_id:string|null;field_id?:string|null;filterable:boolean;groupable:boolean;aggregation:"NONE"|"RETAINED_VALUE_ONLY";options:AnalysisValue[]};
export type AnalysisRow = {key:string;label:string;values:Record<string,AnalysisValue>;contributor_count:number;trace:AnalysisPin};
export type AnalysisContributor = {basis?:"ORIGINAL_SOURCE"|"CANONICAL_DEFINITION"|"UNAVAILABLE";label:string;reference:AnalysisPin;cells:Array<{label:string;value:AnalysisScalar;coordinate:string|null;formula:string|null}>;document_id:string|null;source_sha256:string|null;sheet:string|null;coordinate:string|null};
export type AnalysisDescriptor = {contract:"semantic-analysis/1"|"semantic-analysis/2";row_noun?:"groups"|"objects";invocation_id:string;receipt_hash:string;run_id:string;function:AnalysisPin;company:AnalysisPin;company_label:string;title:string;grain:string[];partition_keys:string[];excluded_evidence:AnalysisContributor[];fields:AnalysisField[];measure:string|null;visual:"HORIZONTAL_BARS"|"NONE";filtering:"RETAINED_GROUP_SELECTION";grouping:"RETAINED_ROWS_WITHOUT_AGGREGATION";authority:string;coverage:Array<{label:string;value:string}>;context:Array<{label:string;value:string}>;valid_at:string;known_at:string;recorded_at:string;definitions:AnalysisPin[];unavailable_operations:string[];current_use_authorized:false;business_effect_authorized:false};
export type AnalysisProjection = {descriptor:AnalysisDescriptor;descriptor_sha256:string;rows:AnalysisRow[];total_rows:number;sections:Array<{label:string;row_keys:string[]}>;selection:{row_key:string;contributor_index:number;contributor_count:number;contributor:AnalysisContributor}|null;request:AnalysisRequest};
