"""Generate portable SDK wire types and validators' schemas from the actual API models."""

import argparse
import hashlib
import json
from pathlib import Path

from finai_api.domain.object_sets import ObjectSetQuery
from finai_api.domain.ontology_query_wire import (
    DefinedObjectSetResponse,
    ObjectSetResponse,
)

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "packages/contracts/src/ontology-wire.ts"
MODELS = {
    "querySchema": ObjectSetQuery,
    "responseSchema": ObjectSetResponse,
    "definedResponseSchema": DefinedObjectSetResponse,
}


def ts_type(schema):
    """Emit the types used by these models; unsupported constructs fail generation."""
    if not schema:
        return "unknown"
    if "$ref" in schema:
        return "Wire" + schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return "(" + " | ".join(ts_type(item) for item in schema["anyOf"]) + ")"
    kind = schema.get("type")
    if kind in {"string", "boolean", "null"}:
        return kind
    if kind in {"integer", "number"}:
        return "number"
    if kind == "array":
        return "Array<" + ts_type(schema["items"]) + ">"
    if kind == "object":
        props = schema.get("properties", {})
        required = schema.get("required", [])
        parts = [
            f"{json.dumps(name)}{' ' if name in required else '?'}: {ts_type(spec)};"
            for name, spec in props.items()
        ]
        extra = schema.get("additionalProperties", True)
        if extra is not False:
            parts.append(
                "[key: string]: "
                + (ts_type(extra) if isinstance(extra, dict) else "unknown")
                + ";"
            )
        return "{ " + " ".join(parts) + " }"
    raise ValueError(f"Unsupported SDK type schema: {schema}")


def generate():
    schemas = {
        name: {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            **model.model_json_schema(),
        }
        for name, model in MODELS.items()
    }
    digest = hashlib.sha256(json.dumps(schemas, sort_keys=True).encode()).hexdigest()
    definitions = {}
    for name, model in MODELS.items():
        schema = schemas[name]
        for title, definition in {
            **schema.get("$defs", {}),
            model.__name__: schema,
        }.items():
            if title in definitions and ts_type(definitions[title]) != ts_type(
                definition
            ):
                raise ValueError(f"Conflicting generated type: {title}")
            definitions[title] = definition
    lines = [
        "// Generated by scripts/generate-ontology-query-contracts.py. Do not edit.",
        "// Dynamic resource attributes remain owned by the canonical ontology schemas.",
        'export const ontologyQueryWireVersion = "ontology-object-set/1";',
        f'export const ontologyQuerySchemaSha256 = "{digest}";',
    ]
    lines += [
        f"export type Wire{name} = {ts_type(value)};"
        for name, value in definitions.items()
    ]
    lines += [
        f"export const {name} = {json.dumps(value, indent=2, ensure_ascii=False)};"
        for name, value in schemas.items()
    ]
    return "\n\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit(
                "Ontology query contracts differ; regenerate before shipping."
            )
        print("Generated ontology query contracts match the canonical API models.")
    else:
        OUTPUT.write_text(content, encoding="utf-8", newline="\n")
        print("Generated ontology query wire types and JSON schemas.")


if __name__ == "__main__":
    main()
